= Аннотация

== Область применения

Модуль "Базовые объекты" добавляет в систему "Docsvision 5.5" (далее – "Docsvision") базовые сущности для возможности организации электронного документооборота.

Модуль предполагается применять в организациях, использующих систему Docsvision.== Назначение документа

Настоящий документ является руководством пользователя модуля "Docsvision 5. Базовые объекты" (далее – "Модуль").

Документ содержит инструкцию по установке Модуля (серверной и клиентской частей); перечислены функции _администратора Docsvision_. Описание _конструкторов_ и _справочников_ Модуля приведено в документе _Модуль "Docsvision 5. Базовые объекты". Описание конструкторов и справочников_. Описание карточек Модуля приведено в документе _Модуль "Docsvision 5. Базовые объекты". Руководство пользователя_

Документ содержит общую информацию о карточках Модуля (документ, задание, группа заданий и бизнес-календарь), инструкцию по выполнению заданий с использованием почтового клиента.

Настоящий документ содержит описание справочников и конструкторов модуля "Docsvision 5. Базовые объекты" (далее – "Модуль").

[NOTE]
====
Описание конструкторов и справочников Модуля приведено в документе _Модуль "Docsvision 5. Базовые объекты". Руководство администратора_.
====

Документ предназначен для пользователей системы Docsvision.

== Как организован документ

.Настоящее руководство содержит следующие разделы:
. xref:user:first-launch.adoc[Подготовка к работе] (приведены условия для работы с карточками Модуля в программе Windows-клиент/РМА).
. xref:user:Operations.adoc[Описание операций] (приведено описание операций с карточками _Документ_, _Задание_, _Группа заданий_ и _Бизнес-календарь_).
. xref:requirements.adoc[] (приведены требования Модуля к программному и аппаратному обеспечению компьютера).
. Раздел xref:desdirs:Conditions.adoc[Условия использования конструкторов и справочников] (перечислены условия, которые требуется соблюдать при работе с конструкторами и справочникам)
. Отдельные разделы с описанием справочников и конструкторов. (Описание включает: описание пользовательского интерфейса конструктора или справочника при работе в Windows-клиенте, и инструкцию по работе с данным справочником или конструктором.)
. xref:module-structure.adoc[Структура Модуля] (перечислены составные части Модуля).
. xref:admin:installation.adoc[Установка и настройка] (содержит инструкцию по установке и настройке Модуля).
. xref:admin:update-module.adoc[Установка новой версии модуля] (содержит инструкцию по установке новой версии Модуля).
. xref:admin:Administrator_functions.adoc[Функции администратора] (содержит описание настроек Модуля, выполняемых администратором Docsvision).
. xref:admin:General_settings.adoc[Описание настроек модуля в справочнике "Системные настройки"] (содержит описание настроек Модуля в справочнике Системные настройки).
