= Аннотация

= Назначение документа

Настоящий документ является руководством пользователя модуля "Docsvision 5. Базовые объекты" (далее – "Модуль").

Документ содержит общую информацию о карточках Модуля (документ, задание, группа заданий и бизнес-календарь), инструкцию по выполнению заданий с использованием почтового клиента.

[NOTE]
====
Описание конструкторов и справочников Модуля приведено в документе _Модуль "Docsvision 5. Базовые объекты". Руководство администратора_.
====

Документ предназначен для пользователей системы Docsvision.

= Как организован документ

Настоящее руководство содержит следующие разделы:

. xref:Introduction.adoc[Введение] (приведены общие сведения о Модуле, требования к подготовке пользователей).
. xref:Preparationfor_work.adoc[Подготовка к работе] (приведены условия для работы с карточками Модуля в программе Windows-клиент/РМА).
. xref:Operations.adoc[Описание операций] (приведено описание операций с карточками _Документ_, _Задание_, _Группа заданий_ и _Бизнес-календарь_).

= Соглашения по оформлению

В данном документе для представления различных терминов и названий используются следующие шрифты и средства форматирования.

[width="99%",cols="34%,66%",options="header",]
|===
|Шрифт |Описание
|*Жирный* |Используется при написании названий элементов экранного интерфейса.
|_Курсив_ |Используется для обозначения новых терминов, названий типов и видов карточек.
|http://docsvision.com[Синий] |Используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц.
|`Моноширинный` |Используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним. Также используется для указания необходимой опции, выделения значений, задаваемых пользователем с клавиатуры.
|===

Некоторые абзацы в тексте содержат информацию, на которую следует обратить особое внимание. Эти абзацы выделены в специальные блоки.

[IMPORTANT]
====
Служит для привлечения внимания пользователя к информации, которая необходима для корректного восприятия изложенного далее текста, и к указаниям, которые настоятельно рекомендуется выполнять.
====

[NOTE]
====
Используется для отображения информации дополнительного характера.
====
