= Аннотация

== Область применения

модуль _{bo}_ добавляет в систему "{dv} 5.5" (далее -- "{dv}") базовые сущности для возможности организации электронного документооборота.

модуль предполагается применять в организациях, использующих систему {dv}.== Назначение документа

Настоящий документ является руководством пользователя модуля "{dv} 5. {bo}" (далее -- "модуль").

Документ содержит инструкцию по установке модуля (серверной и клиентской частей); перечислены функции _администратора {dv}_. Описание _конструкторов_ и _справочников_ модуля приведено в документе _модуль "{dv} 5. {bo}". Описание конструкторов и справочников_. Описание карточек модуля приведено в документе _модуль "{dv} 5. {bo}". Руководство пользователя_

Документ содержит общую информацию о карточках модуля (документ, задание, группа заданий и бизнес-календарь), инструкцию по выполнению заданий с использованием почтового клиента.

Настоящий документ содержит описание справочников и конструкторов модуля "{dv} 5. {bo}" (далее -- "модуль").

[NOTE]
====
Описание конструкторов и справочников модуля приведено в документе _модуль "{dv} 5. {bo}". Руководство администратора_.
====

Документ предназначен для пользователей системы {dv}.

== Как организован документ

.Настоящее руководство содержит следующие разделы:
. xref:user:first-launch.adoc[Подготовка к работе] (приведены условия для работы с карточками модуля в программе Windows-клиент/РМА).
. xref:user:Operations.adoc[Описание операций] (приведено описание операций с карточками _Документ_, _Задание_, _Группа заданий_ и _Бизнес-календарь_).
. xref:requirements.adoc[] (приведены требования модуля к программному и аппаратному обеспечению компьютера).
. Раздел xref:desdirs:Conditions.adoc[Условия использования конструкторов и справочников] (перечислены условия, которые требуется соблюдать при работе с конструкторами и справочникам)
. Отдельные разделы с описанием справочников и конструкторов. (Описание включает: описание пользовательского интерфейса конструктора или справочника при работе в Windows-клиенте, и инструкцию по работе с данным справочником или конструктором.)
. xref:module-structure.adoc[Структура модуля] (перечислены составные части модуля).
. xref:admin:install.adoc[Установка и настройка] (содержит инструкцию по установке и настройке модуля).
. xref:admin:update-module.adoc[Установка новой версии модуля] (содержит инструкцию по установке новой версии модуля).
. Функции администратора (содержит описание настроек модуля, выполняемых администратором {dv}).
. xref:admin:General_settings.adoc[Описание настроек модуля в справочнике "Системные настройки"] (содержит описание настроек модуля в справочнике Системные настройки).
