= Папки

Модуль "Базовые объекты" добавляет в систему Docsvision папки:

* "Почтовый клиент"
** "Задания" – папка для хранения виртуальных папок с настроенными поисковыми запросами, обеспечивающими создание и синхронизацию задач Outlook по заданиям Docsvision (используется модулем "Docsvision 5. Панель инструментов для Microsoft Office"):
*** "Задания мне" – в папке отображаются карточки _Задание_ в состояниях `Не начато`, `В                                     работе`, `Делегировано`, `На                                     доработке`, `Возврат с                                     делегирования`, `Отложено`, `Завершено`, в которых текущий пользователь указан как _Исполнитель_ или является временным заместителем назначенного исполнителя;
*** "Задания от меня" – в папке отображаются карточки _Задание_ в состояниях `Не                                     начато`, `В работе`, `Делегировано`, `На                                     доработке`, `Возврат с                                     делегирования`, `Отложено`, в которых текущий пользователь указан как _Автор_ или которые он ранее делегировал;
** "Служебные" – папка с шаблонами БП, которые обеспечивают обработку решений по заданиями, полученным по электронной почте.

