= Общие сведения о модуле

== Область применения

Модуль _{bo}_ добавляет в систему {dv} базовые сущности для возможности организации электронного документооборота.

Модуль предполагается применять в организациях, использующих систему {dv}.

== Краткое описание возможностей

Модуль _{bo}_ является базовым модулем {dv} и добавляет в систему базовые типы карточек, основные справочники и конструкторы, а именно:

* Карточки: _Бизнес-календарь_, _Группа заданий_, _Документ_, _Задание_, _Карточка подразделения_, _Карточка подразделения контрагента_, _Карточка сервера_, _Карточка сотрудника_, _Карточка сотрудника контрагента_, _Карточка строки справочника_, _Согласование_.
* Справочники:__ Справочник видов карточек__, _Справочник категорий_, _Справочник контрагентов_, _Справочник меток подписей_, _Справочник серверов_, _Справочник сотрудников_ и _Справочник ссылок_.
* Конструкторы: _Конструктор правил нумерации_, _Конструктор разметок_, _Конструктор ролей_, _Конструктор скриптов_, _Конструктор состояний_, _Конструктор справочников_.

.Модуль предоставляет следующие возможности:
* Создание (с минимальным набором данных и возможностей) карточек документов, заданий и групп заданий.
* Ведение списка организаций и сотрудников организаций.
* Управление группами пользователей.
* Ведение списка контрагентов и сотрудников контрагентов.
* Настройка правил автоматической нумерации документов.
* Настройка разметок карточек.
* Настройка автомата состояний карточек.
* Настройка ролевой модели безопасности.
* Разработка скриптов карточек на языках C# и VB.NET.
* Оповещение исполнителей заданий по электронной почте.
* Рассылка и выполнение заданий по электронной почте.

== Назначение документации

Настоящий документ является руководством пользователя модуля {bo} (далее -- "модуль").

.Документация содержит следующие разделы:
- xref:module-structure.adoc[Структура модуля] -- перечислены составные части модуля.
- xref:admin:install.adoc[Инструкцию] по установке серверной и клиентской частей модуля.
- xref:admin:update-module.adoc[Инструкцию] по обновлению версии модуля-- содержит инструкцию по установке новой версии модуля.
- xref:admin:system-settings.adoc[Описание] настроек модуля в справочнике "Системные настройки" -- содержит описание настроек модуля в справочнике Системные настройки.
- Функции администратора -- перечислены функции _администратора {dv}_.
- xref:desdirs:conditions.adoc[Описание] _конструкторов_ и _справочников_ модуля.
- Работа с модулем -- приведено описание операций с карточками _Документ_, _Задание_, _Группа заданий_ и _Бизнес-календарь_.
- xref:user:first-launch.adoc[Подготовка к работе] -- приведены условия для работы с карточками модуля в программе {wincl}/РМА.
- xref:requirements.adoc[]-- приведены требования модуля к программному и аппаратному обеспечению компьютера.
- xref:desdirs:conditions.adoc[Условия] использования конструкторов и справочников -- перечислены условия, которые требуется соблюдать при работе с конструкторами и справочниками.
