= Структура модуля

Модуль _{bo}_ состоит из двух частей: серверной и клиентской.

.Серверная часть для установки на компьютер с сервером {dv} включает:
. Библиотеку карточек _{bo}_.
. Добавляемые в систему {dv} <<bps,Бизнес-процессы>> и <<folders,Папки>>.
. Библиотеки DLL с объектной моделью карточек модуля, _функциями_ (бизнес-процессов) для работы с объектами модуля в БП.
. Пакет установки клиентской части модуля _{bo}_.

.Клиентская часть для установки на компьютеры пользователей {dv} включает:
. Библиотеки DLL с компонентом библиотеки карточек _{bo}_, объектной моделью карточек модуля и элементами пользовательского интерфейса карточек модуля для {wincl}а и РМА.

[#bps]
== Бизнес-процессы

Модуль _{bo}_ добавляет в систему {dv} бизнес-процессы, перечисленные далее.

Маршрутизация заданий в почту::
+
.БП "Маршрутизация заданий в почту" выполняет следующие действия:
. Отыскивает карточки Задание (всех видов), если:
+
* Состояние задания `Начато`, `Делегировано`, `Возвращено с делегирования`.
* У исполнителя задания установлен способ маршрутизации *_Письмо с описанием задания_* или *_Задача Почтового клиента_*;
* В текущий момент времени задание не обрабатывается никаким бизнес-процессом.
+
. Формирует почтовое сообщение с заданием и отсылает его пользователю.

ПК Мониторинг почты::
+
.БП "ПК Мониторинг почты" выполняет следующие действия:
. С периодичностью, указанной в свойствах функции _Сообщения задания 5_ (вкладка _Общие_, поле _Период опроса, мин_, по умолчанию `5 минут`) БП отыскивает непрочитанные письма о совершении из почтового сообщения некоторого действия с заданием (тема сообщения начинается с `86D0BBBE:`).
. Обрабатывает каждое из полученных сообщений.
+
Каждое полученное письмо о совершении действия обрабатывается только один раз. В случае сбоя в работе почтового сервера обработка будет начата с последнего непрочитанного сообщения.
+
. Переводит обработанное сообщение в прочитанные.

ПК Взятие задания в работу::
+
.БП "ПК Взятие задания в работу" выполняет следующие действия:
. Получает из БП "ПК Мониторинг почты" ответное письмо по действию _В работу_.
. Обрабатывает это письмо.
. Записывает результаты в карточку задания {dv}, изменяя состояние задания.
. Отсылает пользователю уведомление о результате выполнения: задание успешно взято в работу или этого не произошло.

ПК Завершение задания::
+
.БП "ПК Завершение задания" выполняет следующие действия:
. Получает из БП "ПК Мониторинг почты" ответное письмо по действию _Завершить_.
. Обрабатывает это письмо.
. Записывает результаты в карточку задания {dv}.
. Отсылает пользователю уведомление о результате выполнения: задание успешно завершено или этого не произошло.

ПК Отклонение задания::
+
.БП "ПК Отклонение задания" выполняет следующие действия:
. Получает из БП "ПК Мониторинг почты" ответное письмо по действию _Отклонить_.
. Обрабатывает это письмо.
. Записывает результаты в карточку задания {dv}.
. Отсылает пользователю уведомление о результате выполнения: задание успешно отклонено или этого не произошло.

[#folders]
== Папки

.Модуль _{bo}_ добавляет в систему {dv} папки:
* `Почтовый клиент`
** `Задания` -- папка для хранения виртуальных папок с настроенными поисковыми запросами, обеспечивающими создание и синхронизацию задач Outlook по заданиям {dv}. Используется модулем "{dv} 5. Панель инструментов для Microsoft Office".
*** `Задания мне` -- в папке отображаются карточки _Задание_ в состояниях `Не начато`, `В работе`, `Делегировано`, `На доработке`, `Возврат с делегирования`, `Отложено`, `Завершено`, в которых текущий пользователь указан как _Исполнитель_ или является временным заместителем назначенного исполнителя.
*** `Задания от меня` -- в папке отображаются карточки _Задание_ в состояниях `Не начато`, `В работе`, `Делегировано`, `На доработке`, `Возврат с делегирования`, `Отложено`, в которых текущий пользователь указан как _Автор_ или которые он ранее делегировал.
** `Служебные` -- папка с шаблонами БП, которые обеспечивают обработку решений по заданиям, полученным по электронной почте.

