= Необходимые ресурсы

[#hard]
== Необходимое техническое обеспечение

[#hard-server]
=== Требования серверной части модуля

Специальные требования к аппаратному обеспечению не предъявляются.

[#hard-client]
=== Требования клиентской части модуля

Для возможности сканирования в {wincl}е/РМА документов из карточек модуля требуется любой WIA-совместимый сканер с WIA-драйвером.

.Сканеры, сертифицированные для работы в системе {dv}:
* WIA: Epson Workforce PS-6500.
* TWAIN: Epson GT-S55, Epson P-215.

[CAUTION]
====
Рекомендуется проверить совместимость с конкретными сканерами до начала использования продукта.

Компания "ДоксВижн" не несет ответственности за некорректную работу сканеров и иного оборудования. Несовместимость с конкретной моделью сканера, или отличия в поведении сканирования из системы {dv} по сравнению со сканированием в стороннем ПО не могут являться основанием для рекламации или обращения в техническую поддержку {dv}.
====

[#soft]
== Необходимое программное обеспечение

База данных {dv} должна работать с расширенными метаданными. Работа с базой данных с динамическими метаданными не поддерживается.

Для корректной работы данной версии модуля "{bo}" требуется установить *серверную* и *клиентскую* части следующих модулей:

. Модуль {pl} {pl-req} и выше.
. Модуль {dm} {ud-req} и выше.
. Приложение {wf} {wf-req} и выше.
. Модуль {ad} {ad-req} и выше.
. Модуль Делопроизводство 4.5 {dp-req} и выше.
. Приложение {wincl} {win-req} и выше.
. Модуль Служба {ws} версии {ws-req} и выше.
+
Модуль требуется для полноценной работы *групп заданий*. +
Для создания *заданий* устанавливать Службу {ws} не требуется, однако, такая возможность будет отключена в следующих версиях.

[#additional]
== Дополнительное программное обеспечение

. xref:admin:prepare-abbyy.adoc[ABBYY FineReader Engine] 11.0 (32-разрядная версия) -- для работы функции распознавания в карточках модуля (в т.ч. для потокового ввода документов и распознавания штрих-кодов).
. Почтовый клиент -- для работы с заданиями, маршрутизируемыми в почту.

.Известные проблемы совместимости:
****
При использовании почтового клиента Gmail в операционной системе iOS, а также Microsoft Outlook в операционной системе Android, при формировании ответного письма часть содержимого темы письма обрезается, что делает невозможным обработку данных писем на сервере {dv}. Используйте альтернативные почтовые клиенты в данном случае.
****

[#crypto-pro]
=== Программное обеспечение, необходимое для работы с сертификатами КриптоПро

Следующее программное обеспечение должно быть установлено на компьютере для использования сертификатов УЦ КриптоПро для формирования и проверки усиленной квалифицированной или усовершенствованной ЭП.

[#crypto-client]
==== Требования к клиентским рабочим местам

.Компоненты криптопровайдера "КриптоПро":
* КриптоПро CSP версии 3.9/4.0/5.0.
* КриптоПро TSPCOM версии 1.05.1379 / 1.05.1057 / 2.0.12450.
* КриптоПро OCSPCOM версии 1.05.1178 / 1.05.1053 / 2.0.12261.
* КриптоПро CADESCOM 2.0.13292.

.Сертификаты:
* Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователяfootnote:[Например, корневой сертификат КриптоПро.] должен быть установлен в хранилище "Доверенные корневые центры сертификации" на уровне "Локальный компьютер".
* Сертификат пользователя должен быть установлен в хранилище "Личное" на уровне "Текущий пользователь".

.Обратите внимание:
****
* Для использования функции КриптоПро "Облачный провайдер" требуется "КриптоПро CSP" версии 5.0 или выше. В качестве сервера электронной подписи может выступать КриптоПро DSS.
* Для использования ключей ЭП ГОСТ Р 34.10-2012 требуется "КриптоПро CSP" версии 4.0 или выше.
* Для работы с КриптоПро должна быть выполнена настройка, рассмотренная в xref:admin:prepare-cryptopro.adoc[данном] пункте.
* По вопросам получения компонентов криптопровайдера "КриптоПро" следует обращаться в компанию ООО "КРИПТО-ПРО".
****

[#dv]
== Требования к системе {dv}

include::workerservice:ROOT:partial$excerpts.adoc[tags=feature]

[#license]
== Лицензия

Для работы с модулем _{bo}_ лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Card Builder_ ("Конструктор карточек").

.При отсутствии данной дополнительной опции, работа с карточками и справочниками модуля будет ограничена:
* В _Справочнике видов карточек_ сохранится возможность изменять часть существующих настроек, но создавать, удалять и переименовывать виды при этом нельзя. Также нельзя изменять настройки наследования параметров для вида.
* _Конструктор разметок_ и _Конструктор скриптов_ будут отображаться в списке _Конструкторы и справочники_, но открыть их будет нельзя.
* В _Конструкторе состояний_ будет разрешено настраивать доступность операций, но создавать, удалять и переименовывать состояния или переходы между состояниями при этом нельзя.
* В _Конструкторе справочников_ нельзя будет добавлять новые узлы, но можно будет создавать записи.

[#routing]
Для работы маршрутизации заданий в почту *_Задача Почтового клиента_*, лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Outlook Client_. При отсутствии данной дополнительной опции исполнителям будут рассылаться простые письма с описанием задания без возможности исполнения в почтовом клиенте.
