= Необходимые ресурсы

== Необходимое техническое обеспечение

=== Требования серверной части модуля

Специальные требования к аппаратному обеспечению не предъявляются.

=== Требования клиентской части модуля

Для возможности сканирования в {wincl}е/РМА документов из карточек модуля требуется любой WIA-совместимый сканер с WIA-драйвером.

.Сканеры, сертифицированные для работы в системе {dv}:
* WIA: Epson Workforce PS-6500;
* TWAIN: Epson GT-S55, Epson P-215.

[CAUTION]
====
Рекомендуется проверить совместимость с конкретными сканерами до начала использования продукта. Компания "ДоксВижн" не несет ответственности за некорректную работу сканеров и иного оборудования. Отсутствие совместимости с конкретной моделью сканера, или отличия в поведении сканирования из системы {dv} по сравнению со сканированием в стороннем ПО, не могут являться основанием для рекламации или обращения в техническую поддержку ДоксВижн.
====

== Необходимое программное обеспечение

База данных {dv} должна работать с расширенными метаданными. Работа с базой данных с динамическими метаданными *не поддерживается*.

=== Требования серверной части модуля

.. Серверная часть модуля "{dv} 5. {pl}" версии 5.5.2 сборка 4553 и выше.
.. Серверная часть приложения "{dv} 5. {ud}" версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Серверная часть модуля "{dv} 5. {ad}" версии 5.5.2 сборка 4221 и выше.
.. Серверная часть приложения "{dv} 5. Делопроизводство 4.5" версии 5.5.2 сборка 4203 и выше.
.. Серверная часть модуля "{dv} 5. {wincl}" версии 5.5.2 сборка 4248 и выше.

=== Требования клиентской части модуля

.. Клиентская часть модуля "{dv} 5. {pl}" версии 5.5.2 сборка 4553 и выше.
.. Клиентская часть приложения "{dv} 5. {ud}" версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Клиентская часть модуля "{dv} 5. {ad}" версии 5.5.2 сборка 4221 и выше.
.. Клиентская часть приложения "{dv} 5. Делопроизводство 4.5" версии 5.5.2 сборка 4203 и выше.
.. Клиентская часть модуля "{dv} 5. {wincl}" версии 5.5.2 сборка 4248 и выше.
. *Дополнительное программное обеспечение:*
.. ABBYY FineReader Engine 11.0 (32-разрядная версия) -- для работы функции распознавания в карточках модуля (в т.ч. для потокового ввода документов и распознавания штрих-кодов). Дополнительная информация приведена в пункте xref:admin:prepare-abbyy.adoc[Настройка ABBYY FineReader Engine].
.. Почтовый клиент -- для работы с заданиями, маршрутизируемыми в почту.
+
*Известные проблемы совместимости*. При использовании почтового клиента Gmail в операционной системе iOS, а также MS Outlook в операционной системе Android, при формировании ответного письма часть содержимого темы письма обрезается, что делает невозможным обработку данных писем на сервере {dv}. Используйте альтернативные почтовые клиенты в данном случае.

[#crypto-pro]
=== Программное обеспечение, необходимое для работы с сертификатами КриптоПро

Следующее программное обеспечение должно быть установлено на компьютере для использования сертификатов УЦ КриптоПро для формирования/проверки усиленной квалифицированной или усовершенствованной ЭП.

==== Требования к клиентским рабочим местам

. Компоненты криптопровайдера "КриптоПро":
* КриптоПро CSP версии 3.9/4.0/5.0;
* КриптоПро TSPCOM версии 1.05.1379 / 1.05.1057 / 2.0.12450;
* КриптоПро OCSPCOM версии 1.05.1178 / 1.05.1053 / 2.0.12261;
* КриптоПро CADESCOM 2.0.13292.
. Сертификаты:
* Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователяfootnote:[Например, корневой сертификат КриптоПро.] -- должен быть установлен в хранилище "Доверенные корневые центры сертификации" на уровне "Локальный компьютер";
* сертификат пользователя -- должен быть установлен в хранилище "Личное" на уровне "Текущий пользователь".

.Обратите внимание
****
* Для использования функции КриптоПро "Облачный провайдер" требуется "КриптоПро CSP" версии 5.0 или выше. В качестве сервера электронной подписи может выступать КриптоПро DSS.
* Для использования ключей ЭП ГОСТ Р 34.10-2012 требуется "КриптоПро CSP" версии 4.0 или выше.
* Для работы с КриптоПро должна быть выполнена настройка, рассмотренная в пункте <<crypto-pro,Настройка {dv} для работы с криптопровайдером КриптоПро>>.
* По вопросам получения компонентов криптопровайдера "КриптоПро" следует обращаться в компанию ООО "КРИПТО-ПРО".
****

== Лицензия

Для работы с модулем "{dv} 5. {bo}" лицензия на систему {dv} должна содержать дополнительную опцию "{dv} Card Builder" ("Конструктор карточек"). При отсутствии данной дополнительной опции возможности работы с карточками и справочниками модуля будут ограничены:

* В "Справочнике видов карточек" сохранится возможность изменять часть существующих настроек, но создавать/удалять/переименовывать виды при этом нельзя. Также нельзя изменять настройки наследования параметров для вида.
* "Конструктор разметок" и "Конструктор скриптов" будут отображаться в списке *Конструкторы и справочники*, но открыть их будет нельзя.
* В "Конструкторе состояний" будет разрешено настраивать доступность операций, но создавать/изменять/удалять состояния или переходы между состояниями при этом нельзя.
* В "Конструкторе справочников" нельзя будет добавлять новые узлы (создавать записи можно).

[#routing]
Для работы маршрутизации заданий в почту "Задача Почтового клиента", лицензия на систему {dv} должна содержать дополнительную опцию "{dv} Outlook Client". При отсутствии данной дополнительной опции исполнителям будут рассылаться простые письма с описанием задания без возможности исполнения в почтовом клиенте.
