= Уровень подготовки пользователя

Для эксплуатации модуля _{bo}_ определены две пользовательские роли: администратор {dv} и конечный пользователь. Настройку _решения_ на базе системы {dv} с использованием модуля выполняет инженер {dv}.

Администратор {dv} устанавливает модуль (серверную и клиентскую части), выполняет первоначальную настройку, выявляет неполадки в работе бизнес-процессов модуля в процессе эксплуатации.

Инженер {dv} настраивает работу с карточками модуля с помощью предоставляемых _конструкторов_ и _справочников_ {dv}, разрабатывает скрипты карточек, настраивает бизнес-процессы.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой, согласованием и т.п.

Администратор или конечный пользователь {dv} заполняют и актуализируют справочники {dv}.

Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере, в программе "{wincl}" (модуль "{dv} 5. {wincl}").

Администратор {dv} должен обладать навыками настройки модуля "{dv} 5. {pl}", формирования сертификатов ЭЦП в ОС Windows, использования криптопровайдера "КриптоПро"; а также ознакомиться с документом _модуль "{dv} 5. {bo}". Руководство администратора_.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}, иметь опыт разработки на языке C# или Visual Basic .NET; должен ознакомиться с данным руководством пользователя, с документами _модуль "{dv} 5. {bo}". Руководство администратора_# и _{dv} 5.5. Руководство программиста_.

Конечные пользователи должны ознакомиться с данным руководством пользователя.
