= Уровень подготовки пользователя

Для эксплуатации модуля _{bo}_ определены три пользовательские роли: администратор {dv}, инженер и конечный пользователь. Настройку _решения_ на базе системы {dv} с использованием модуля выполняет инженер {dv}.

.Администратор {dv}:
* Устанавливает модуль (серверную и клиентскую части).
* Выполняет первоначальную настройку.
* Выявляет неполадки в работе бизнес-процессов модуля во время эксплуатации.
* Администратор или конечный пользователь {dv} заполняют и актуализируют справочники {dv}.

.Администратор {dv} должен:
* Обладать навыками настройки модуля {pl}, формирования сертификатов ЭП в ОС Windows, использования криптопровайдера "КриптоПро",
* Ознакомиться с разделом _Администрирование модуля {bo}_.

.Инженер {dv}:
* Настраивает работу с карточками модуля с помощью предоставляемых _конструкторов_ и _справочников_ {dv},
* Разрабатывает скрипты карточек.
* Настраивает бизнес-процессы.

.Инженер {dv} должен:
* Быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}.
* Иметь опыт разработки на языке C# или Visual Basic .NET.
* Ознакомиться с разделом _Работа с модулем {bo}_, с разделом _Администрирование модуля {bo}_ и документом xref:programmer::index.adoc["Руководство разработчика"].

.Конечный пользователь:
* Выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой, согласованием и прочие.
* Должен ознакомиться с разделом _Работа с модулем {bo}_.

.Все пользователи модуля должны:
* Обладать базовыми навыками работы на персональном компьютере, в программе {wincl}.
