= Приложение B. Обработка ошибок бизнес-процессами модуля

При работе бизнес-процесса _Маршрутизация заданий в почту_ могут возникать следующие ошибки:

[%noheader,cols=","]
|===
|Невозможность отправки заданий в связи с неработоспособностью почтового сервера, возникшей во время работы бизнес-процесса.
|В этом случае БП выполняет 10 повторных попыток отправки почтовых сообщений с заданиями. Интервал между попытками -- 10 секунд. Если отправить письма с заданиями не удалось, БП останавливается с ошибкой.

При повторном старте бизнес-процесса сообщение по уже обработанным заданиям не отсылается.

|Невозможность отправки отдельного задания. Ошибка может возникать, например, по причине превышения размера почтового сообщения.
|В этом случае в журнал бизнес-процесса записывается сообщение о причине невозможности отправки, при этом бизнес-процесс продолжает обрабатывать следующие задания. На xref:routing-general.adoc#admin-mail[адрес администратора {dv}] будет отправлено сообщение об ошибке.

|Получения сообщения о недоставке/ошибке почтового сообщения. Ошибка может возникать, например, если адрес получателя не существует.
|На адрес администратора {dv} будет отправлено сообщение об ошибке.
|===

== Обработка ошибок в БП "ПК Мониторинг почты"

Если функция "Обработка сообщений" БП _ПК Мониторинг почты_ не смогла получить или удалить почтовое сообщение о совершении действий с заданием с почтового сервера, будет предпринято несколько повторных попыток выполнить данные действия. Количество попыток обработки определяется значением переменной _AttempsToTry_ БП "ПК Мониторинг почты" -- по умолчанию `10`.

Если коллекция писем не была обработана за указанное в _AttempsToTry_ количество попыток, БП будет остановлен по ошибке и на xref:routing-general.adoc#admin-mail[адрес администратора {dv}] будет отправлено сообщение об ошибке.

После повторного старта БП _ПК Мониторинг почты_ обработка коллекции писем будет начата с последнего непрочитанного сообщения.
