= Приложение A. Описание процесса маршрутизации заданий в почту

. Бизнес-процесс мониторинга отыскивает необработанные ранее карточки _Задание_ (всех видов), соответствующие следующим параметрами:
+
* Состояние `Начато`, `Делегировано`, `Возвращено с делегирования`.
* Установлен способ маршрутизации *_Задача Почтового клиента_* (для исполнителя, для вида задания или указан в настройках задания).
* В текущий момент времени задание не обрабатывается никаким бизнес-процессом.
+
. Для каждого отобранного на предыдущем этапе задания запускается подпроцесс, который создаёт форму письма, формирует тело письма и набор доступных операций.
+
--
.При этом набор действий, доступных к выполнению из письма, следующий:
* Завершение задания. Завершить задание из письма можно, если:
.. При завершении задания требуется заполнить не более одного поля.
.. Параметры завершения задания ограничены следующим списком: ввод отчёта, прикрепление файла отчёта, ввод комментария.
--
+
--
Если параметры завершения задания не удовлетворяют перечисленным условиям, в письме размещается уведомление о необходимости открыть карточку задания {dv} для завершения задания.
--
+
* Взятие в работу.
* Отклонение задания.
+
[NOTE]
====
Пользователю может быть разрешено делегировать задание. Для выполнения этой операции потребуется открыть карточку задания {dv}.
====
+
* В тело письма помещается ссылка на карточку {dv}, по которой она может быть открыта, если на компьютере установлены клиентские компоненты {dv}.
* В письмо как вложения помещаются файлы документов, приложенных к карточке _Задание_ (если выполнены соответствующие настройки в _Справочнике видов карточек_).
* В тело письма могут быть помещены атрибуты карточки документа, по которому создано задание.
* В тело письма по умолчанию помещаются атрибуты карточки задания: автор, исполнители, дата завершения, контролер, дата контроля.
+
[NOTE]
====
Идентификатор сформированного письма содержит адрес сервера {dv}, на который оно должно быть отправлено.
====
+
. После формирования письма запускается подпроцесс, отправляющий это письмо исполнителю задания. Отправка производится через почтовый клиент, с которым работает сервер {dv}. Параметры работы сервера {dv} с почтой указаны в Консоли настройки {dv}.
. В процессе исполнения задания пользователь переходит по ссылке -- действию в области _Действия с заданием_ полученного письма. В результате формируется ответное письмо, которое пользователь отправляет на сервер.
. На сервере {dv} бизнес-процесс мониторинга почты отслеживает непрочитанные письма о совершении некоторого действия с заданием из почтового сообщения, обрабатывает каждое из полученных сообщений, затем передаёт управление подпроцессу, ответственному за обработку данного действия или создаёт сообщение о том, что данное действие невозможно выполнить.
+
.Получивший управление подпроцесс вносит в карточку задания {dv} соответствующие изменения:
* Состояние.
* Дата начала.
* Дата завершения.
* Отчеты (текстовый отчёт и файлы отчёта).
* Комментарии -- при завершении задания, отклонении задания, отказе в согласовании.
+
. После получения сервером ответного письма формируется и отправляется исполнителю письмо-уведомление о том, что операция выполнена и изменения внесены в карточку задания {dv} или о том, что в ходе выполнения действия произошла ошибка.
