= Создание карточки "Группа заданий"

Карточка _Группа заданий_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта.

В базовый комплект поставки системы _{dv} 5_ (при отсутствии модуля _{ud}_) входит базовый тип карточки _Группа заданий_. Данный тип не подлежит изменению, но может использоваться для создания карточек.

include::partial$excerpts.adoc[tags=user-kinds]

.Создание карточки "Группа заданий" может быть выполнено следующими способами:
include::partial$excerpts.adoc[tags=create]

.Также для карточек "Группа заданий" существуют дополнительные способы создания:
* xref:additional/additional-links.adoc[По ссылке из другой карточки].
* xref:additional/additional-performance-tree.adoc[Из дерева исполнения связанной карточки].

Созданная карточка изначально находится в состоянии `Инициализация` (в соответствии с "автоматом состояний"). При этом часть полей карточки будут автоматически заполнены на основе следующих сведений:

* В качестве _Автора_ задания указывается текущий сотрудник.
* Настройки карточки наследуются из вида или шаблона (если карточка создается из него).

.Созданную карточку необходимо настроить:
* xref:task-group/main-tab.adoc#author[Выбрать] автора задания.
* xref:task-group/main-tab.adoc#name[Ввести] название и содержание задания.
* xref:task-group/main-tab.adoc#performer[Выбрать] исполнителя задания.
* xref:task-group/main-tab.adoc#duration[Указать] сроки исполнения задания.
* xref:task-group/main-tab.adoc#control[Настроить] контроль исполнения задания.
