= Настройка дерева исполнения связанных карточек

С помощью _Конструктора разметок_ на разметку карточки документа или задания может быть добавлен xref:desdirs:layouts/std-ctrl/performance-tree.adoc[элемент управления] `_Дерево исполнения_`.

Из контекстного меню этого элемента можно создавать или удалять задания. При создании задания, связанного с документом, имеется возможность выбрать вид задания или создать задание корневого вида. Также можно настроить или уточнить поведение задания: в случае необходимости указать получателя задания, срок исполнения и прочее. Когда требуемые настройки выполнены, можно отслеживать исполнение задания и управлять его ходом непосредственно из карточки документа.

NOTE: Доступ к этой функции зависит от настроек в конструкторах _состояний_ и _ролей_. Отслеживать исполнение и управлять его ходом можно с помощью дерева исполнения задания.

При создании задания из карточки документа, этот документ для задания считается основным и отображается согласно настройкам карточки задания.
