= Типы маршрутизации

По умолчанию::
Настройки маршрутизации берутся из карточки сотрудника (исполнителя задания) в _Справочнике сотрудников_.

Онлайн задание::
Задание приходит в настроенную виртуальную папку _{dv}_.

Задача Почтового клиента::
На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида Задание в системе {dv} (в {wincl}е или в {wc}е). Также пользователю предоставляется возможность выполнять задания непосредственно в почтовом клиенте с помощью ответных писем.

Ссылка на задание::
На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида _Задание_ в системе {dv} (в {wincl}е или в {wc}е).

Письмо с описанием задания::
На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида _Задание_ в системе {dv} и текстом, который указан в XSLT-преобразовании.

Офлайн задание::
Пользователь получает по электронной почте специальное сообщение (форму Outlook), внешне похожее на карточку задания, однако обмен данными происходит по электронной почте. В личную папку пользователя помещается ярлык на онлайн-задание.
+
Данный тип маршрутизации совместим только с карточками {dv} 4.5. Задания {dv} 5 не работают с данным типом маршрутизации, в _Справочнике видов карточек_ данный тип не отображается.

Зашифрованное офлайн задание::
Данный способ маршрутизации и внешний вид карточки задания полностью аналогичны способу маршрутизации онлайн-задание, однако при отправке пользователю все данные задания автоматически шифруются и доступ к нему имеет только тот пользователь, которому оно предназначено.
+
Для отправки зашифрованных офлайн-заданий необходимо настроить параметры шифрования в справочнике _Системные настройки_, а также выбрать сертификат в _Консоли настройки_ (выполняется администратором системы).
+
Получателю зашифрованного офлайн-задания отправляются, помимо самого задания, сессионный ключ шифрования и настройки крипто-провайдера и алгоритма шифрования. Для того, чтобы получатель смог открыть свое задание, администратор должен предоставить ему личный сертификат.
+
Данный тип маршрутизации совместим только с карточками {dv} 4.5. Задания {dv} 5 не работают с данным типом маршрутизации, в _Справочнике видов карточек_ данный тип не отображается.

Не маршрутизировать::
При отправке задания в системной папке _Карточки_ (в ветке Задание бизнес-процесса библиотеки Делопроизводство) появляется карточка задания. Вся работа пользователя с заданием осуществляется в рамках работы с приложением {wincl}.
