//tag::gen[]
==== Вкладка "Общие"

Состав и назначение параметров на данной вкладке общие для всех типов карточек. Настройки вкладки описаны <<general-tab,выше>>.
//end::gen[]

//tag::before[]
[NOTE]
====
До версии _{dv} 5.5_ для наложения запрета на виды карточек применялась настройка `*Вид недоступен для выбора*`, которая влияла одновременно и на выбор, и на использование вида для создания карточек.

В данной версии, чтобы не потерять ранее выполненные изменения, следует использовать две разные настройки, влияющие на xref:card-kinds/general-hide-kind.adoc[выбор] вида и на xref:card-kinds/general-forbid-card.adoc[создание] объектов выбранного вида.
====
//end::before[]

//tag::ban[]
* В _Дереве видов_ справочника.
//tag::hide[]
* В _Справочнике видов карточек_ для заданий на вкладках xref:card-kinds/Task_ChildTask_card_type.adoc["Подчиненное задание"] и xref:card-kinds/Task_ChildGroupTask_card_type.adoc["Подчиненная Группа заданий"] справочника, в области _Выбор вида из ограниченного списка_.
* В _Справочнике видов карточек_ для группы заданий на вкладке _Группа заданий_ в области xref:card-kinds/GroupTask_card_type.adoc["Типы карточек для документов"].
* В карточке базового типа _Задание_ на вкладке _Настройки_ в поле _Вид подчиненного задания_.
* В настройках элементов управления xref:layouts/std-ctrl/references.adoc["Ссылки"] и xref:layouts/std-ctrl/links-tree.adoc["Дерево связей"] (Разрешенные типы/виды карточек).
* В диалоговом окне выбора вида при вызове справочника видов из полей в справочниках, карточках, из формы поисковых запросов, а также функциях приложения _Управление процессами_.
* В быстром поиске из полей карточек, справочников, поисковой формы с использованием выбора вида.
//end::hide[]
* В окне выбора вида при вызове _Справочника видов карточек_ из каких-либо полей объектов системы (в том числе -- конструкторов).
//end::ban[]