= Недоступность вида для выбора

В _Справочнике видов карточек_ могут храниться виды, которые по различным причинам не должны быть доступны для выбора из объектов системы.

Недоступность вида для выбора не влияет на возможность создания карточек данного вида и их отображение в контекстных меню создания карточек, выбора карточек с использованием режимов создания, скриптов, а также при выборе в конструкторах (ролей, состояний, разметок).

[NOTE]
====
До версии _{dv} 5.5_ для наложения запрета на виды карточек применялась настройка *Вид недоступен для выбора*, которая влияла одновременно и на выбор, и на использование вида для создания карточек. В данной версии, чтобы не потерять ранее выполненные изменения, следует использовать две разные настройки, влияющие на xref:card-kinds/Common_Hide_subtype.adoc[выбор] вида и на xref:card-kinds/Common_Forbid_card_creation.adoc[создание] объектов выбранного вида.
====

.Чтобы вид был недоступен для выбора:
. Выберите в _Дереве видов карточек_ вид, который не должен отображаться у пользователей.
. Перейдите на вкладку xref:card-kinds/directory.adoc#general-tab[*Общие*].
. Установите флаг *Сделать вид недоступным для выбора*.
+
Виды будут отображаться в полях системы серым цветом шрифта, однако кнопки подтверждения выбора будут недоступны.
+
.Выбор вида и его дочерних видов будет запрещен из следующих объектов системы:
* в _Справочнике видов карточек_ для заданий на вкладках xref:card-kinds/Task_ChildTask_card_type.adoc[*Подчиненное задание*] и xref:card-kinds/Task_ChildGroupTask_card_type.adoc[*Подчиненная Группа заданий*] справочника, в области *Выбор вида из ограниченного списка*;
* в _Справочнике видов карточек_ для группы заданий на вкладке *Группа заданий* в области xref:card-kinds/GroupTask_card_type.adoc[*Типы карточек для документов*];
* в карточке базового типа _Задание_ на вкладке *Настройки* в поле *Вид подчиненного задания*;
* в настройках элементов управления *Ссылки* и *Дерево связей* (Разрешенные типы/виды карточек);
* в диалоговом окне выбора вида при вызове справочника видов из полей в справочниках, карточках, из формы поисковых запросов, а также функциях приложения _Управление процессами_;
* быстрым поиском из полей карточек, справочников, поисковой формы с использованием выбора вида.
