= Тип "Группа заданий"

Тип _Группа заданий_ входит в библиотеку *{bo}* системы _{dv} 5_.

Карточки данного типа предназначены для создания детализированных распоряжений по документу, разбитых на отдельные подзадачи. Каждая подзадача предназначена для определенного исполнителя или группы исполнителей, снабжена описанием работ, сроками их исполнения и другими параметрами, а также предусматривает необходимый контроль за ходом реализации группы заданий.

После создания карточки и отправки группы заданий исполнителям, система автоматически создает бизнес-процесс в соответствии с указанными параметрами, и далее рассылка заданий исполнителям и другим участникам производится автоматически.

По умолчанию, при создании _Группы заданий_ будет открыта карточка справочника базового типа. При необходимости на базе типа могут быть созданы виды карточек. Дочерние виды будут доступны для выбора в контекстном меню при создании карточки.

Для пользователей, назначенных _Исполнителями_ и _Ответственными исполнителями_, которые получат карточку задания на исполнение, по умолчанию будет использоваться карточка базового типа. При соответствующей xref:card-kinds/GroupTask_select_subtype.adoc[настройке], для данных пользователей будет открываться карточка заданного вида.
