// tag::mail-mon[]
При запуске БП Мониторинг почты в журнале может появляться сообщение: `Cannot map account name: domain\username`. Для устранения ошибки потребуется установить дополнительный компонент `gss-ntlmssp` командой:

[tabs]
====
Astra Linux::
+
[source,bash]
----
sudo apt-get install gss-ntlmssp
----

РЕД ОС::
+
[source,bash]
----
sudo dnf install gss-ntlmssp
----
====

// end::mail-mon[]

//tag::provider[]
В поле _{provider}_ выберите DLL файл, содержащий реализацию функции провайдера службы штампов времени.

Стандартная реализация провайдера службы для криптопровайдера КриптоПро содержится в файле `Каталог-установки-модуля/{dv}.BackOffice.ObjectModel.CryptoPro.dll`.

NOTE: Если требуется взаимодействовать со службой другого криптопровайдера, необходимо самостоятельно разработать компонент, содержащий реализацию провайдера к этой службе. Обратитесь за дополнительной информацией к описанию интерфейса `DocsVision.BackOffice.ObjectModel.Services.{api}`, приведенному в
//end::provider[]