[[ariaid-title1]]
== Перемещение и копирование категории

С помощью метода drag'n'drop (перетаскивания мышью) можно копировать или перемещать категории внутри дерева.

. [.ph .cmd]#Чтобы переместить категорию, установите на ней курсор и перетащите категорию в новое место. #
+
При перетаскивании категория переместится на новое место.
. [.ph .cmd]#Чтобы скопировать категорию, выполните любое из действий: #
* выделите нужную категорию, левой клавишей мыши вызовите контекстное меню, затем выберите команду [.keyword]*Копировать*. Установите курсор в место сохранения копии, вызовите контекстное меню и выберите команду [.keyword]*Вставить*.
* При перетаскивании методом drag'n'drop удерживайте нажатой клавишу _Ctrl_.
+
[NOTE]
====
[.note__title]#Прим.:# Внутри корневой папки скопировать категорию методом drag'n'drop нельзя. Операция доступна только через контекстное меню.
====
+
Если копирование происходит в узел, который уже содержит категорию с таким же именем, то к названию скопированной категории будет добавлен порядковый номер (например, можно последовательно создать копии категории _Сервис_, которые будут называться _Сервис1_, _Сервис2_ и т.д.).

*На уровень выше:* xref:../pages/cat_Work.adoc[Работа со справочником]
