[[ariaid-title1]]
== Запрет на создание карточек определенных видов

В [.dfn .term]_Справочнике видов карточек_ могут храниться виды, которые по различным причинам не должны использоваться для создания карточек, но при этом xref:cSub_Subtype_delete.adoc[удаление] которых из справочника не желательно. Для таких видов можно запретить создание карточек:

* из контекстного меню [.dfn .term]_Docsvision Рабочего места администратора_ и Windows-клиент;
* из меню кнопки [.keyword]*Создать карточку* ленты [.dfn .term]_Docsvision Рабочего места администратора_ и Windows-клиент;
* из элемента управления xref:lay_Elements_References.html[[.keyword]*Ссылки*] (если данный элемент используется в разметке карточки), по команде [.keyword]*Создать карточку*. При этом выбор существующих карточек не будет запрещен, если он выбран в настройках элемента управления.

Если запрет установлен, создание карточек данного вида в перечисленных выше объектах будет определяться по следующим правилам:

* вид не будет отображаться, если отсутствуют дочерние виды или в присутствующих дочерних видах нет ни одного разрешенного;
* вид будет отображаться, если присутствуют дочерние виды, однако создание карточек данного вида будет запрещено. Если на своём уровне запрещенный вид единственный в меню и имеет дочерние виды, он должен быть скрыт, а дочерние - отображены.

Опция не влияет на возможность создания карточек с использованием режимов создания, скриптов, бизнес-процессов. Виды, для которых установлена опция, доступны для выбора в любых местах, где осуществляется выбор вида.

[[task_jnf_d4h_ns__note_last_version_flag]]
[NOTE]
====
[.note__title]#Прим.:# До версии [.dfn .term]_Docsvision 5.5_ для наложения запрета на виды карточек применялась настройка [.keyword]*Вид недоступен для выбора*, которая влияла одновременно и на выбор, и на использование вида для создания карточек. В данной версии, чтобы не потерять ранее выполненные изменения, следует использовать две разные настройки, влияющие на link:cSub_Common_Hide_subtype.adoc[выбор] вида и на xref:cSub_Common_Forbid_card_creation.adoc[создание] объектов выбранного вида.
====

Чтобы запретить создание карточек для вида, выполните следующие действия:

. [.ph .cmd]#Выберите в [.dfn .term]_Дереве видов карточек_ вид, для которого необходимо настроить запрет на создание карточек. #
. [.ph .cmd]#Перейдите на вкладку xref:cSub_Interface_Common.html[[.keyword]*Общие*].#
. [.ph .cmd]#Установите флаг [.ph .uicontrol]*Запретить создание карточек данного вида*.#
+
Виды, для которых настроен запрет, не будут отображаться в подменю выбора вида для создания карточек.

Виды, для которых настроен запрет на создание карточек, будут отображаться курсивом:

* в [.dfn .term]_Дереве видов_ справочника;
* в [.dfn .term]_Справочнике видов карточек_ для заданий на вкладках link:cSub_Task_ChildTask_card_type.html[[.keyword]*Подчиненное задание*] и link:cSub_Task_ChildGroupTask_card_type.html[[.keyword]*Подчиненная Группа заданий*] справочника, в области [.keyword]*Выбор вида из ограниченного списка*;
* в [.dfn .term]_Справочнике видов карточек_ для группы заданий на вкладке [.keyword]*Группа заданий* в области link:cSub_GroupTask_card_type.html[[.keyword]*Типы карточек для документов*];
* в карточке базового типа [.dfn .term]_Задание_ на вкладке [.keyword]*Настройки* в поле [.keyword]*Вид подчиненного задания*;
* в настройках элементов управления link:lay_Elements_References.html[[.keyword]*Ссылки*] и link:lay_Elements_LinksTree.html[[.keyword]*Дерево связей*] (Разрешенные типы/виды карточек);
* в окне выбора вида при вызове [.dfn .term]_Справочника видов карточек_ из каких-либо полей объектов системы (в том числе - конструкторов).

*На уровень выше:* link:../pages/cSub_Common.adoc[Общие настройки]
