[[ariaid-title1]]
== Недоступность вида для выбора

В [.dfn .term]_Справочнике видов карточек_ могут храниться виды, которые по различным причинам не должны быть доступны для выбора из объектов системы.

Недоступность вида для выбора не влияет на возможность создания карточек данного вида и их отображение в контекстных меню создания карточек, выбора карточек с использованием режимов создания, скриптов, а также при выборе в конструкторах (ролей, состояний, разметок).

[NOTE]
====
[.note__title]#Прим.:# До версии [.dfn .term]_Docsvision 5.5_ для наложения запрета на виды карточек применялась настройка [.keyword]*Вид недоступен для выбора*, которая влияла одновременно и на выбор, и на использование вида для создания карточек. В данной версии, чтобы не потерять ранее выполненные изменения, следует использовать две разные настройки, влияющие на xref:cSub_Common_Hide_subtype.adoc[выбор] вида и на xref:cSub_Common_Forbid_card_creation.adoc[создание] объектов выбранного вида.
====

Чтобы вид был недоступен для выбора, выполните следующие действия:

. [.ph .cmd]#Выберите в [.dfn .term]_Дереве видов карточек_ вид, который не должен отображаться у пользователей. #
. [.ph .cmd]#Перейдите на вкладку xref:cSub_Interface_Common.html[[.keyword]*Общие*].#
. [.ph .cmd]#Установите флаг [.ph .uicontrol]*Сделать вид недоступным для выбора*.#
+
Виды будут отображаться в полях системы серым цветом шрифта, однако кнопки подтверждения выбора будут недоступны.

Выбор вида и его дочерних видов будет запрещен из следующих объектов системы:

* в [.dfn .term]_Справочнике видов карточек_ для заданий на вкладках link:cSub_Task_ChildTask_card_type.html[[.keyword]*Подчиненное задание*] и link:cSub_Task_ChildGroupTask_card_type.html[[.keyword]*Подчиненная Группа заданий*] справочника, в области [.keyword]*Выбор вида из ограниченного списка*;
* в [.dfn .term]_Справочнике видов карточек_ для группы заданий на вкладке [.keyword]*Группа заданий* в области link:cSub_GroupTask_card_type.html[[.keyword]*Типы карточек для документов*];
* в карточке базового типа [.dfn .term]_Задание_ на вкладке [.keyword]*Настройки* в поле [.keyword]*Вид подчиненного задания*;
* в настройках элементов управления [.keyword]*Ссылки* и [.keyword]*Дерево связей* (Разрешенные типы/виды карточек);
* в диалоговом окне выбора вида при вызове справочника видов из полей в справочниках, карточках, из формы поисковых запросов, а также функциях приложения [.dfn .term]_Управление процессами_;
* быстрым поиском из полей карточек, справочников, поисковой формы с использованием выбора вида.

*На уровень выше:* link:../pages/cSub_Common.adoc[Общие настройки]
