= Тип "Согласование"

Тип _Согласование_ входит в библиотеку *Базовые объекты* системы _Docsvision 5_.

Карточки данного типа предназначены для выполнения согласования по документу при наличии установленного приложения _{ud}_. Карточка может использоваться:

* Для настройки шаблона согласования. Для работы с шаблоном необходимо выполнить команду создания карточки из области представления Windows-клиент. Разметка открывшейся карточки будет содержать поля для настройки данного шаблона (см. руководство администратора приложения "Docsvision 5. {ud}", раздел *Настройка шаблона согласования*);
* Для выполнения сценариев согласования. Для запуска сценария необходимо выполнить команду создания согласования из карточки вида _Документ УД_ (см. руководство пользователя приложения "Docsvision 5. {ud}", раздел *Создание и запуск согласования по документу*).

При отсутствии установленного приложения _{ud}_ настройка разметок для данной карточки может быть выполнена пользователями самостоятельно. Дочерние виды будут доступны для выбора в контекстном меню при создании карточки.
