[[ariaid-title1]]
== Тип 'Согласование'

Тип [.keyword .parmname]_Согласование_ входит в библиотеку [.keyword]*Базовые объекты* системы [.dfn .term]_Docsvision 5_.

Карточки данного типа предназначены для выполнения согласования по документу при наличии установленного приложения [.dfn .term]_Управление документами_. Карточка может использоваться:

* Для настройки шаблона согласования. Для работы с шаблоном необходимо выполнить команду создания карточки из области представления Windows-клиент. Разметка открывшейся карточки будет содержать поля для настройки данного шаблона (см. руководство администратора приложения «Docsvision 5. Управление документами», раздел [.keyword]*Настройка шаблона согласования*);
* Для выполнения сценариев согласования. Для  запуска сценария необходимо выполнить команду создания согласования из карточки вида [.dfn .term]_Документ УД_ (см. руководство пользователя приложения «Docsvision 5. Управление документами», раздел [.keyword]*Создание и запуск согласования по документу*).

При отсутствии установленного приложения [.dfn .term]_Управление документами_ настройка разметок для данной карточки может быть выполнена пользователями самостоятельно. Дочерние виды будут доступны для выбора в контекстном меню при создании карточки.

*На уровень выше:* xref:../pages/cSub_Work_SelectCardType.adoc[Выбор типа карточки]
