= Запрет на создание карточек определенных видов

В _Справочнике видов карточек_ могут храниться виды, которые по различным причинам не должны использоваться для создания карточек, но при этом xref:cSub_Subtype_delete.adoc[удаление] которых из справочника не желательно. Для таких видов можно запретить создание карточек:

* из контекстного меню _{dv} Рабочего места администратора_ и {wincl};
* из меню кнопки *Создать карточку* ленты _{dv} Рабочего места администратора_ и {wincl};
* из элемента управления xref:lay_Elements_References.adoc[*Ссылки*] (если данный элемент используется в разметке карточки), по команде *Создать карточку*. При этом выбор существующих карточек не будет запрещен, если он выбран в настройках элемента управления.

Если запрет установлен, создание карточек данного вида в перечисленных выше объектах будет определяться по следующим правилам:

* вид не будет отображаться, если отсутствуют дочерние виды или в присутствующих дочерних видах нет ни одного разрешенного;
* вид будет отображаться, если присутствуют дочерние виды, однако создание карточек данного вида будет запрещено. Если на своём уровне запрещенный вид единственный в меню и имеет дочерние виды, он должен быть скрыт, а дочерние -- отображены.

Опция не влияет на возможность создания карточек с использованием режимов создания, скриптов, бизнес-процессов. Виды, для которых установлена опция, доступны для выбора в любых местах, где осуществляется выбор вида.

[NOTE]
====
До версии _{dv} 5.5_ для наложения запрета на виды карточек применялась настройка *Вид недоступен для выбора*, которая влияла одновременно и на выбор, и на использование вида для создания карточек. В данной версии, чтобы не потерять ранее выполненные изменения, следует использовать две разные настройки, влияющие на xref:cSub_Common_Hide_subtype.adoc[выбор] вида и на xref:cSub_Common_Forbid_card_creation.adoc[создание] объектов выбранного вида.
====

.Чтобы запретить создание карточек для вида:
. Выберите в _Дереве видов карточек_ вид, для которого необходимо настроить запрет на создание карточек.
. Перейдите на вкладку xref:cSub_Interface_Common.adoc[*Общие*].
. Установите флаг *Запретить создание карточек данного вида*.
+
Виды, для которых настроен запрет, не будут отображаться в подменю выбора вида для создания карточек.
+
Виды, для которых настроен запрет на создание карточек, будут отображаться курсивом:
+
* в _Дереве видов_ справочника;
* в _Справочнике видов карточек_ для заданий на вкладках xref:cSub_Task_ChildTask_card_type.adoc[*Подчиненное задание*] и xref:cSub_Task_ChildGroupTask_card_type.adoc[*Подчиненная Группа заданий*] справочника, в области *Выбор вида из ограниченного списка*;
* в _Справочнике видов карточек_ для группы заданий на вкладке *Группа заданий* в области xref:cSub_GroupTask_card_type.adoc[*Типы карточек для документов*];
* в карточке базового типа _Задание_ на вкладке *Настройки* в поле *Вид подчиненного задания*;
* в настройках элементов управления xref:lay_Elements_References.adoc[*Ссылки*] и xref:lay_Elements_LinksTree.adoc[*Дерево связей*] (Разрешенные типы/виды карточек);
* в окне выбора вида при вызове _Справочника видов карточек_ из каких-либо полей объектов системы (в том числе -- конструкторов).
