= Тип "Документ"

Тип _Документ_ входит в библиотеку *Базовые объекты* системы _Docsvision 5_.

Карточки данного типа предназначены для работы с файлами: хранения файлов в различных форматах, предварительный просмотр, учет версий, экспорта в различные форматы, наложение электронно-цифровых подписей в формате p7s.

Дополнительно для файлов документов в формате MS Office 2016 x86 и младше поддерживается синхронизация полей карточки и свойств вложенного файла.

При наличии установленного приложения Microsoft Outlook, поддерживается как перемещение писем и вложений в карточку из окна приложения, так и перемещение объектов из карточки в окно Microsoft Outlook, с последующим созданием письма с соответствующим вложением.

Также в карточках доступна печать штрих-кода и возможность создания связанных карточек.

По умолчанию, при создании карточки _Документ_ будет открыта карточка справочника базового типа. При необходимости, на базе типа могут быть созданы виды карточек. Дочерние виды будут доступны для выбора в контекстном меню при создании карточки.
