= Настройка подписания

Для карточки вида _Документ_ имеется возможность настройки подписания как полей карточки, так и операций редактирования, выполняемых с карточкой. Наложение электронно-цифровой подписи возможно как для _Основных_ или _Дополнительных_ файлов, вложенных в карточку.

Вид подписи, которая формируется при подписании карточек и файлов, определяется настройками, выполненными администратором Docsvision в справочнике "Системные настройки". Подпись может быть следующих видов:

* _Простая подпись_ – это электронная подпись, которая посредством использования кодов, паролей или иных средств, подтверждает факт формирования электронной подписи  определенным лицом. Данная подпись применяется для подтверждения того, что пользователь под учетной записью Windows выполнил какую-либо операцию. В дополнение к описанным выше требованиям, в системе _Docsvision_ при наложении _простых_ подписей используется механизм хэш-функций, применяемых к объектам, включаемым в подпись. Механизм служит для проверки неизменности объекта на момент подписи. Примером может служить подпись, добавляемая в электронное письмо;
* _Усиленная подпись_ – электронная подпись, при наложении которой выполняется проверка наличия у пользователя сертификата. К данному виду относятся:
+
** _Усиленная неквалифицированная электронная подпись_ – подпись, созданная с помощью криптографических средств и имеющая сертификат от не аккредитованного удостоверяющего центра;
** _Усиленная квалифицированная электронная подпись_ – подпись, созданная с помощью подтвержденных ФСБ криптографических средств и имеющая сертификат от аккредитованного удостоверяющего центра, выступающего гарантом подлинности подписи.
