= Предупреждения об изменении подписанного файла и атрибута

Для пользовательских видов карточек можно настроить вывод подсказок при изменении подписанного основного файла/атрибута документа (для файла – при сохранении файла, для атрибутов – при сохранении карточки).

.Чтобы настроить предупреждения об изменении подписанного файла и атрибута, выполните следующие действия:
. Перейдите на вкладку *Подпись*.
. Установите флаг *Предупреждение об изменении подписанного файла или атрибута*.
+
По умолчанию флаг установлен.
+
* При изменении файла будет появляться сообщение: `Данный                                 документ подписан цифровой подписью, при изменении файла подпись                                 будет недействительна. Сохранить изменения файла?`;
* При сохранении карточки будет появляться сообщение: `Атрибут подписан цифровой подписью. При изменении                                     атрибута, подпись будет недействительна. Сохранить                                     изменения?`.
