= Поисковые слова для исполнителя

Руководитель::
Будет найден сотрудник, который в _Справочнике Сотрудников_ указан как руководитель автора карточки _Задание_. В случае делегирования будет найден руководитель сотрудника, делегировавшего задание;
Подчиненные::
Будут найдены сотрудники данного подразделения, для которых автор карточки _Задание_ в _Справочнике Сотрудников_ указан как руководитель. В случае делегирования  будут найдены подчиненные сотрудника, делегировавшего задание;
Все подчиненные::
Сотрудники всех подразделений, для которых автор карточки _Задание_ в _Справочнике Сотрудников_ указан как непосредственный руководитель или является руководителем вышестоящего подразделения.  В случае делегирования будут найдены подчиненные сотрудника, делегировавшего задание;
Замещаемые::
Будут найдены сотрудники, для которых автор карточки _Задание_ в _Справочнике Сотрудников_ указан как заместитель. В случае делегирования будут найдены сотрудники, замещаемые по отношению к делегату задания;
Подразделения, в которых автор - руководитель::
Будут найдены все подразделения, в которых автор карточки _Задание_ в _Справочнике Сотрудников_ указан как руководитель. В случае делегирования будут найдены подразделения сотрудника, делегировавшего задание;
Сотрудники департамента автора::
Будут найдены сотрудники департамента, к которому принадлежит автор карточки _Задание_. В случае делегирования будут найдены сотрудники подразделения делегата;
Заместители::
Будут найдены сотрудники, указанные в качестве заместителей для автора карточки _Задание_ в _Справочнике Сотрудников_. В случае делегирования будут найдены заместители сотрудника, делегировавшего задание.
