= Настройка подписания операций c документом

Электронно-цифровая подпись может быть наложена не только на поля карточки, но и на операции, выполняемые посредством карточки. Подписание операций используется для заверения факта выполнения операции определенным сотрудником. Например, для фиксации фамилии сотрудника, который зарегистрировал документ. Для подписания операций настраивается отдельный набор атрибутов, который может как совпадать, так и отличаться от атрибутов подписания документа. Для атрибутов подписания операций подсветки полей карточек не предусмотрено.

Для подписания операций могут быть выполнены следующие настройки:

* xref:cSub_Document_SignOperation_add.adoc[Добавление новой операции подписания];
* xref:cSub_Document_SignOperation_delete.adoc[Удаление операции подписания];
* xref:cSub_ViewSignature_attribute_add.adoc[Добавление атрибута операции подписания];
* xref:cSub_ViewSignature_attribute_delete.adoc[Удаление атрибута операции подписания];
* xref:cSub_ViewSignature_using_add.adoc[Добавление варианта использования подписи];
* xref:cSub_ViewSignature_using_delete.adoc[Удаление варианта использования подписи].
