[[ariaid-title1]]
== Предупреждения об изменении подписанного файла и атрибута

Для пользовательских видов карточек можно настроить вывод подсказок при изменении подписанного основного файла/атрибута документа (для файла – при сохранении файла, для атрибутов – при сохранении карточки).

Чтобы настроить предупреждения об изменении подписанного файла и атрибута, выполните следующие действия:

[[task_zbq_xcx_cm__steps_crd_zcx_cm]]
. [.ph .cmd]#Перейдите на вкладку [.keyword]*Подпись*.#
. [.ph .cmd]#Установите флаг [.ph .uicontrol]*Предупреждение об изменении подписанного файла или атрибута*.#
+
По умолчанию флаг установлен.
+
* При изменении файла будет появляться сообщение: `Данный                                 документ подписан цифровой подписью, при изменении файла подпись                                 будет недействительна. Сохранить изменения файла?`;
* При сохранении карточки будет появляться сообщение: `Атрибут подписан цифровой подписью. При изменении                                     атрибута, подпись будет недействительна. Сохранить                                     изменения?`.

*На уровень выше:* xref:../pages/cSub_Type_document.adoc[Настройки типа 'Документ']
