[[ariaid-title1]]
== Выбор источника данных

Источник данных для элемента можно выбрать как в первоначальной малой форме свойств, так и в большой форме (после нажатия на *Больше...*).

Источником данных может выступать раздел/элемент метаданных простого ("плоского") типа (обозначен в конструкторе как _Struct_), либо типа _Коллекция значений_ (обозначен в конструкторе как _Table_).

Тип _Table_ позволяет хранить набор значений, благодаря которому можно заполнить с помощью одного элемента сразу некий массив данных (например, столбец в таблице).

Большинство элементов карточки используют в качестве источника метаданные простого типа:

* Карточка [.dfn .term]_Документ_:
** Основная информация;
** Системные свойства;
** Хранение;
** Отправители.
* Карточка [.dfn .term]_Задание_:
** Системные свойства;
** Настройки;
** Задание;
** Настройки завершения;
** Настройки вида подчиненного задания;
** Настройки создания подчиненного задания.

Для элементов xref:lay_Elements_Employees.adoc[Сотрудники], xref:lay_Elements_Table.adoc[Таблица] и xref:lay_Elements_Set_Of_Values.adoc[Коллекция значений] в качестве источника данных будут предлагаться разделы _коллекционного_ типа.

Пользователь может создать для карточки новые секции и поля – расширенные метаданные.

*На уровень выше:* xref:../pages/lay_Set_control_element.adoc[Настройка элементов управления]
