= Атрибуты карточки

== Общие

Тип::
  Тип объекта карточки.

== Внешний вид

Высота::
  Высота карточки при открытии.
Минимальная высота::
  Минимальная высота карточки.
Минимальная ширина::
  Минимальная ширина карточки.
Ширина::
  Ширина карточки при открытии.

== Данные

Дайджест::
  Текст XSLT-преобразования для формирования дайджеста карточки (например, <xsl:value-of select="//CustomPropertiesRow[@Property_Name="Name"]/@Value"/>, где Name – название свойства, значение которого нужно вывести в дайджесте). Это XSLT-преобразование применяется к XML-документу, содержащему данные карточки.
Файл справки::
  Полный путь к файлу справки.
Тема справки::
  Зарезервированное слово, для которого отображается справка; поле может быть оставлено пустым; если тема справки указана, то файл справки будет открываться на этой теме.

== Поведение

NoReuse::
  Запрещает переиспользование разметки карточки. Если выбрано значение *false*, то при открытии карточки используется (при наличии) разметка из кэша; если выбрано значение *true* - разметка инициализируется каждый раз при открытии новой карточки.
