[[ariaid-title1]]
== Настройка разметки

Как правило, новые пользовательские разметки создаются на основе разметок базовых типов карточек, входящих в комплект поставки системы [.dfn .term]_Docsvision_. Базовые разметки, в свою очередь, содержат наборы базовых элементов управления, не предполагающих настройки со стороны пользователя.

Настройка пользовательской разметки предполагает xref:lay_Layout_element_add.adoc[добавление] в базовую разметку дополнительных xref:lay_Control_elements.adoc['элементов управления] и изменение их свойств. Базовые элементы, которые не предполагается использовать, могут быть скрыты.

Для настройки разметки, выделенной в области [.dfn .term]_Список разметок_, предназначена область xref:lay_Interface_Layouts_panel.html[[.dfn .term]_Разметки_] главного окна конструктора.

* *link:../pages/lay_Layout_element_add.adoc[Добавление элемента управления в разметку]* +
* *xref:../pages/lay_Layout_element_delete.adoc[Удаление элемента из разметки]* +
* *xref:../pages/lay_Set_grouping.adoc[Группировка элементов]* +
* *xref:../pages/lay_Set_label.adoc[Показать текст метки]* +
* *xref:../pages/lay_Set_label_place.adoc[Положение текста]* +
* *xref:../pages/lay_Set_tabs.adoc[Создание вкладок]* +
* *xref:../pages/lay_Set_empty_cell.adoc[Создание пустой ячейки]* +
* *xref:../pages/lay_Set_size_limit.adoc[Ограничение размера]* +

*На уровень выше:* xref:../pages/lay_Work.adoc[Работа с конструктором]
