[[ariaid-title1]]
== Локализация разметки

Для разметки карточки можно предусмотреть различные варианты локализации.

При создании, разметка не содержит локализаций. xref:lay_Locale_add.adoc[Добавление] новых локализаций производится вручную из интерфейса [.dfn .term]_Конструктора разметок_. После того, как новые локали будут добавлены, при открытии разметки в [.dfn .term]_Конструкторе разметок_ локализованные названия для xref:lay_Control_elements_hardcode.adoc[встроенных элементов управления] будут загружены из сборок ресурсов. Для использованных в разметке xref:lay_Control_elements.adoc[стандартных элементов управления] локализованные названия нужно будет настроить самостоятельно.

Настройка локализации [.dfn .term]_дополнительных_ элементов управления выполняется отдельно для каждого добавленного в разметку элемента. Добавление локализованных названий выполняется в свойствах элементов. Для всех элементов могут быть локализованы некоторые xref:lay_Elements_general.adoc[общие свойства], для ряда элементов дополнительно могут быть настроены xref:lay_Locale_specific_element_properties.html[[.dfn .term]_специфические_ свойства].

При открытии карточки в клиентских приложениях системы, выбор языка карточек будет производиться в соответствии с локализацией, настроенной для приложения. В интерфейсе [.dfn .term]_Конструктора разметок_ отображение локализации зависит от значения поля [.keyword]*Локализация*.

При link:lay_Layout_copy.adoc[копировании разметки], для неё будут сгенерированы соответствующие общим настройкам вида объекты для хранения локализованных настроек. При копировании разметки из другого вида копируются только параметры по умолчанию. Если для вида, в который копируются разметки, заданы дополнительные локали, для копируемых разметок будет сгенерирован собственный [.dfn .term]_*.xml_ файл для хранения параметров локализуемых свойств. 

* *xref:../pages/lay_Locale_add.adoc[Добавление локализации разметки]* +
* *xref:../pages/lay_Locale_common_element_properties.adoc[Локализация общих свойств 'дополнительных' элементов управления]* +
* *xref:../pages/lay_Locale_specific_element_properties.adoc[Локализация специфических свойств 'дополнительных' элементов управления]* +
* *xref:../pages/lay_Locale_delete.adoc[Удаление локализации разметки]* +

*На уровень выше:* xref:../pages/lay_Work.adoc[Работа с конструктором]
