= Выбор вида карточки

В _Конструкторе разметок_ допускается редактирование разметок пользовательских видов карточек, зарегистрированных в _Справочнике видов карточек_. При открытии конструктора в xref:lay_Interface.adoc[главном окне] информация будет отсутствовать. Для начала работы необходимо выбрать вид, для которого будет выполняться настройка пользовательских разметок.

.Чтобы выбрать вид:
. Выберите на панели инструментов библиотеку карточек, а также необходимый пользовательский вид.
+
Предполагается что при настройке вида в _Справочнике видов карточек_ была выполнена настройка xref:cSub_Common_Inheritance.adoc[наследования] разметок, позволяющая редактирование карточки в _Конструкторе разметок_.
+
В случае выбора вида, который наследует свои настройки разметки от родительского вида, у пользователя появится диалоговое окно с предложением открыть родительский вид.
. При необходимости подтвердите согласие на открытие родительского вида.
+
При согласии пользователя откроется родительский вид карточки, со своей разметкой, доступной для редактирования.
+
. Чтобы изменения в разметке были применены к ранее открытым карточкам соответствующего вида, необходимо закрыть, а затем заново открыть приложение {wincl}.
