= Локализация разметки

Для разметки карточки можно предусмотреть различные варианты локализации.

При создании, разметка не содержит локализаций. xref:lay_Locale_add.adoc[Добавление] новых локализаций производится вручную из интерфейса _Конструктора разметок_. После того, как новые локали будут добавлены, при открытии разметки в _Конструкторе разметок_ локализованные названия для xref:lay_Control_elements_hardcode.adoc[встроенных элементов управления] будут загружены из сборок ресурсов. Для использованных в разметке xref:lay_Control_elements.adoc[стандартных элементов управления] локализованные названия нужно будет настроить самостоятельно.

Настройка локализации _дополнительных_ элементов управления выполняется отдельно для каждого добавленного в разметку элемента. Добавление локализованных названий выполняется в свойствах элементов. Для всех элементов могут быть локализованы некоторые xref:lay_Elements_general.adoc[общие свойства], для ряда элементов дополнительно могут быть настроены xref:lay_Locale_specific_element_properties.adoc[_специфические_ свойства].

При открытии карточки в клиентских приложениях системы, выбор языка карточек будет производиться в соответствии с локализацией, настроенной для приложения. В интерфейсе _Конструктора разметок_ отображение локализации зависит от значения поля *Локализация*.

При xref:lay_Layout_copy.adoc[копировании разметки], для неё будут сгенерированы соответствующие общим настройкам вида объекты для хранения локализованных настроек. При копировании разметки из другого вида копируются только параметры по умолчанию. Если для вида, в который копируются разметки, заданы дополнительные локали, для копируемых разметок будет сгенерирован собственный _*.xml_ файл для хранения параметров локализуемых свойств.