[[ariaid-title1]]
== Показать текст метки

Любой элемент управления (базовый, дополнительный или пользовательский), включает текстовое поле xref:lay_Elements_general.html#reference_xg4_zpv_2m__label_text[[.keyword]*Текст метки*], предназначенное для отображения названия поля в запущенной карточке. Для базовых элементов управления тексты меток не подлежат изменению. Для дополнительных элементов управления (добавляемых пользователями из области [.dfn .term]_Панель инструментов_), текст метки определяется в свойствах элемента. В зависимости от назначения элемента управления, текст метки может быть либо отображен, либо скрыт.

[NOTE]
====
[.note__title]#Прим.:# Существует также дополнительный элемент управления link:lay_Elements_Label.html[[.keyword]*Метка*], видимость которого определяется не командой [.keyword]*Показать текст метки*, в свойством элемента [.keyword]*Видимость*.
====

Чтобы отобразить/скрыть текст метки, выполните следующие действия:

. [.ph .cmd]#Выделите в области [.dfn .term]_Разметки_ или области [.dfn .term]_Структура разметки_ элемент, для которого следует изменить отображение свойства [.keyword]*Текст метки*. #
. [.ph .cmd]#Правой клавишей мыши вызовите контекстное меню, затем выберите команду [.ph .uicontrol]*Скрыть текст метки* или [.ph .uicontrol]*Отобразить текст метки*.#

*На уровень выше:* link:../pages/lay_Layout.adoc[Настройка разметки]
