[[ariaid-title1]]
== Удаление элемента из разметки

Любой элемент разметки карточки может быть удален.

Для элементов, которые не являются стандартными для системы [.dfn .term]_Docsvision_, а подключаются при установке дополнительных модулей и приложений системы (например, [.dfn .term]_Управление документами_), рекомендуется вместо операции удаления скрывать элемент, используя настройку xref:lay_ControlElements_Appearance.adoc[видимости].

Чтобы удалить элемент из разметки, выполните следующие действия:

. [.ph .cmd]#Выделите в области [.dfn .term]_Разметки_ или области [.dfn .term]_Структура разметки_ элемент, который требуется удалить. #
. [.ph .cmd]#Правой клавишей мыши вызовите контекстное меню, затем выберите команду [.ph .uicontrol]*Удалить элемент*.#
+
Элемент перестанет отображаться в разметке.

После удаления дополнительного элемента управления (установленного с дополнительным модулем), он станет доступен для добавления в разметку только после повторного открытия [.dfn .term]_Конструктора разметок_.

[NOTE]
====
[.note__title]#Прим.:# Название элемента управления на [.keyword .wintitle]*Панели инструментов* может отличаться от названия экземпляра элемента управления, удаленного из разметки.
====

*На уровень выше:* xref:../pages/lay_Layout.adoc[Настройка разметки]
