= Настройка очередности обхода полей карточки по кнопке Tab

Пользователь имеет возможность настройки собственной последовательности очередности обхода карточки по кнопке Tab.

Чтобы настроить последовательность, в группе *Поведение* xref:lay_Elements_general.adoc[Общих свойств элементов управления] предусмотрены параметры:

* xref:lay_Elements_general.adoc#reference_xg4_zpv_2m__Action_tab[Переходить по TAB];
* xref:lay_Elements_general.adoc#reference_xg4_zpv_2m__Action_order[Порядок обхода].

Чтобы включить возможность перехода по Tab, необходимо в поле _Переходить по Tab_ выбрать значение *Да*.

Порядковый номер поля задается в параметре _Порядок обхода_. Номер вводится пользователем вручную. Уникальность введенного номера системой не отслеживается, т.е. пользователь может нескольким полям проставить один и тот же номер. Например, если трем полям задать номер "5" переход к данным полям произойдет после поля с номером "4", но в произвольном порядке.

Для карточки _Документ_ данные параметры могут использоваться только для пользовательских полей. Для базовых полей данные настройки не будут работать.

Для карточки _Задание_ базовым полям назначены номера порядка обхода с шагом 10, т.е. "10", "20", "30" и т.д. Для задания очередности обхода пользовательским полям им следует задавать номера, отличные от базовых (11, 25 и т.п.).
