= Настройка разметки

Как правило, новые пользовательские разметки создаются на основе разметок базовых типов карточек, входящих в комплект поставки системы _Docsvision_. Базовые разметки, в свою очередь, содержат наборы базовых элементов управления, не предполагающих настройки со стороны пользователя.

Настройка пользовательской разметки предполагает xref:lay_Layout_element_add.adoc[добавление] в базовую разметку дополнительных xref:lay_Control_elements.adoc["элементов управления] и изменение их свойств. Базовые элементы, которые не предполагается использовать, могут быть скрыты.

Для настройки разметки, выделенной в области _Список разметок_, предназначена область xref:lay_Interface_Layouts_panel.adoc[_Разметки_] главного окна конструктора.

* *xref:../pages/lay_Layout_element_add.adoc[Добавление элемента управления в разметку]* +
* *xref:../pages/lay_Layout_element_delete.adoc[Удаление элемента из разметки]* +
* *xref:../pages/lay_Set_grouping.adoc[Группировка элементов]* +
* *xref:../pages/lay_Set_label.adoc[Показать текст метки]* +
* *xref:../pages/lay_Set_label_place.adoc[Положение текста]* +
* *xref:../pages/lay_Set_tabs.adoc[Создание вкладок]* +
* *xref:../pages/lay_Set_empty_cell.adoc[Создание пустой ячейки]* +
* *xref:../pages/lay_Set_size_limit.adoc[Ограничение размера]* +
