[[ariaid-title1]]
== Настройка безопасности

Чтобы назначить пользователям права доступа к ссылке, выполните следующие действия:

[NOTE]
====
[.note__title]#Прим.:# Если изменение настроек безопасности выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска Windows-клиент.
====

При использовании роли в качестве инструмента настройки безопасности, роль добавляет в список объектов безопасности входящих в нее сотрудников. При удалении или добавлении сотрудников к роли, безопасность объектов, которые были сконфигурированы с помощью роли, автоматически не меняется. В подобных случаях рекомендуется использовать группы.

. [.ph .cmd]#Откройте [.dfn .term]_Справочник ссылок_. #
. [.ph .cmd]#Щелкните правой кнопкой мыши по объекту, права доступа к которому необходимо назначить пользователю (пользователям). #
. [.ph .cmd]#Для отображения окна назначения прав доступа выберите из контекстного меню команду [.ph .uicontrol]*Безопасность*. #
. [.ph .cmd]#Настройте права доступа с помощью стандартного диалога управления правами. #

Ограничения прав, наложенные на первую часть двусторонней ссылки – прямую ссылку, автоматически будут применяться и ко второй части пары – обратной ссылке (хотя в окне, открывающемся при выборе из ее контекстного меню команды *Безопасность*, это отражено не будет).

*На уровень выше:* xref:../pages/link_Work.adoc[Работа со справочником]
