= Настройка безопасности

[NOTE]
====
Если изменение настроек безопасности выполнялось администратором, у обычных пользователей изменения будут применены после перезапуска {wincl}.
====

При использовании роли в качестве инструмента настройки безопасности, роль добавляет в список объектов безопасности входящих в нее сотрудников. При удалении или добавлении сотрудников к роли, безопасность объектов, которые были сконфигурированы с помощью роли, автоматически не меняется. В подобных случаях рекомендуется использовать группы.

.Чтобы назначить пользователям права доступа к ссылке:
. Откройте _Справочник ссылок_.
. Щелкните правой кнопкой мыши по объекту, права доступа к которому необходимо назначить пользователю (пользователям).
. Для отображения окна назначения прав доступа выберите из контекстного меню команду *Безопасность*.
. Настройте права доступа с помощью стандартного диалога управления правами.
+
Ограничения прав, наложенные на первую часть двусторонней ссылки -- прямую ссылку, автоматически будут применяться и ко второй части пары -- обратной ссылке (хотя в окне, открывающемся при выборе из ее контекстного меню команды *Безопасность*, это отражено не будет).
