= Работа со справочником

.Администратор или пользователь, обладающий правами модификации справочника, может выполнять следующие действия:
* добавление организации или подразделения;
* добавление сотрудника;
* изменение сведений об организации, подразделении или сотруднике;
* удаление записи об организации, подразделении или сотруднике;
* объединение подразделений и организаций в группы;
* назначение пользователям прав доступа к элементам справочника (организация, подразделение, группа, сотрудник);
* определение атрибутов, проверяемых на уникальность при сохранении карточки;
* поиск данных в справочнике (может выполняться сотрудником без прав на модификацию справочника);
* сортировка списка данных (может выполняться сотрудником без прав на модификацию справочника).

Справочник контрагентов может быть открыт для редактирования несколькими пользователями одновременно, но во время сохранения изменений одним из пользователей справочник блокируется.

После добавления организации/подразделения или сотрудника, соответствующая запись становится активной (в фокусе) в окне справочника. Однако у этого правила есть особенность: если фокус установлен только на дереве подразделений/организаций (выбрано какое-нибудь подразделение), то при добавлении Сотрудника, в правой части окна фокус на карточку сотрудника установлен не будет. Однако если перейти в правую часть (с помощью Tab или просто щелкнув по пустой области), то фокус установится на последнюю добавленную карточку. Если же изначально фокус стоял и на дереве подразделений (выбрано подразделение), и на списке сотрудников (выбрана карточка сотрудника), то при добавлении нового сотрудника фокус сразу устанавливается на добавленную карточку.

[NOTE]
====
Для заполнения справочника из *.xls файла может использоваться утилита *TOPartnersLoad*.
====
