= Управление группами

Кроме места в иерархической структуре организации, сотрудник может входить в одну или несколько групп, объединенных по каким-либо признакам, определяемым производственной необходимостью. Это могут быть, например, профессиональные статусы (секретари, бухгалтеры), должностные (руководители отделов) или любые другие (например, лица старше 50 лет). Группы могут быть организованы в иерархическую структуру.

В созданную группу можно добавлять/удалять сотрудников. Сами группы могут быть скопированы внутрь других групп. Одна и та же организация/подразделение может быть включена в две и более групп.

* *xref:../pages/part_Groups_add_partner.adoc[Добавление группы]* +
* *xref:../pages/part_Groups_add_organization.adoc[Добавление в группу организации/подразделения]* +
* *xref:../pages/part_Groups_change_organization.adoc[Изменение параметров подразделения в группе]* +
* *xref:../pages/part_Groups_delete_organization.adoc[Удаление подразделения из группы]* +
* *xref:../pages/part_Groups_view_repartment_fields.adoc[Отображение полей подразделений в группе]* +
