= Панель поиска в открытом на выбор справочнике

В справочнике контрагентов, открытом "на выбор" из какого-либо поля карточки, для поиска данных могут использоваться следующие поисковые запросы:

* _Организация/подразделение: название_;
* _Организация/подразделение: полное название_;
* _Подразделение: название_;
* _Подразделение: полное название_;
* _Организация: название_;
* _Организация: полное название_;
* _ИНН организации_;
* _Сотрудник_.

Поведение справочника при использовании режимов зависит от объекта выбора -- сотрудника/подразделения/организации.

== Режимы поиска при выборе сотрудника-контрагента

По умолчанию, в открытом на выбор справочнике контрагентов установлен режим поиска _Сотрудник_. В результатах поиска выводится информация о подразделении/организации контрагента, ФИО сотрудника и его должность. По двойному щелчку левой клавиши мыши осуществляется выбор сотрудника.

Доступны также режимы Организация/Подразделение/ИНН организации. В результатах поиска отображаются найденные Организации/Подразделения (без сотрудников и должностей с полным/кратким названием или ИНН, соответствующим строке поиска).

По двойному щелчку левой клавиши мыши на строке из результатов поиска или команде меню _Показать в справочнике_, фокус переходит на узел дерева выбранной организации/подразделения. В правой части окна будут отображены сотрудники-контрагенты из этого подразделения/организации.

== Режимы поиска при выборе организации/подразделения-контрагента

При выборе организации/подразделения контрагента возможны следующие варианты значений:

--
* Только подразделение (режим поиска по умолчанию _Подразделение: название_);
* Только организация (режим поиска по умолчанию _Организация: название_);
* Организация и подразделение (режим поиска по умолчанию _Организация/подразделение: название_).
--

Только организация::
Дополнительно появляются режимы:
+
--
* _Подразделение: название_;
* _Подразделение: полное название_;
* _Организация/подразделение: название_;
* _Организация/подразделение: полное название_;
* _Сотрудник_.
--
+
Если поиск ведется по названию (полному или краткому) подразделения, то находятся все подразделения, соответствующие строке поиска. По двойному щелчку левой клавиши мыши по строке в результатах поиска или команде _Показать в справочнике_ фокус устанавливается на узле подразделения в дереве. Для выбора доступна только организация, а не само подразделение.
+
Если поиск ведется по названию (полному или краткому) подразделения/организации, будут найдены все организации/подразделения, соответствующие строке поиска. По двойному щелчку левой клавиши мыши по строке поиска организация выбирается сразу, а если в результате найдено подразделение, то поведение соответствует предыдущему пункту (поиск по подразделению).
+
Если поиск ведется по сотруднику, то в результатах будет показан список сотрудников (ФИО, должность и подразделение/организация). По двойному щелчку левой клавиши мыши на строке из результатов поиска выбирается организация (не подразделение), в которой записан найденный сотрудник.

Только подразделение::
Дополнительно появляются режимы:
+
--
* _Организация: название_;
* _Организация: полное название_;
* _Организация/подразделение: название_;
* _Организация/подразделение: полное название_;
* _Сотрудник_;
* _ИНН организации_.
--
+
Если поиск ведется по названию (полному или краткому) организации, будут найдены все организации, соответствующие строке поиска. По двойному щелчку левой клавиши мыши по строке в результатах поиска или команде _Показать в справочнике_ фокус устанавливается на узле организации в дереве. Однако, ввиду ограничения по выбору, для выбора доступны только подразделения, а не сама организация.
+
Если поиск ведется по названию (полному или краткому) подразделения/организации, будут найдены все организации/подразделения, соответствующие строке поиска. По двойному щелчку левой клавиши мыши по строке поиска подразделение выбирается сразу, а если в результате найдена организация, то поведение соответствует предыдущему пункту (поиск по организации).
+
Если поиск ведется по сотруднику, в результатах будет показан список сотрудников, у которых указано подразделение (в результатах отображается ФИО, должность и подразделение). По двойному щелчку левой клавиши мыши на строке, из результатов поиска выбирается подразделение, в котором записан найденный сотрудник.
+
Если поиск ведется по ИНН организации, в результатах отображается организация с соответствующим строке поиска ИНН. По двойному щелчку левой клавиши мыши по строке в результатах поиска или команде _Показать в справочнике_ фокус устанавливается на узле организации в дереве. Однако, ввиду ограничения по выбору, для выбора доступны только подразделения, а не сама организация.

Организация и подразделение::
При выборе и организации, и подразделения дополнительно появляется только режим поиска _Сотрудник_. Остальные режимы работают без изменений.
+
Если поиск ведется по сотруднику, то в результатах будет показан список сотрудников (ФИО, должность и подразделение/организация). По двойному щелчку левой клавиши мыши на строке из результатов поиска выбирается организация (если сотрудник записан в корне узла организации) или подразделение (если сотрудник записан в подразделение).
