= Организации контрагентов

Карточки организаций контрагентов предназначены для хранения в системе Docsvision сведений о компаниях партнеров. Организации создаются внутри корневой организации, которая присутствует в _Справочнике контрагентов_ по умолчанию.

Для организации может быть определен специальный xref:part_Organizaton_settings_card_kind.adoc[вид карточки], который будет использоваться для хранения информации о подразделениях и сотрудниках.

Для просмотра информации об организации в справочнике может быть настроен xref:part_Set_DepartmentFields_View.adoc[способ отображения полей].

Возможно объединение организаций в xref:part_Groups_add_organization.adoc[группы].

* *xref:../pages/part_Organization_add.adoc[Добавление дочерней организации]* +
* *xref:../pages/part_Organization_change.adoc[Изменение сведений об организации]* +
* *xref:../pages/part_Organization_delete.adoc[Удаление организации]* +
* *xref:../pages/part_Set_unique_attributes.adoc[Проверка уникальности организации]* +
