= Настройка "Ролевой модели"

_Ролевая модель_ – общее наименование механизма распределения прав пользователей при работе с рядом приложений Docsvision на основе данных самой карточки.

Создание и настройка ролей пользователей начинаются с выбора типа и вида карточек. Следует учитывать, что если выбранный вид наследует настройки ролей от родительского вида, то данные настройки откроются в *Конструкторе ролей* без возможности редактирования. Если настройки именно копируются из родительского вида, то только тогда конструктор позволит изменять роли.

Непосредственно действия по созданию и настройке роли производятся на вкладке *Роли* указанного справочника.

Левая панель этой вкладки содержит список всех настроенных ролей, а правая – дерево условий, сформированных для роли, выделенной на левой панели.
[IMPORTANT]
====
Системные виды карточек: _Карточка подразделения_, _Карточка подразделения контрагента_, _Карточка сервера_, _Карточка сотрудника_, _Карточка сотрудника контрагента_, _Карточка строки справочника_ не предполагают создания собственных состояний и обработки _Ролевой моделью_. Для настройки прав доступа к данным видам карточек следует использовать дискреционную безопасность. При этом для данных видов имеет смысл создание дочерних видов и настройка собственных разметок.
====

