[[ariaid-title1]]
== Настройка 'Ролевой модели'

[.dfn .term]_Ролевая модель_ – общее наименование механизма распределения прав пользователей при работе с рядом приложений Docsvision на основе данных самой карточки.

Создание и настройка ролей пользователей начинаются с выбора типа и вида карточек. Следует учитывать, что если выбранный вид наследует настройки ролей от родительского вида, то данные настройки откроются в *Конструкторе ролей* без возможности редактирования. Если настройки именно копируются из родительского вида, то только тогда конструктор позволит изменять роли.

Непосредственно действия по созданию и настройке роли производятся на вкладке *Роли* указанного справочника.

Левая панель этой вкладки содержит список всех настроенных ролей, а правая – дерево условий, сформированных для роли, выделенной на левой панели.

[[concept_nb1_wsw_hm__sys_cards_state_roles]]
[NOTE]
====
[.note__title]#Важное замечание:#

Системные виды карточек: [.keyword .parmname]_Карточка подразделения_, [.keyword .parmname]_Карточка подразделения контрагента_, [.keyword .parmname]_Карточка сервера_, [.keyword .parmname]_Карточка сотрудника_, [.keyword .parmname]_Карточка сотрудника контрагента_, [.keyword .parmname]_Карточка строки справочника_ не предполагают создания собственных состояний и обработки [.dfn .term]_Ролевой моделью_. Для настройки прав доступа к данным видам карточек следует использовать дискреционную безопасность. При этом для данных видов имеет смысл создание дочерних видов и настройка собственных разметок.
====

* *xref:../pages/rol_Role_add.adoc[Создание роли]* +
* *xref:../pages/rol_Role_common.adoc[Настройка общей роли]* +
* *xref:../pages/rol_Condition_add.adoc[Добавление условия]* +
* *xref:../pages/rol_Condition_group_add.adoc[Добавление групп условий]* +
* *xref:../pages/rol_Condition_group_collect.adoc[Группировка и разгруппировка условий]* +
* *xref:../pages/rol_Operator_change.adoc[Изменение логического оператора]* +

*На уровень выше:* xref:../pages/rol_Work.adoc[Работа с конструктором]
