[[ariaid-title1]]
== Типы маршрутизации

По умолчанию::
  Настройки маршрутизации берутся из карточки сотрудника (исполнителя задания) в [.dfn .term]_Справочнике сотрудников_.
Онлайн задание::
  Задание приходит в настроенную виртуальную папку [.dfn .term]_Docsvision_.
Задача Почтового клиента::
  На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида Задание в системе Docsvision (в Windows-клиенте или в Web-клиенте). Также пользователю предоставляется возможность выполнять задания непосредственно в почтовом клиенте с помощью ответных писем.
Ссылка на задание::
  На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида [.keyword .parmname]_Задание_ в системе Docsvision (в Windows-клиенте или в Web-клиенте).
Письмо с описанием задания::
  На настроенный электронный почтовый ящик приходит письмо со ссылкой для доступа к карточке вида [.keyword .parmname]_Задание_ в системе Docsvision и текстом, который указан в XSLT-преобразовании.
Офлайн задание::
  Пользователь получает по электронной почте специальное сообщение (форму Outlook), внешне похожее на карточку задания, однако обмен данными происходит по электронной почте. В личную папку пользователя помещается ярлык на онлайн-задание.
  +
  Данный тип маршрутизации совместим только с карточками Docsvision 4.5. Задания Docsvision 5 не работают с данным типом маршрутизации, в [.dfn .term]_Справочнике видов карточек_ данный тип не отображается.
Зашифрованное офлайн задание::
  Данный способ маршрутизации и внешний вид карточки задания полностью аналогичны способу маршрутизации онлайн-задание, однако при отправке пользователю все данные задания автоматически шифруются и доступ к нему имеет только тот пользователь, которому оно предназначено.
  +
  Для отправки зашифрованных офлайн-заданий необходимо настроить параметры шифрования в справочнике [.dfn .term]_Системные настройки_, а также выбрать сертификат в [.dfn .term]_Консоли настройки_ (выполняется администратором системы).
  +
  Получателю зашифрованного офлайн-задания отправляются, помимо самого задания, сессионный ключ шифрования и настройки крипто-провайдера и алгоритма шифрования. Для того, чтобы получатель смог открыть свое задание, администратор должен предоставить ему личный сертификат.
  +
  Данный тип маршрутизации совместим только с карточками Docsvision 4.5. Задания Docsvision 5 не работают с данным типом маршрутизации, в [.dfn .term]_Справочнике видов карточек_ данный тип не отображается.
Не маршрутизировать::
  При отправке задания в системной папке [.dfn .term]_Карточки_ (в ветке Задание бизнес-процесса библиотеки Делопроизводство) появляется карточка задания. Вся работа пользователя с заданием осуществляется в рамках работы с приложением Windows-клиент.

*На уровень выше:* xref:../pages/staff_Employee_main_common.adoc[Общие данные сотрудника]
