= Системные группы

Вместе с установкой модуля в справочник сотрудников добавляется группа пользователей *_Системные группы*. Данная группа включает в себя набор стандартных групп {dv}:

* Администраторы (Administrators);
* Пользователи ({dv}Users );
* Продвинутые пользователи (Power Users);
* Операторы архива (Archive operators);
* Создатели поисковых запросов (Search query creators);
* Администраторы безопасности (Security administrators);
* Создатели бизнес-процессов (Workflow process creators).

*_Системные группы* используются для определения прав доступа только в текущей используемой базе данных. Группа *_Системные группы* поставляется с пустыми настройками дискреционной безопасности. Группы, входящие в *_Системные группы* не имеют собственной дискреционной безопасности, а наследуют их от родительской *_Системные группы*.

[NOTE]
====
После установки модуля рекомендуется задать индивидуальные настройки дискреционной безопасности для каждой группы, входящей в *_Системные группы*. Индивидуальные настройки дискреционной безопасности также необходимо задать для самой группы *_Системные группы*. Если эти настройки не заданы, при обновлении модуля будут применены стандартные настройки безопасности. Подробнее о настройках безопасности для *_Системных групп* см. xref:staff_Security.adoc[Настройка безопасности].
====

.Группы, входящие в *_Системные группы* имеют следующие свойства:
. Группы не имеют прав или настроек дискреционной безопасности в новой БД (по аналогии с группой Системная для WF).
. Системные группы не могут быть удалены.

== Определение прав пользователя в БД

Участие в Системных группах {dv} определяется по комбинации настроек локальных групп сервера с настройками групп Справочника сотрудников. Участники локальных серверных групп могут работать во всех БД. Пользователи, указанные в группах Справочника сотрудников, могут работать только в своей БД.

При создании новой БД, войти в систему смогут пользователи согласно настройке локальных групп сервера. Минимально необходимо иметь настройку для пользователя Администратор, который будет состоять в локальной системной группе {dv} Security Administrators. При создании новой БД Администратору необходимо войти в систему и настроить для групп, входящих в *_Системные группы* дискреционную безопасность при помощи Справочника Сотрудников.
