[[ariaid-title1]]
== Управление ролями

В [.dfn .term]_Справочнике сотрудников_ существует возможность объединения сотрудников по ролям.

Для управления ролями предназначена вкладка xref:staff_Interface_roles_tab.adoc[*Роли*], на которой выводятся роли и список сотрудников/подразделений в них.

В созданную роль можно добавлять/удалять сотрудников, по аналогии с организациями и подразделениями.

При использовании роли в качестве инструмента настройки безопасности, роль добавляет в список объектов безопасности входящих в нее сотрудников. При удалении или добавлении сотрудников к роли, безопасность объектов, которые были сконфигурированы с помощью роли, автоматически не меняется. В подобных случаях рекомендуется использовать группы.

* *xref:../pages/staff_Role_add.adoc[Добавление роли]* +
* *xref:../pages/staff_Role_delete.adoc[Удаление роли]* +
* *xref:../pages/staff_Role_add_into_role.adoc[Добавление роли в роль]* +
* *xref:../pages/staff_Role_folder_select.adoc[Выбор папки роли]* +
* *xref:../pages/staff_Role_members_delete.adoc[Исключение элементов из роли]* +

*На уровень выше:* xref:../pages/staff_Work.adoc[Работа со справочником]
