[[ariaid-title1]]
== Состояния сотрудника

Активен::
  Сотрудник активен и может выполнять свои рабочие обязанности. Состояние можно изменить как из [.dfn .term]_Справочника сотрудников_, так и из строки состояния приложения Windows-клиент.

Болен::
  Сотрудник отсутствует по состоянию здоровья. Состояние можно изменить как из [.dfn .term]_Справочника сотрудников_, так и из строки состояния приложения Windows-клиент.

В отпуске::
  Сотрудник находится в отпуске. Состояние можно изменить как из [.dfn .term]_Справочника сотрудников_, так и из строки состояния приложения Windows-клиент.

В командировке::
  Сотрудник находится в командировке. Состояние можно изменить как из [.dfn .term]_Справочника сотрудников_, так и из строки состояния приложения Windows-клиент.

Отсутствует::
  Сотрудник отсутствует по каким-либо другим причинам. Состояние можно изменить как из [.dfn .term]_Справочника сотрудников_, так и из строки состояния приложения Windows-клиент.

Уволен::
  Сотрудник уволен. Состояние доступно для смены только из [.dfn .term]_Справочника сотрудников_.

Переведен::
  Сотрудник переведен в другое подразделение. Состояние доступно для смены только из [.dfn .term]_Справочника сотрудников_.

Уволен без возможности восстановления::
  Запрет любых изменений сведений о сотруднике, в том числе, повторного изменение состояния. Работа с системой для сотрудников в данном состоянии запрещена. Состояние доступно для смены только из [.dfn .term]_Справочника сотрудников_.

*На уровень выше:* xref:../pages/staff_Employee_additional_access.adoc[Доступность сотрудника]
