[[ariaid-title1]]
== Стандартные операции редактирования

Для обслуживания стандартных элементов управления в карточках [.dfn .term]_Документ_ и [.dfn .term]_Задание_ реализован набор стандартных операций.

Если стандартная операция для состояния не включена (флаг не установлен), то соответствующая функция в карточке не будет отображаться. При этом, если флаг операции установлен, и функция в карточке отображается, но недоступна для выбора, то следует проверить настройку доступности данной операции в [.dfn .term]_Конструкторе ролей_.

* *xref:../pages/state_Operations_DocumentCard.adoc[Стандартные операции карточки 'Документ']* +
* *xref:../pages/state_Operations_TaskCard.adoc[Стандартные операции карточки 'Задание']* +
* *xref:../pages/state_Operations_GrTaskCard.adoc[Стандартные операции карточки 'Группа заданий']* +
* *xref:../pages/state_Operations_ApprCard.adoc[Стандартные операции карточки 'Согласование']* +

*На уровень выше:* xref:../pages/state_Set_EditOperation.adoc[Добавление операции редактирования]
