= Создание состояния

Конструктор состояний позволяет редактировать стандартный набор состояний (автомат состояний) выбранного вида только в том случае, если для него в _Справочнике видов карточек_ выбрана настройка *Копировать все настройки из родительского вида*.

[IMPORTANT]
====
Настройка состояний для карточек _Документ_ и _Задание_ имеет отличия. Если состояния для документа обычно настраиваются с чистого листа, то для карточек заданий существует заранее созданный жизненный цикл. Поэтому, когда пользователь желает создать состояния для карточки задания и выбирает нужный вид, в *Конструкторе состояний* будут отображён автомат состояний – система жизненного цикла карточки. Пользовательские изменения и дополнения к этой системе при этом не ограничены.
====

[IMPORTANT]
====
Системные виды карточек: _Карточка подразделения_, _Карточка подразделения контрагента_, _Карточка сервера_, _Карточка сотрудника_, _Карточка сотрудника контрагента_, _Карточка строки справочника_ не предполагают создания собственных состояний и обработки _Ролевой моделью_. Для настройки прав доступа к данным видам карточек следует использовать дискреционную безопасность. При этом для данных видов имеет смысл создание дочерних видов и настройка собственных разметок.
====

.Чтобы создать состояние, выполните следующие действия:
. xref:state_SelectCardType.adoc[Выберите] вид карточки, для которого требуется создать состояние.
. Нажмите левой кнопкой мыши по пустому месту в области автомата состояний.
. Удерживая кнопку нажатой, нарисуйте прямоугольник.
+
Получившийся блок соответствует одному состоянию.
+
Данным способом можно создать все необходимые состояния.
