[[ariaid-title1]]
== Создание состояния

Конструктор состояний позволяет редактировать стандартный набор состояний (автомат состояний) выбранного вида только в том случае, если для него в [.dfn .term]_Справочнике видов карточек_ выбрана настройка [.keyword]*Копировать все настройки из родительского вида*.

[NOTE]
====
[.note__title]#Важное замечание:# Настройка состояний для карточек _Документ_ и _Задание_ имеет отличия. Если состояния для документа обычно настраиваются с чистого листа, то для карточек заданий существует заранее созданный жизненный цикл. Поэтому, когда пользователь желает создать состояния для карточки задания и выбирает нужный вид, в *Конструкторе состояний* будут отображён автомат состояний – система жизненного цикла карточки. Пользовательские изменения и дополнения к этой системе при этом не ограничены.
====

[NOTE]
====
[.note__title]#Важное замечание:#

Системные виды карточек: [.keyword .parmname]_Карточка подразделения_, [.keyword .parmname]_Карточка подразделения контрагента_, [.keyword .parmname]_Карточка сервера_, [.keyword .parmname]_Карточка сотрудника_, [.keyword .parmname]_Карточка сотрудника контрагента_, [.keyword .parmname]_Карточка строки справочника_ не предполагают создания собственных состояний и обработки [.dfn .term]_Ролевой моделью_. Для настройки прав доступа к данным видам карточек следует использовать дискреционную безопасность. При этом для данных видов имеет смысл создание дочерних видов и настройка собственных разметок.
====

Чтобы создать состояние, выполните следующие действия:

. [.ph .cmd]#xref:state_SelectCardType.adoc[Выберите] вид карточки, для которого требуется создать состояние.#
. [.ph .cmd]#Нажмите левой кнопкой мыши по пустому месту в области автомата состояний.#
. [.ph .cmd]#Удерживая кнопку нажатой, нарисуйте прямоугольник. #
+
Получившийся блок соответствует одному состоянию.

Данным способом можно создать все необходимые состояния.

*На уровень выше:* xref:../pages/state_Work.adoc[Работа с конструктором]
