= Конструктор состояний

_Конструктор состояний_ предназначен для создания состояний объектов, настройки переходов между ними и определения разрешенных операций для каждого состояния. Конструктор работает с _Базовыми объектами_, то есть позволяет создавать и редактировать состояния для созданных видов карточек.

Разрешение на работу с конструктором определяется наличием лицензии.

Состояния необходимы для поддержания жизненного цикла карточки, поэтому для начала работы с карточкой типа _Документ_ или _Задание_ необходимо, чтобы для соответствующего вида было настроено хотя бы одно состояние. Заранее настроенный набор состояний и операций переходов между ними в системе Docsvision называется _Автоматом состояний_.

Для карточек типа _Задание_ по умолчанию имеется заранее настроенный автомат состояний, предназначенный для реализации типового жизненного цикла задания. Для карточек типа _Документ_ по умолчанию настроенных состояний не предусмотрено, однако, для карточки доступны все стандартные операции.

* *xref:../pages/state_Interface.adoc[Интерфейс "Конструктора состояний"]* +
* *xref:../pages/state_Work.adoc[Работа с конструктором]* +
