= Аннотация

== Назначение документа

Настоящий документ является руководством администратора модуля "Docsvision 5. Базовые объекты" (далее – "Модуль").

Документ содержит инструкцию по установке Модуля (серверной и клиентской частей); перечислены функции _администратора Docsvision_. Описание _конструкторов_ и _справочников_ Модуля приведено в документе _Модуль "Docsvision 5. Базовые объекты". Описание конструкторов и справочников_. Описание карточек Модуля приведено в документе _Модуль "Docsvision 5. Базовые объекты". Руководство пользователя_#

Документ предназначен для администраторов и инженеров системы Docsvision.

== Как организован документ

Настоящее руководство содержит следующие разделы:

. xref:General_information.adoc[Общие сведения] (приведены общие сведения о Модуле, требования Модуля к программному и аппаратному обеспечению компьютера).
. xref:Structureof_program.adoc[Структура Модуля] (перечислены составные части Модуля).
. xref:Install_and_configuration.adoc[Установка и настройка] (содержит инструкцию по установке и настройке Модуля).
. xref:UpdateVersion.adoc[Установка новой версии модуля] (содержит инструкцию по установке новой версии Модуля).
. xref:Administrator_functions.adoc[Функции администратора] (содержит описание настроек Модуля, выполняемых администратором Docsvision).
. xref:General_settings.adoc[Описание настроек модуля в справочнике "Системные настройки"] (содержит описание настроек Модуля в справочнике Системные настройки).

== Соглашения по оформлению

В данном документе для представления различных терминов и названий используются следующие шрифты и средства форматирования.

[width="99%",cols="34%,66%",options="header",]
|===
|Шрифт |Описание
|*Жирный* |Используется при написании названий элементов экранного интерфейса.
|_Курсив_ |Используется для обозначения новых терминов, названий типов и видов карточек.
|http://docsvision.com[Синий] |Используется для выделения перекрестных ссылок внутри документа и ссылок на доступные внешние документы, для указания адресов интернет-страниц.
|`Моноширинный` |Используется для выделения текстов макрокоманд и программных кодов, имен файлов и путей к ним. Также используется для указания необходимой опции, выделения значений, задаваемых пользователем с клавиатуры.
|===

Некоторые абзацы в тексте содержат информацию, на которую следует обратить особое внимание. Эти абзацы выделены в специальные блоки.

[IMPORTANT]
====
Служит для привлечения внимания пользователя к информации, которая необходима для корректного восприятия изложенного далее текста, и к указаниям, которые настоятельно рекомендуется выполнять.
====

[NOTE]
====
Используется для отображения информации дополнительного характера.
====
