[[ariaid-title1]]
== Бизнес-процессы

Модуль «Базовые объекты» добавляет в систему Docsvision бизнес-процессы, перечисленные далее.

. «Маршрутизация заданий в почту».
+
БП «Маршрутизация заданий в почту» выполняет следующие действия:
[loweralpha]
.. Отыскивает карточки Задание (всех видов) с параметрами:
* состояние `Начато`, `Делегировано`, `Возвращено с делегирования`;
* у исполнителя задания установлен способ маршрутизации «Письмо с описанием задания» или «Задача Почтового клиента»;
* в текущий момент времени задание не обрабатывается никаким бизнес-процессом.
.. Формирует почтовое сообщение с заданием и отсылает его пользователю.
. «ПК Мониторинг почты».
+
БП «ПК Мониторинг почты» выполняет следующие действия:

[loweralpha]
.. С периодичностью, указанной в свойствах функции [.keyword .parmname]_Мониторинг сообщений_ (вкладка [.keyword]*Общие*, поле [.ph .uicontrol]*Период опроса, мин*; по умолчанию установлено значение [.kbd .ph .userinput]`1` минута) БП отыскивает непрочитанные письма о совершении из почтового сообщения некоторого действия с заданием (тема сообщения начинается с `6EDEA0D1&`).
.. Обрабатывает каждое из полученных сообщений, передавая управление подпроцессу, ответственному за обработку данного действия или создавая сообщение о невозможности проведения данного действия.
+
Каждое полученное письмо о совершении действия обрабатывается только один раз. В случае сбоя в работе почтового сервера обработка будет начата с последнего непрочитанного сообщения.
.. Переводит обработанное сообщение в прочитанные.
. «ПК Взятие задания в работу».
+
БП «ПК Взятие задания в работу» выполняет следующие действия:
[loweralpha]
.. Получает из БП «ПК Мониторинг почты» ответное письмо по действию [.keyword .parmname]_В работу_.
.. Обрабатывает это письмо.
.. Записывает результаты в карточку задания Docsvision, изменяя состояние задания.
.. Отсылает пользователю уведомление о результате выполнения (задание успешно взято в работу или этого не произошло).
. «ПК Завершение задания».
+
БП «ПК Завершение задания» выполняет следующие действия:
[loweralpha]
.. Получает из БП «ПК Мониторинг почты» ответное письмо по действию [.keyword .parmname]_Завершить_.
.. Обрабатывает это письмо.
.. Записывает результаты в карточку задания Docsvision.
.. Отсылает пользователю уведомление о результате выполнения (задание успешно завершено или этого не произошло).
. «ПК Отклонение задания».
+
БП «ПК Отклонение задания» выполняет следующие действия:
[loweralpha]
.. Получает из БП «ПК Мониторинг почты» ответное письмо по действию [.keyword .parmname]_Отклонить_.
.. Обрабатывает это письмо.
.. Записывает результаты в карточку задания Docsvision.
.. Отсылает пользователю уведомление о результате выполнения (задание успешно отклонено или этого не произошло).

*Parent topic:* xref:../pages/Structureof_program.adoc[Структура Модуля]
