= Обработка ошибок бизнес-процесса рассылки заданий

При работе бизнес-процесса _Маршрутизация заданий в почту_ могут возникать следующие ошибки:

* Невозможность отправки заданий в связи с неработоспособностью почтового сервера, возникшей во время работы бизнес-процесса.
+
В этом случае БП выполняет 10 повторных попыток отправки почтовых сообщений с заданиями; интервал между попытками – 10 секунд. Если отправить письма с заданиями не удалось, БП останавливается по ошибке.
+
При повторном старте бизнес-процесса сообщение по уже обработанным заданиям не отсылается.
* Невозможность отправки отдельного задания. Ошибка может возникать, например, по причине превышения размера почтового сообщения.
+
В этом случае в журнал бизнес-процесса записывается сообщение о причине невозможности отправки, при этом бизнес-процесс продолжает обрабатывать следующие задания. На xref:MailAdminConfiguration.adoc[адрес администратора Docsvision] будет отправлено сообщение об ошибке.
* Получения сообщения о недоставке/ошибке почтового сообщения. Ошибка может возникать, например, если адрес получателя не существует.
+
На адрес администратора Docsvision будет отправлено сообщение об ошибке.
