= Сервис перештамповки подписей

Установка модуля добавляет в систему java-cервис перештамповки подписей. Это рабочий процесс, который требует для работы модуль Служба {ws}.

Ниже приведено описание работы Сервиса перештамповки и его настройка.

.Сервис перештамповки состоит из двух компонентов:
* Сервис перештамповки -- входит встандартную поставку модуля {bo}.
+
Расширение модуля {bo} для сервиса перештамповки подписей. Проставляет в xref:6.1@webclient:user:docs-sign.adoc[журнале подписей {wc}а] актуальный статус, тип и дату экспирации ЭП.
+
* Java-сервис -- поставляется отдельно. Java-сервис дополняет сервис перештмаповки и открывает дополнительные возможности, описанные ниже.

При наличии дополнительного Java-сервиса сервис перештамповки находит все карточки, содержащие подписи без штампа времени, а также карточки, у которых поле _Дата устаревания_ сертификата подписи соответствует заданным настройкам.

Сервис актуализирует дату устаревания сертификата подписи и даёт возможность просматривать дополнительную информацию о подписи в xref:6.1@webclient:user:docs-sign.adoc[журнале подписей {wc}а].
// Для этого требуется наличие Java-сервиса перештамповки (поставляется по запросу) или библиотеки tspcom.dll.
// 
// Чтобы использовать библиотеку tspcom.dll, Сервис должен быть развернут в 32-битном процессе Службы рабочих процессов.
Если срок действия сертификата не истёк и Java-сервис перештамповки недоступен, Сервис указывает в карточке актуальный статус подписи, тип и дату окончания срока действия сертификата.
Если срок действия сертификата не истёк, Java-сервис перештамповки доступен и функционирует, Сервис добавляет новый архивный штамп времени и улучшает подпись до CAdES-A.

== Первоначальная настройка сервиса

Ниже приведена инструкция по настройке Сервиса перештамповки подписей, встроенного в модуль Базовые объекты.

Настройки Сервиса записываются в реестр на машине с сервером Docsvision при установке модуля.

.Чтобы изменить настройки, перейдите в ветку реестра:
. `{hklm-dv}WorkerService\Connections\DocsVision`.
. В указанной ветке реестра создайте параметр для подключения к БД с произвольным именем. Это может быть, например, параметр с именем БД. В значении параметра укажите строку подключения к используемой в {dv} БД следующего вида:
+
 ConnectAddress=http://<servername>/StorageServer/StorageServerService.asmx;BaseName=<basename>
+
* Вместо `<servername>` укажите адрес подключения к серверу {dv}.
* Вместо `<basename>` укажите название БД.
+
NOTE: Один экземпляр рабочего процесса Сервиса может обрабатывать только одну БД. Соответственно, для каждого экземпляра сервиса нужно добавлять новый параметр для подключения к БД.

== Настройка обработки подписей

Обработка подписей Сервисом зависит от настроек записанных в ветке:

`{hklm-dv}SOFTWARE\DocsVision\WorkerService\Components\Signatures`

.Сервис обрабатывает подписи в следующих случаях:
* Если срок действия сертификата подписи не больше заданного в значении `DaysOffset`.
* Если не превышено заданное количество карточек с подписями в значении `BatchSize`.
* Если наступил интервал, заданный в значении `Schedule`.

.Чтобы задать собственные настройки для обработки подписей:
. В указанной ветке реестра найдите параметр `SignaturesPeriodComponentSetting` и измените в его значении:
+
* Значение `DaysOffset`. Указывает, за сколько дней до наступления даты окончания срока действия сертификата Сервис будет обрабатывать подписи.
+
Если значение не задано, используется значение по умолчанию -- `180 дней`.
+
* Значение `Schedule`. Указывает на периодичность обработки подписей Сервисом. В строке, объединенной через `;` можно задавать список времен срабатывания.
+
Если значение не задано, используется значение по умолчанию -- `60 секунд`.
+
* Значение `BatchSize`. Количество карточек, которое Сервис ищет и обрабатывает за один раз.
+
Если значение не задано, используется значение по умолчанию -- `500 карточек`.

Работа сервиса журналируется, события записываются в журнал Службы рабочих процессов по умолчанию путь следующий: `C:\ProgramData\Docsvision\WorkerService\Logs`.
