[[ariaid-title1]]
== Лицензия

Для работы с модулем «Docsvision 5. Базовые объекты» лицензия на систему Docsvision должна содержать дополнительную опцию «Docsvision Card Builder» («Конструктор карточек»). При отсутствии данной дополнительной опции возможности работы с карточками и справочниками Модуля будут ограничены:

* В «Справочнике видов карточек» сохранится возможность изменять часть существующих настроек, но создавать/удалять/переименовывать виды при этом нельзя. Также нельзя изменять настройки наследования параметров для вида.
* «Конструктор разметок» и «Конструктор скриптов» будут отображаться в списке [.ph .uicontrol]*Конструкторы и справочники*, но открыть их будет нельзя.
* В «Конструкторе состояний» будет разрешено настраивать доступность операций, но создавать/изменять/удалять состояния или переходы между состояниями при этом нельзя.
* В «Конструкторе справочников» нельзя будет добавлять новые узлы (создавать записи можно).

Для работы маршрутизации заданий в почту «Задача Почтового клиента», лицензия на систему Docsvision должна содержать дополнительную опцию «Docsvision Outlook Client». При отсутствии данной дополнительной опции исполнителям будут рассылаться простые письма с описанием задания без возможности исполнения в почтовом клиенте.

*На уровень выше:* xref:../pages/Required_resources.adoc[Необходимые ресурсы]
