= Приложение A. Описание процесса маршрутизации заданий в почту

. Бизнес-процесс мониторинга отыскивает необработанные ранее карточки Задание (всех видов) с параметрами:
+
* состояние `Начато`, `Делегировано`, `Возвращено с                             делегирования`;
* установлен способ маршрутизации `Задача Почтового клиента` (способ маршрутизации может быть указан для исполнителя в _Справочнике сотрудников_, для вида задания в _Справочнике видов карточек_ или указан в настройках задания);
* в текущий момент времени задание не обрабатывается никаким бизнес-процессом.
+
. Для каждого отобранного на предыдущем этапе задания запускается подпроцесс, который создаёт форму письма, формирует тело письма, набор доступных операций.
+
.При этом:
* набор действий, доступных к выполнению из письма, следующий:
** завершение задания; завершить задание из письма можно, если параметры завершения удовлетворяют условиям:
*** при завершении задания требуется заполнить не более одного поля;
*** параметры завершения задания ограничены следующим списком: ввод отчета, прикрепление файла отчета, ввод комментария;
+
если параметры завершения задания не удовлетворяют перечисленным условиям, в письме размещается уведомление о необходимости открыть карточку задания _{dv}_ для завершения задания;
+
** взятие в работу;
** отклонение задания;
+
[NOTE]
====
Пользователю может быть разрешено делегировать задание. Для выполнения этой операции потребуется открыть карточку задания _{dv}_.
====
+
* в тело письма помещается ссылка на карточку {dv}, по которой она может быть открыта, если на компьютере установлены клиентские компоненты _{dv}_;
* в письмо как вложения помещаются файлы документов, приложенных к карточке Задание (если выполнены соответствующие настройки в _Справочнике видов карточек_);
* в тело письма могут быть помещены атрибуты карточки документа, по которому создано задание;
* в тело письма по умолчанию помещаются атрибуты карточки задания: автор, исполнители, дата завершения, контролер, дата контроля.
+
[NOTE]
====
Идентификатор сформированного письма содержит адрес сервера {dv}, на который оно должно быть отправлено.
====
+
. После формирования письма запускается подпроцесс, отправляющий это письмо исполнителю задания. Отправка производится через почтовый клиент, с которым работает сервер {dv}; параметры работы сервера {dv} с почтой указаны в Консоли настройки {dv}.
. В процессе исполнения задания пользователь переходит по ссылке - действию в области *Действия с заданием* полученного письма. В результате формируется ответное письмо, которое пользователь отправляет на сервер.
. На сервере {dv} бизнес-процесс мониторинга почты отыскивает непрочитанные письма о совершении из почтового сообщения некоторого действия с заданием, обрабатывает каждое из полученных сообщений, передавая управление подпроцессу, ответственному за обработку данного действия или создавая сообщение о невозможности проведения данного действия. Получивший управление подпроцесс вносит в карточку задания {dv} соответствующие изменения:
+
* Состояние,
* Дата начала,
* Дата завершения,
* Отчеты (текстовый отчет и файлы отчета),
* Комментарии -- при завершении задания, отклонении задания, отказе в согласовании.
+
. После получения сервером ответного письма формируется и отправляется исполнителю письмо-уведомление о том, что операция выполнена и изменения внесены в карточку задания _{dv}_ или о том, что в ходе выполнения действия произошла ошибка.
