= Настройка ABBYY FineReader Engine

Для выполнения распознавания из карточек Модуля (в том числе для потокового ввода документов и распознавания штрих-кодов) необходимо наличие на компьютере пользователя программы "ABBYY FineReader Engine".

[NOTE]
====
Для использования "ABBYY FineReader Engine" требуется лицензия, которую можно приобрести непосредственно у компании ABBYY или у компании Docsvision, обратившись по адресу _sales@docsvision.com_.
====

Пользовательская установка "ABBYY FineReader Engine" проводится из командной строки в тихом режиме (режим отсутствия вывода дополнительной информации и запросов на подтверждение). Для установки в таком режиме следует ввести команду `setup.exe /q`. Для ввода остальных параметров установки (серийный номер, каталог установки и др.) следует воспользоваться параметром `/v`, а затем перечислить все необходимые параметры и их значения.

С учетом вышесказанного, командная строка для установки _ABBYY FineReader Engine_ выглядит следующим образом:

[source,pre,codeblock]
----
setup.exe /q /v ARCH=x86 INSTALLDIR=”C:\ProgramFiles\ABBYY\” SN=XXXX-XXXX-XXXX-XXXX-XXXX
----

где:

[source,pre,codeblock]
----
/q – запуск в silent – режиме; 
   /v – начало параметров установки;
   ARCH - разрядность устанавливаемой версии;
   INSTALLDIR – каталог установки; 
   SN – серийный номер лицензии на использование.
----

При установке без указания ключа _ARCH=x86_ на 64-разрядной машине используется автоматическое определение разрядности, что приводит к установке не поддерживаемой _Docsvision_ 64-разрядной версии _FineReader Engine_.

[NOTE]
====
Перечень всех параметров установки можно найти в справке по продукту _ABBYY FineReader Engine_ в разделе _Developer’s Help→Distribution→Installing the Library→Installing the Library in Automatic Mode_.
====

[IMPORTANT]
====
Для корректной работы Модуля с "FineReader Engine" в GAC должны быть зарегистрированы компоненты:

* `AxInterop.FineReaderVisualComponents.dll`;
* `Interop.FineReaderVisualComponents.dll`;
* `Interop.FREngine.dll`.

Перечисленные компоненты размещены в папке `Docsvision\5.5\Client\Components` каталога установки модуля "Docsvision 5. Windows-клиент".
====

После установки _ABBYY FineReader Engine_ на панель инструментов окна *Сканирование с распознаванием* (открывается из карточки _Документ_ при выборе в контекстном меню области вложений команды *Добавить отсканированный и распознанный файл*) будут добавлены элементы управления, позволяющие редактировать полученное в результате сканирования изображение, выделять области для детального просмотра и выполнять другие операции.
