= Настройка ABBYY FineReader Engine

Чтобы распознавать документы из карточек модуля (в том числе для потокового ввода документов и распознавания штрих-кодов) необходимо наличие на компьютере пользователя программы "ABBYY FineReader Engine".

[NOTE]
====
Для использования "ABBYY FineReader Engine" требуется лицензия.
====

Пользовательская установка "ABBYY FineReader Engine" проводится из командной строки в тихом режиме (режим отсутствия вывода дополнительной информации и запросов на подтверждение). Для установки в таком режиме следует ввести команду `setup.exe /q`. Чтобы вывести остальные параметры установки (серийный номер, каталог установки и др.), воспользуйтесь параметром `/v`, затем перечислите все необходимые параметры и их значения.

.Командная строка для установки ABBYY FineReader Engine:
[source,shell]
----
setup.exe /q /v ARCH=x86 INSTALLDIR=”C:\ProgramFiles\ABBYY\” SN=XXXX-XXXX-XXXX-XXXX-XXXX <.>
----
<.> Здесь:
+
* `/q` -- запуск в silent -- режиме;
* `/v` -- начало параметров установки;
* `ARCH` -- разрядность устанавливаемой версии;
* `INSTALLDIR` -- каталог установки;
* `SN` -- серийный номер лицензии на использование.

WARNING: При установке без указания ключа _ARCH=x86_ на 64-разрядной машине разрядность определяется автоматически, что приводит к установке не поддерживаемой {dv} 64-разрядной версии _FineReader Engine_.

[NOTE]
====
Перечень всех параметров установки можно найти в справке по продукту _ABBYY FineReader Engine_ в разделе menu:Developer’s Help[Distribution > Installing the Library > Installing the Library in Automatic Mode].
====

[WARNING]
====
Для корректной работы модуля с "FineReader Engine" в GAC должны быть зарегистрированы компоненты:

* `AxInterop.FineReaderVisualComponents.dll`;
* `Interop.FineReaderVisualComponents.dll`;
* `Interop.FREngine.dll`.

Перечисленные компоненты размещены в папке `{dv}\5.5\Client\Components` каталога установки модуля {wincl}.
====

После установки _ABBYY FineReader Engine_ на панель инструментов окна _Сканирование с распознаванием_ (открывается из карточки _Документ_ при выборе в контекстном меню области вложений команды _Добавить отсканированный и распознанный файл_) будут добавлены элементы управления, позволяющие редактировать полученное в результате сканирования изображение, выделять области для детального просмотра и выполнять другие операции.
