[[ariaid-title1]]
== Программное обеспечение, необходимое для работы с сертификатами КриптоПро

Следующее программное обеспечение должно быть установлено на компьютере для использования сертификатов УЦ КриптоПро для формирования/проверки усиленной квалифицированной или усовершенствованной ЭП.

=== Требования к клиентским рабочим местам

. Компоненты криптопровайдера «КриптоПро»:
* КриптоПро CSP версии 3.9/4.0/5.0;
* КриптоПро TSPCOM версии 1.05.1379 / 1.05.1057 / 2.0.12450;
* КриптоПро OCSPCOM версии 1.05.1178 / 1.05.1053 / 2.0.12261;
* КриптоПро CADESCOM 2.0.13292.
. Сертификаты:
* Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователя xref:#fntarg_1[^1^] – должен быть установлен в хранилище «Доверенные корневые центры сертификации» на уровне «Локальный компьютер»;
* сертификат пользователя – должен быть установлен в хранилище «Личное» на уровне «Текущий пользователь».

*Обратите внимание*:

* Для использования функции КриптоПро «Облачный провайдер» требуется «КриптоПро CSP» версии 5.0 или выше. В качестве сервера электронной подписи может выступать КриптоПро DSS.
* Для использования ключей ЭП ГОСТ Р 34.10-2012 требуется «КриптоПро CSP» версии 4.0 или выше.
* Для работы с КриптоПро должна быть выполнена настройка, рассмотренная в пункте link:CfgCryptoPro.adoc[Настройка Docsvision для работы с криптопровайдером КриптоПро].
* По вопросам получения компонентов криптопровайдера «КриптоПро» следует обращаться в компанию ООО "КРИПТО-ПРО".

*На уровень выше:* xref:../pages/Required_resources_software.adoc[Необходимое программное обеспечение]

link:#fnsrc_1[^1^] Например, корневой сертификат КриптоПро.
