[[ariaid-title1]]
== Необходимое программное обеспечение

=== Требования серверной части Модуля

. *Модули Docsvision*:
[loweralpha]
.. Серверная часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4553 и выше.
.. Серверная часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля «Docsvision 5. Управление процессами» версии 5.5.2 сборка 4224 и выше.
.. Серверная часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4221 и выше.
.. Серверная часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4203 и выше.
.. Серверная часть модуля «Docsvision 5. Windows-клиент» версии 5.5.2 сборка 4248 и выше.

=== Требования клиентской части Модуля

. *Модули Docsvision*:
[loweralpha]
.. Клиентская часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4553 и выше.
.. Клиентская часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля «Docsvision 5. Управление процессами» версии 5.5.2 сборка 4224 и выше.
.. Клиентская часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4221 и выше.
.. Клиентская часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4203 и выше.
.. Клиентская часть модуля «Docsvision 5. Windows-клиент» версии 5.5.2 сборка 4248 и выше.
. *Дополнительное программное обеспечение:*
[loweralpha]
.. ABBYY FineReader Engine 11.0 (32-разрядная версия) – для работы функции распознавания в карточках Модуля (в т.ч. для потокового ввода документов и распознавания штрих-кодов). Дополнительная информация приведена в пункте xref:Preparing_to_Work_Install_ABBYYFineReader.adoc[Настройка ABBYY FineReader Engine].
.. Почтовый клиент – для работы с заданиями, маршрутизируемыми в почту.
+
*Известные проблемы совместимости*. При использовании почтового клиента Gmail в операционной системе iOS, а также MS Outlook в операционной системе Android, при формировании ответного письма часть содержимого темы письма обрезается, что делает невозможным обработку данных писем на сервере Docsvision. Используйте альтернативные почтовые клиенты в данном случае.

* *xref:../pages/Requirements_software_forsign.adoc[Программное обеспечение, необходимое для работы с сертификатами КриптоПро]* +

*На уровень выше:* xref:../pages/Required_resources.adoc[Необходимые ресурсы]
