= Маршрутизация заданий в электронную почту

Пользователи могут получать информацию о новых заданиях {dv} по электронной почте, а также выполнять задания с использованием почтового клиента (без использования {wincl}а и {wc}а).

.Возможности по работе с заданием, полученным по почте, зависят от типа маршрутизации данного задания:
Ссылка на задание::
При данном типе маршрутизации в электронное письмо добавляется только ссылка для открытия задания в {wincl}е или в {wc}е.

Письмо с описанием задания::
При данном типе маршрутизации в электронное письмо добавляется описание задания, а также ссылка для открытия задания в {wincl}е или в {wc}е.

Задача Почтового клиента::
При данном типе маршрутизации в электронное письмо добавляются кнопки для выполнения задания, описание задания, а также ссылка для открытия задания в {wincl}е или в {wc}е.
+
Для использования маршрутизации *_Задача Почтового клиента_* xref:ROOT:requirements.adoc#routing[требуется] лицензия. При отсутствии лицензии, в уведомлениях будут отсутствовать кнопки завершения заданий.

.Тип маршрутизации может быть выбран для вида заданий и для сотрудника:
* Если тип маршрутизации выбран для вида задания, то все задания данного вида будут маршрутизироваться выбранным способом.
* Если тип маршрутизации выбран для сотрудника, то все его задания будут маршрутизироваться выбранным способом.

Тип маршрутизации, выбранный для вида задания, имеет приоритет над типом маршрутизации, который выбран для сотрудника.

Чтобы настроить маршрутизацию заданий в почту, следуйте инструкции, приведенной далее. Если маршрутизация не требуется, данную настройку можно пропустить.

Подробнее о процессе маршрутизации в почту см. xref:appendix/routing-description.adoc[].
