= Настройка маршрутизации заданий в электронную почту

Пользователи могут получать информацию о новых заданиях Docsvision по электронной почте, а также выполнять задания с использованием почтового клиента (без использования Windows-клиента и Web-клиента).

Возможности по работе с заданием, полученным по почте, зависят от типа маршрутизации данного задания:

* "Ссылка на задание" – при данном типе маршрутизации в электронное письмо добавляется только ссылка для открытия задания в Windows-клиенте или в Web-клиенте;
* "Письмо с описанием задания" – при данном типе маршрутизации в электронное письмо добавляется описание задания, а также ссылка для открытия задания в Windows-клиенте или в Web-клиенте;
* "Задача Почтового клиента"– при данном типе маршрутизации в электронное письмо добавляются кнопки для выполнения задания, описание задания, а также ссылка для открытия задания в Windows-клиенте или в Web-клиенте.
+
Для использования маршрутизации "Задача Почтового клиента" требуется лицензия (см. требования). При отсутствии лицензии, в уведомлениях будут отсутствовать кнопки завершения заданий.

Тип маршрутизации может быть выбран для вида заданий и для сотрудника:

* если тип маршрутизации выбран для вида задания, то все задания данного вида будут маршрутизироваться выбранным способом;
* если тип маршрутизации выбран для сотрудника, то все его задания будут маршрутизироваться выбранным способом.

Тип маршрутизации, выбранный для вида задания, имеет приоритет над типом маршрутизации, который выбран для сотрудника.

Чтобы настроить маршрутизацию заданий в почту, следуйте инструкции, приведенной далее. Если маршрутизация не требуется, данную настройку можно пропустить.

* *xref:../pages/MailAdminConfiguration.adoc[Настройка общих параметров маршрутизации]* +
* *xref:../pages/TaskRoutingForKind.adoc[Включение маршрутизации заданий для вида заданий]* +
* *xref:../pages/TaskRoutingForUser.adoc[Включение маршрутизации заданий для отдельного сотрудника]* +
* *xref:../pages/ConfigStateAndRole.adoc[Настройка параметров для согласования документов]* +
* *xref:../pages/TaskMailTemplate.adoc[Настройка шаблонов почтовых уведомлений]* +
* *xref:../pages/RunMailMon.adoc[Запуск БП "ПК Мониторинг почты"]* +

