= Создание карточки "Бизнес-календарь"

Карточка _Бизнес-календарь_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта. В базовый комплект поставки системы _{dv} 5_ (при отсутствии модуля _{ud}_) входит базовый тип карточки _Бизнес-календарь_. Данный тип может использоваться для создания карточек, однако его настройки не подлежат изменению. Поэтому, при работе с системой рекомендуется пользоваться дочерними видами карточек, созданными на основе базового типа _Бизнес-календарь_.

[IMPORTANT]
====
Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====

Создание карточки _Бизнес-календарь_ может быть выполнено следующими способами:

* В программе {wincl}:
** с помощью ленты {wincl}а;
** с помощью меню {wincl}а;
** по заранее созданному шаблону;
** из открытой карточки того же вида;
** из открытой карточки по команде *Создать карточку*.
* В модуле _Рабочее место администратора_:
** с помощью инструментов модуля;
** по шаблону;
** из открытой карточки того же типа.
