= Работа с карточкой "Бизнес-календарь"

Карточка _Бизнес-календарь_, входящая в состав библиотеки _Базовые объекты_, предназначена для хранения информации о расписании работы сотрудников (количество рабочих дней, рабочих часов и др.) на определенный период времени. Карточка входит в комплект поставки системы _Docsvision 5_. Название карточки соответствует названию ее типа в _Справочнике видов карточек_.

[NOTE]
====
В системе _Docsvision 5_ используются следующие виды календарей:

. *Системный бизнес-календарь*. Не подлежит изменению со стороны пользователей. Задает режим работы: по будням с 9 до 18, выходные – суббота и воскресенье.
. *Календарь по умолчанию*. Календарь задается в справочнике _Системные настройки_ (Делопроизводство). Если календарь не определен, будет использоваться Системный бизнес-календарь.
. *Бизнес-календарь сотрудника* (организации, подразделения). Указывается в _Справочнике сотрудников_. Данный календарь имеет более высокий приоритет, чем Календарь по умолчанию и Системный календарь. Для настройки расписания данного календаря используется Карточка бизнес-календаря.
====

Специальные бизнес-календари могут создаваться не только для сотрудников, но и для подразделений и организаций. В календаре могут быть указаны рабочие, выходные, праздничные дни, в том числе отгулы, командировки, отпуск или болезнь сотрудника. В том числе, может быть указано нестандартное рабочее/нерабочее время, например, частичная занятость или отсутствие сотрудника в течение дня.

Информация бизнес-календаря учитывается при расчете сроков завершения задания в карточках _Задание_ и _Группа заданий_.

[NOTE]
====
Для карточек _Делопроизводство_ в справочнике _Системные настройки_ один из созданных календарей может быть настроен для использования по умолчанию для всех организаций, подразделений и сотрудников. В _Справочнике сотрудников_ для каждого сотрудника/организации/подразделения можно также указать бизнес-календарь, который будет использоваться для выбранного подразделения/сотрудника. При создании дочерних объектов бизнес-календарь наследуется, однако, впоследствии вид используемого календаря для каждого из дочерних объектов может быть изменен пользователем.
====

* *xref:../pages/Calendar_interface.adoc[Интерфейс карточки "Бизнес-календарь"]* +
* *xref:../pages/Calendar_create.adoc[Создание карточки "Бизнес-календарь"]* +
* *xref:../pages/Calendar_config.adoc[Настройка карточки "Бизнес-календарь"]* +
