[[ariaid-title1]]
== Создание карточки 'Бизнес-календарь'

Карточка [.dfn .term]_Бизнес-календарь_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта. В базовый комплект поставки системы [.dfn .term]_Docsvision 5_ (при отсутствии модуля [.dfn .term]_Управление документами_) входит базовый тип карточки [.dfn .term]_Бизнес-календарь_. Данный тип может использоваться для создания карточек, однако его настройки не подлежат изменению. Поэтому, при работе с системой рекомендуется пользоваться дочерними видами карточек, созданными на основе базового типа [.dfn .term]_Бизнес-календарь_.

[NOTE]
====
[.note__title]#Важное замечание:# Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====

Создание карточки [.dfn .term]_Бизнес-календарь_ может быть выполнено следующими способами:

* В программе Windows-клиент:
** с помощью ленты Windows-клиента;
** с помощью меню Windows-клиента;
** по заранее созданному шаблону;
** из открытой карточки того же вида;
** из открытой карточки по команде [.ph .uicontrol]*Создать карточку*.
* В модуле [.dfn .term]_Рабочее место администратора_:
** с помощью инструментов модуля;
** по шаблону;
** из открытой карточки того же типа.

*На уровень выше:* xref:../pages/Calendar_card.adoc[Работа с карточкой «Бизнес-календарь»]
