= Краткое описание возможностей

Модуль "Базовые объекты" является базовым модулем системы Docsvision, который добавляет в Docsvision базовые типы карточек, основные справочники и конструкторы, а именно:

* карточки: Бизнес-календарь, Группа заданий, Документ, Задание, Карточка подразделения, Карточка подразделения контрагента, Карточка сервера, Карточка сотрудника, Карточка сотрудника контрагента, Карточка строки справочника, Согласование;
* справочники: Справочник видов карточек, Справочник категорий, Справочник контрагентов, Справочник меток подписей, Справочник серверов, Справочник сотрудников и Справочник ссылок;
* конструкторы: Конструктор правил нумерации, Конструктор разметок, Конструктор ролей, Конструктор скриптов, Конструктор состояний, Конструктор справочников.

Модуль предоставляет следующие возможности:

* создание (с минимальным набором данных и возможностей) карточек документов, заданий и групп заданий;
* ведение списка организаций и сотрудников организаций; управление группами пользователей;
* ведение списка контрагентов и сотрудников контрагентов;
* настройка правил автоматической нумерации документов;
* настройка разметок карточек;
* настройка автомата состояний карточек;
* настройка ролевой модели безопасности;
* разработка скриптов карточек на языках C# и VB.NET;
* оповещение исполнителей заданий по электронной почте; рассылка и выполнение заданий по электронной почте.
