[[ariaid-title1]]
== Настройка дерева исполнения связанных карточек

С помощью [.dfn .term]_Конструктора разметок_ на разметку карточки документа/задания может быть добавлен элемент управления [.dfn .term]_Дерево исполнения_.

Создание/удаление задания доступно из контекстного меню этого элемента. При создании задания, связанного с документом, имеется возможность выбрать вид задания или создать задание корневого вида. Также можно настроить или уточнить поведение задания в случае необходимости (указать получателя задания, срок исполнения и прочее). После того, как требуемые настройки сделаны, можно отслеживать исполнение задания и управлять его ходом (доступ к этой функции зависит от настроек в конструкторах _состояний_ и _ролей_) непосредственно из карточки документа (с помощью дерева исполнения заданиями).

При создании задания из карточки документа, этот документ для задания считается основным (отображается согласно настройкам карточки задания).

*На уровень выше:* xref:../pages/Card_extra_elements.adoc[Дополнительные возможности карточек]
