[[ariaid-title1]]
== Создание карточки 'Документ'

Карточка [.dfn .term]_Документ_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта. В базовый комплект поставки системы [.dfn .term]_Docsvision 5_ (при отсутствии модуля [.dfn .term]_Управление документами_) входит базовый тип карточки [.dfn .term]_Документ_. Данный тип может использоваться для создания карточек, однако его настройки не подлежат изменению. Поэтому, при работе с системой рекомендуется пользоваться дочерними видами карточек, созданными на основе базового типа [.dfn .term]_Документ_.

[NOTE]
====
[.note__title]#Важное замечание:# Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====

Создание карточки [.dfn .term]_Документ_ может быть выполнено следующими способами:

* В программе Windows-клиент:
** с помощью ленты Windows-клиента;
** с помощью меню Windows-клиента;
** по заранее созданному шаблону;
** из открытой карточки того же вида;
** из открытой карточки по кнопке [.ph .uicontrol]*Создать карточку*.
* В приложении [.dfn .term]_Рабочее место администратора_:
** с помощью инструментов модуля;
** по шаблону;
** из открытой карточки того же типа;
** из открытой карточки по кнопке [.ph .uicontrol]*Создать карточку*.

Также для карточек [.dfn .term]_Документ_ существуют дополнительные способы создания:

* xref:DCard_create_by_barcode.adoc[создание карточки по штрих-коду];
* xref:DCard_create_by_file.adoc[создание карточки при перетаскивании файла в Windows-клиенте];
* xref:Card_extra_links.adoc[по ссылке из другой карточки];
* xref:Card_extra_perform_tree.adoc[из дерева исполнения связанной карточки].

При создании карточки [.dfn .term]_Документ_ могут применяться настройки, выполненные для данного вида в [.dfn .term]_Справочнике видов карточек_. Например, при сохранении карточки может выполняться проверка уникальности атрибутов карточки, синхронизация свойств карточки и вложенного файла и другие действия.

* *xref:../pages/DCard_create_by_file.adoc[Создание карточки при перетаскивании файла в Windows-клиент]* +
* *xref:../pages/DCard_create_by_barcode.adoc[Создание карточки по штрих-коду]* +

*На уровень выше:* xref:../pages/Dcard.adoc[Работа с карточкой «Документ»]
