[[ariaid-title1]]
== Прикладывание произвольного файла к ответному письму

[NOTE]
====
[.note__title]#Прим.:# При работе с письмами следует учитывать, что при прикреплении к письму изображения (картинки, фотографии или скриншота) прикрепленный файл не будет отображаться в письме при использовании встроенного почтового клиента MacOS, использовании Gmail и MS Outlook в операционной системе Windows, а также при использовании MS Outlook в операционной системе iOS.
====

Чтобы приложить к ответному письму произвольный файл, выполните следующие действия:

[[task_gm5_zkq_t4__steps_kq2_2lq_t4]]
. [.ph .cmd]#Откройте почтовое сообщение.#
. [.ph .cmd]#В секции почтового сообщения [.keyword]*Действия с заданием* нажмите ссылку, соответствующую выбранному варианту завершения задания.#
+
Будет открыто новое письмо с параметрами:

* в поле [.ph .uicontrol]*Кому* будет скопировано значение из поля [.ph .uicontrol]*От* исходного письма с заданием;
* в поле [.ph .uicontrol]*Тема* будет помещен идентификатор, соответствующий выбранному варианту завершения.
. [.ph .cmd]#Приложите к письму нужный файл. Введите в поле содержания письма описание приложенного файла.#
. [.ph .cmd]#Отправьте письмо.#

В карточке Задание текст письма будет отображаться как текстовый отчет, а приложенный файл – как файл отчета. После обработки полученного письма БП будет изменено состояние задания, а на вкладке [.keyword]*История* карточки задания будет сделана соответствующая запись.

*На уровень выше:* xref:../pages/Work_with_Task.adoc[Исполнение заданий]
