= Прикладывание произвольного файла к ответному письму

[NOTE]
====
При работе с письмами следует учитывать, что при прикреплении к письму изображения (картинки, фотографии или скриншота) прикрепленный файл не будет отображаться в письме при использовании встроенного почтового клиента MacOS, использовании Gmail и MS Outlook в операционной системе Windows, а также при использовании MS Outlook в операционной системе iOS.
====

.Чтобы приложить к ответному письму произвольный файл, выполните следующие действия:
. Откройте почтовое сообщение.
. В секции почтового сообщения *Действия с заданием* нажмите ссылку, соответствующую выбранному варианту завершения задания.
+
Будет открыто новое письмо с параметрами:
+
* в поле *Кому* будет скопировано значение из поля *От* исходного письма с заданием;
* в поле *Тема* будет помещен идентификатор, соответствующий выбранному варианту завершения.
+
. Приложите к письму нужный файл. Введите в поле содержания письма описание приложенного файла.
. Отправьте письмо.
+
В карточке Задание текст письма будет отображаться как текстовый отчет, а приложенный файл – как файл отчета. После обработки полученного письма БП будет изменено состояние задания, а на вкладке *История* карточки задания будет сделана соответствующая запись.
