= Создание карточки "Группа заданий"

Карточка _Группа заданий_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта. В базовый комплект поставки системы _Docsvision 5_ (при отсутствии модуля _Управление документами_) входит базовый тип карточки _Группа заданий_. Данный тип может использоваться для создания карточек, однако его настройки не подлежат изменению. Поэтому, при работе с системой рекомендуется пользоваться дочерними видами карточек, созданными на основе базового типа _Группа заданий_.

[IMPORTANT]
====
Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====

.Создание карточки _Группа заданий_ может быть выполнено следующими способами:
* В программе Windows-клиент:
** с помощью ленты Windows-клиента;
** с помощью меню Windows-клиента;
** по заранее созданному шаблону;
** из открытой карточки того же вида;
** из открытой карточки по кнопке Создать карточку.
* В приложении _Рабочее место администратора_:
** с помощью инструментов модуля;
** по шаблону;
** из открытой карточки того же типа;
** из открытой карточки по кнопке Создать карточку.

.Также для карточек _Группа заданий_ существуют дополнительные способы создания:
* xref:Card_extra_links.adoc[по ссылке из другой карточки];
* xref:Card_extra_perform_tree.adoc[из дерева исполнения связанной карточки].

Созданная карточка изначально находится в состоянии *Инициализация* (в соответствии с "автоматом состояний"). При этом часть полей карточки будут автоматически заполнены на основе следующих сведений:

* В качестве *Автора* задания указывается текущий сотрудник;
* Настройки карточки наследуются из вида или шаблона (если карточка создается из него).

.Созданную карточку необходимо настроить:
* xref:GrTcard_create_author.adoc[Выбрать автора задания];
* xref:GrTcard_create_name.adoc[Ввести название и содержание задания];
* xref:GrTcard_create_performer.adoc[Выбрать исполнителя задания];
* xref:GrTcard_create_deadline.adoc[Указать сроки исполнения задания];
* xref:GrTcard_create_control_acceptance.adoc[Настроить контроль исполнения задания].
