= Делегирование задания

.Чтобы делегировать задание другому исполнителю, выполните следующие действия:
. Откройте почтовое сообщение с заданием.
. Нажмите кнопку *Делегировать без возврата* или *Делегировать с возвратом* (задание вернется на исполнение после выполнения делегатом). Будет открыто новое письмо с параметрами:
+
* в поле *Скрытая копия* (СК) будет скопировано значение из поля *От* исходного письма с заданием;
* в поле *Тема* будет помещена строка с параметрами выполнения задания на сервере Docsvision;
* в тело письма будет добавлено сообщение: "Выполняется делегирование задания. Для работы с ним необходимо дождаться сообщения о делегировании от системы".
+
Кнопки *Делегировать без возврата* или *Делегировать с возвратом* могут быть недоступны, если операция делегирования запрещена правами или настройками задания.
+
. В поле *Кому* укажите адрес электронной почты сотрудника, которому выполняется делегирование. Данный адрес должен быть указан в Справочнике сотрудников в карточке данного сотрудника.
. Если нужно, добавьте собственное сообщение для делегата в тело письма.
. Отправьте письмо.
+
Данное письмо будет отправлено делегату и серверу Docsvision.
+
После обработки полученного письма сервером Docsvision:
+
.. Состояние задания изменится на `Делегировано`.
.. Исполнителю будет отправлено уведомление о результате выполнения или об ошибке.
.. Задание будет передано на исполнение сотруднику с указанным почтовым адресом.
+
Задание делегата выполняется обычным образом: с помощью клиента Docsvision или с помощью почтового клиента, если для задания настроена маршрутизация с типом "Задача Почтового клиента".
+
Если выполнено делегирование с возвратом, то задание вернется после исполнения делегатом.

