= Завершение задания

. Откройте почтовое сообщение с заданием.
. Нажмите кнопку *Завершить* (или другой доступный вариант завершения). Будет открыто новое письмо с параметрами:
+
* в поле *Кому* будет скопировано значение из поля *От* исходного письма с заданием;
* в поле *Тема* будет помещена строка с параметрами выполнения задания на сервере {dv}.
+
Кнопка *Завершить* может быть недоступна, если для завершения требуется изменить поля карточки Задание (исключение приведено ниже). В этом случае письмо будет содержать сообщение "Для завершения задания необходимо открыть карточку задания {dv}". Чтобы завершить такое задание, откройте его в Windows-клиенте или в Web-клиенте.
+
. При необходимости введите отчет следующим образом:
+
* текстовый отчет вводится в поле *Содержание* письма и передается в поле *Отчет* карточки задания _{dv}_;
* файл отчета прикладывается к письму как вложение и передается в карточку задания как ссылка на отчет об исполнении.
+
Если для завершении задания необходимо заполнить *одно текстовое поле*, то это так же можно сделать, введя нужный текст в поле *Содержание* ответного письма.
+
. Отправьте письмо.
+
После обработки полученного письма сервером {dv}:
+
.. Состояние задания изменится на `Завершено`.
.. Исполнителю будет отправлено уведомление о результате выполнения или об ошибке. Например, если к заданию не приложен отчет, который является обязательным для данного задания, сервер {dv} вернет письмо с сообщением: "При завершении задания Вы забыли приложить отчет".
