[[ariaid-title1]]
== Отклонение задания

[[task_kn2_jtv_zn__steps_tjt_41k_14]]
. [.ph .cmd]#Откройте почтовое сообщение с заданием.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Отклонить*. Будет открыто новое письмо с параметрами:#
+
* в поле [.ph .uicontrol]*Кому* будет скопировано значение из поля [.ph .uicontrol]*От* исходного письма с заданием;
* в поле [.ph .uicontrol]*Тема* будет помещена строка с параметрами выполнения задания на сервере Docsvision.
. [.ph .cmd]#Укажите причину отклонения задания в содержании письма.#
. [.ph .cmd]#Отправьте письмо.#
+
После обработки полученного письма сервером Docsvision:

[loweralpha]
.. Состояние задания изменится на `В                             Отклонено`.
.. Исполнителю будет отправлено уведомление о результате выполнения или об ошибке. Например, если не указана причина отклонения, но её указание является обязательным для данного задания, письмо будет содержать сообщение: «Невозможно отклонить задание, укажите причину отклонения».

*На уровень выше:* xref:../pages/Work_with_Task.adoc[Исполнение заданий]
