[[ariaid-title1]]
== Завершение задания

[[task_hhh_5tv_zn__steps_kjt_rck_14]]
. [.ph .cmd]#Откройте почтовое сообщение с заданием.#
. [.ph .cmd]#Нажмите кнопку [.ph .uicontrol]*Завершить* (или другой доступный вариант завершения). Будет открыто новое письмо с параметрами:#
+
* в поле [.ph .uicontrol]*Кому* будет скопировано значение из поля [.ph .uicontrol]*От* исходного письма с заданием;
* в поле [.ph .uicontrol]*Тема* будет помещена строка с параметрами выполнения задания на сервере Docsvision.
+
Кнопка [.ph .uicontrol]*Завершить* может быть недоступна, если для завершения требуется изменить поля карточки Задание (исключение приведено ниже). В этом случае письмо будет содержать сообщение «Для завершения задания необходимо открыть карточку задания Docsvision». Чтобы завершить такое задание, откройте его в Windows-клиенте или в Web-клиенте.
. [.ph .cmd]#При необходимости введите отчет следующим образом:#
* текстовый отчет вводится в поле [.ph .uicontrol]*Содержание* письма и передается в поле [.ph .uicontrol]*Отчет* карточки задания [.dfn .term]_Docsvision_;
* файл отчета прикладывается к письму как вложение и передается в карточку задания как ссылка на отчет об исполнении.
+
Если для завершении задания необходимо заполнить [.keyword]*одно текстовое поле*, то это так же можно сделать, введя нужный текст в поле [.ph .uicontrol]*Содержание* ответного письма.
. [.ph .cmd]#Отправьте письмо.#
+
После обработки полученного письма сервером Docsvision:

[loweralpha]
.. Состояние задания изменится на `Завершено`.
.. Исполнителю будет отправлено уведомление о результате выполнения или об ошибке. Например, если к заданию не приложен отчет, который является обязательным для данного задания, сервер Docsvision вернет письмо с сообщением: «При завершении задания Вы забыли приложить отчет».

*На уровень выше:* xref:../pages/Work_with_Task.adoc[Исполнение заданий]
