[[ariaid-title1]]
== Выбор вида подчиненного задания

Вид подчиненных заданий, которые создаются из карточек [.dfn .term]_Задание_, настраивается для вида задания в [.dfn .term]_Справочнике видов карточек_. Однако, имеется возможность индивидуального выбора вида подчиненного задания для конкретного экземпляра задания.

Чтобы настроить вид подчиненного задания, создаваемого из данного экземпляра задания, выполните следующие действия:

[[task_ums_ck4_24__steps_j2x_wg4_24]]
. [.ph .cmd]#Откройте карточку [.dfn .term]_Задание_, затем перейдите на xref:Tcard_settings.html[вкладку [.keyword]*Настройки*].#
. [.ph .cmd]#Найдите область [.keyword]*Вид подчиненного задания*#
. [.ph .cmd]#Выберите предпочтительный вариант настройки вида:#
* [.keyword]*Того же вида, что и родительское задание* – дочернее задание будет автоматически наследовать вид родительского задания;
* [.keyword]*Выбор любого вида задания* - пользователь может выбрать произвольный вид из числа доступных;
* [.keyword]*Выбор вида из ограниченного списка* – пользователь может выбрать вид из сформированного списка. В расположенном ниже поле можно вручную указать, какие именно виды будут доступны для выбора.  
+
При создании нового задания из открытой карточки [.dfn .term]_Задание_ пользовательского вида будет создаваться новая карточка [.dfn .term]_Задание_, вид карточки будет соответствовать выполненным настройкам.

*На уровень выше:* link:../pages/Tcard.adoc[Работа с карточкой «Задание»]
