[[ariaid-title1]]
== Настройки завершения задания

Возможность автоматического завершения задания имеется только в том случае, если карточка задания находится в состоянии _В работе_ (доступен переход _Прекратить исполнение_).

Настройки завершения карточек [.dfn .term]_Задание_ определяются для вида задания в [.dfn .term]_Справочнике видов карточек_. Однако, имеется возможность индивидуального изменения данных настроек для конкретного экземпляра задания.

Чтобы настроить параметры завершения задания, выполните следующие действия:

[[task_smg_q1p_24__steps_j2x_wg4_24]]
. [.ph .cmd]#Откройте карточку [.dfn .term]_Задание_, затем перейдите на вкладку xref:Tcard_settings_extra.html[[.keyword]*Расширенные настройки*].#
. [.ph .cmd]#Чтобы настроить автоматическое завершение задания: #
[loweralpha]
.. [.ph .cmd]#Найдите область [.keyword]*Автоматическое завершение*.#
.. [.ph .cmd]#При помощи переключателя [.keyword]*Завершение при завершении подчиненных* выберите предпочтительный вариант завершения родительского задания при завершении подчиненных заданий: #
* [.keyword]*Не завершать* - автоматического завершения задания не произойдет. Задание может быть завершено только вручную при помощи выполнения соответствующей операции из интерфейса карточки;
* [.keyword]*При завершении всех подчиненных* - задание будет автоматически завершено после того, как будут завершены все его подчиненные задания;
* [.keyword]*При завершении любого из подчиненных* - для завершения родительского задания достаточно завершения любого из подчиненных заданий.
.. [.ph .cmd]#Чтобы при завершении родительского задания автоматически завершались все подчиненные задания, установите флаг [.keyword]*При завершении задания автоматически завершать подчиненные*. #
+
По умолчанию параметр отключен.
+
Родительское задание будет автоматически завершено, если завершение выполняется из дочерней карточки. Чтобы задание завершилось, нужно чтобы из текущего состояния можно было выполнить переход в состояние [.keyword]*Прекратить исполнение*.
. [.ph .cmd]#Чтобы настроить добавление отчета при выполнении задания:#
[loweralpha]
.. [.ph .cmd]#Найдите область [.keyword]*Завершение задания*.#
.. [.ph .cmd]#Чтобы при завершении задания от пользователя потребовалось ввести отчет, установите флаг [.keyword]*Ввести отчет*. #
+
Для ввода отчета в разметке карточки необходимо настроить элемент управления [.keyword .parmname]_Текст_ с привязкой к динамическим данным: секция = `Задание`, Поле = `Отчёт`.
.. [.ph .cmd]#Чтобы при завершении задания от пользователя потребовалось приложить файл отчета, установите флаг [.keyword]*Добавить файл отчета*. #
+
Для завершения задания в разметке карточки необходимо настроить элемент управления [.keyword .parmname]_Ссылки_ с привязкой к динамическим данным: секция = `Задание`, поле = `Список ссылок`. Также нужно выбрать типы ссылок для отчетов в настройках пользовательского вида карточки [.keyword .parmname]_Задание_.
+
При необходимости, добавленный отчет может быть скопирован из дочернего задания в родительское. Операция может быть выполнена средствами элемента управления link:Card_extra_perform_tree.adoc[Дерево исполнения].
. [.ph .cmd]#Чтобы настроить завершение, зависимое от связанных заданий:#
[loweralpha]
.. [.ph .cmd]#Найдите область [.keyword]*Завершение, зависимое от связанных заданий*.#
.. [.ph .cmd]#Выберите предпочтительный вариант завершения:#
* [.keyword]*Не завершать* - задание не будет завершено;
* [.keyword]*Завершать* - задание будет завершено;
* [.keyword]*На усмотрение пользователя* - пользователю будет выдано предупреждающее сообщение со списком заблокированных заданий, с вариантами ответа Продолжить / Прекратить завершение задания.

*На уровень выше:* xref:../pages/Tcard.adoc[Работа с карточкой «Задание»]
