= Выбор вида подчиненного задания

Вид подчиненных заданий, которые создаются из карточек _Задание_, настраивается для вида задания в _Справочнике видов карточек_. Однако, имеется возможность индивидуального выбора вида подчиненного задания для конкретного экземпляра задания.

.Чтобы настроить вид подчиненного задания, создаваемого из данного экземпляра задания, выполните следующие действия:
. Откройте карточку _Задание_, затем перейдите на xref:Tcard_settings.adoc[вкладку *Настройки*].
. Найдите область *Вид подчиненного задания*#
. Выберите предпочтительный вариант настройки вида:
* *Того же вида, что и родительское задание* – дочернее задание будет автоматически наследовать вид родительского задания;
* *Выбор любого вида задания* - пользователь может выбрать произвольный вид из числа доступных;
* *Выбор вида из ограниченного списка* – пользователь может выбрать вид из сформированного списка. В расположенном ниже поле можно вручную указать, какие именно виды будут доступны для выбора.  
+
При создании нового задания из открытой карточки _Задание_ пользовательского вида будет создаваться новая карточка _Задание_, вид карточки будет соответствовать выполненным настройкам.
