= Настройки завершения задания

Возможность автоматического завершения задания имеется только в том случае, если карточка задания находится в состоянии _В работе_ (доступен переход _Прекратить исполнение_).

Настройки завершения карточек _Задание_ определяются для вида задания в _Справочнике видов карточек_. Однако, имеется возможность индивидуального изменения данных настроек для конкретного экземпляра задания.

.Чтобы настроить параметры завершения задания:
. Откройте карточку _Задание_, затем перейдите на вкладку xref:Tcard_settings_extra.adoc[*Расширенные настройки*].
. Чтобы настроить автоматическое завершение задания:
+
.. Найдите область *Автоматическое завершение*.
.. При помощи переключателя *Завершение при завершении подчиненных* выберите предпочтительный вариант завершения родительского задания при завершении подчиненных заданий:
+
* *Не завершать* -- автоматического завершения задания не произойдет. Задание может быть завершено только вручную при помощи выполнения соответствующей операции из интерфейса карточки;
* *При завершении всех подчиненных* -- задание будет автоматически завершено после того, как будут завершены все его подчиненные задания;
* *При завершении любого из подчиненных* -- для завершения родительского задания достаточно завершения любого из подчиненных заданий.
+
.. Чтобы при завершении родительского задания автоматически завершались все подчиненные задания, установите флаг *При завершении задания автоматически завершать подчиненные*.
+
По умолчанию параметр отключен.
+
Родительское задание будет автоматически завершено, если завершение выполняется из дочерней карточки. Чтобы задание завершилось, нужно чтобы из текущего состояния можно было выполнить переход в состояние *Прекратить исполнение*.
+
. Чтобы настроить добавление отчета при выполнении задания:
+
.. Найдите область *Завершение задания*.
.. Чтобы при завершении задания от пользователя потребовалось ввести отчет, установите флаг *Ввести отчет*.
+
Для ввода отчета в разметке карточки необходимо настроить элемент управления _Текст_ с привязкой к динамическим данным: секция = `Задание`, Поле = `Отчёт`.
+
.. Чтобы при завершении задания от пользователя потребовалось приложить файл отчета, установите флаг *Добавить файл отчета*.
+
Для завершения задания в разметке карточки необходимо настроить элемент управления _Ссылки_ с привязкой к динамическим данным: секция = `Задание`, поле = `Список ссылок`. Также нужно выбрать типы ссылок для отчетов в настройках пользовательского вида карточки _Задание_.
+
При необходимости добавленный отчет может быть скопирован из дочернего задания в родительское. Операция может быть выполнена средствами элемента управления xref:Card_extra_perform_tree.adoc[Дерево исполнения].
+
. Чтобы настроить завершение, зависимое от связанных заданий:
+
.. Найдите область *Завершение, зависимое от связанных заданий*.
.. Выберите предпочтительный вариант завершения:
+
* *Не завершать* -- задание не будет завершено;
* *Завершать* -- задание будет завершено;
* *На усмотрение пользователя* -- пользователю будет выдано предупреждающее сообщение со списком заблокированных заданий, с вариантами ответа Продолжить / Прекратить завершение задания.
