[[ariaid-title1]]
== Настройка делегирования задания вручную

Делегирование вручную предоставляет некоторую свободу действий в управлении заданием.

Чтобы настроить возможность делегирования задания вручную, выполните следующие действия:

. [.ph .cmd]#Откройте карточку [.dfn .term]_Задание_, затем перейдите на xref:Tcard_settings.html[вкладку [.keyword]*Настройки*].#
. [.ph .cmd]#В области [.keyword]*Делегирование вручную* установите флаг [.keyword]*Задание может быть делегировано вручную*.#
+
Станут доступны два параметра: *Разрешено делегировать любому сотруднику* и *Выбрать делегата из списка*
. [.ph .cmd]#Чтобы разрешить делегирование всем сотрудникам, установите флаг [.keyword]*Разрешено делегировать любому сотруднику*.#
. [.ph .cmd]#Чтобы ограничить список сотрудников, которым можно делегировать задания, установите флаг [.keyword]*Выбрать делегата из списка*, затем сформируйте список.#
+
Для выбора сотрудника используется стандартный диалог выбора делегата.

*На уровень выше:* link:../pages/Tcard.adoc[Работа с карточкой «Задание»]
