= Завершение задания

Завершение задания производится после того, как работа над заданием будет завершена.

.Завершение задания возможно из следующих состояний:
* `Не начато` - задание завершается сразу же после его получения;
* `В работе` - задание завершается после того, как была выполнена задача, поставленная исполнителю в задании;
* `Возврат с делегирования` - задание завершается сразу после того, как задание было возвращено от последнего делегата.

Способ завершения задания и связанных с ним заданий зависит от xref:Tcard_finish_settings.adoc[параметров завершения], определенных пользователем в _Справочнике видов карточек_ или в самом задании. При завершении задания от пользователя может потребоваться заполнение:

* Файла или ссылки отчета – если для задания проставлен флаг *При завершении задания необходимо добавить файл отчета*;
* Отчета или Файл отчета или ссылка отчета – если для задания проставлен флаг *При завершении задания необходимо ввести отчет*;
* Полей, указанных в настройке вида карточки задания *При завершении задания необходимо заполнить поля* с признаком "Обязательно".

При необходимости производится возврат задания с делегирования. Если сотрудник, которому возвращается задание, не активен, и в задании установлен флаг *Автоматически делегировать заместителю*, выполняется автоматическое делегирование возврата. Текущим исполнителем становится заместитель.

Если карточка задания перешла в состояние `Завершено`, будут принудительно завершены дочерние и родительские задания в соответствии с xref:Tcard_finish_settings.adoc[настройками] вида задания в _Справочнике видов карточек_ или самом задании:

* Если у задания есть подчиненные, они будут принудительно завершены, если в настройках задания (вида задания) установлен флаг *При завершении задания автоматически завершать подчиненные*;
* Если у задания есть родительское, для родительского проверяется настройка *Автоматическое завершение при завершении подчиненных*. Выполняется принудительное завершение родительского задания, если выполняется условие настройки.

Если связанные задания не могут быть завершены (например, заблокированы), будут выполнены действия в зависимости от настройки *Завершение задания при невозможности завершения связанных*:

* *Разрешить* - заблокированные задания будут пропущены, произойдет завершение задания.
* *Запретить* - пользователю будет выдано предупреждающее сообщение со списком заблокированных заданий, после чего процесс прекращения подчиненных заданий будет завершен.
* *На усмотрение пользователя* - пользователю будет выдано предупреждающее сообщение со списком заблокированных заданий, с вариантами ответа Продолжить / Прекратить завершение задания.

После нажатия кнопки *Завершить* в журнале событий карточки основного и связанного задания появляется соответствующая запись:

* Если задание завершено:
** Текущий пользователь;
** Завершено/Прекращено исполнение – в зависимости от операции
* Если выполнен возврат с делегирования:
** Текущий пользователь;
** Возвращено с делегирования <Текущему исполнителю>
* Если выполнялось автоматическое делегирование при возврате, делается дополнительная запись в журнале:
** Задание автоматически делегировано заместителю<ФИО> в связи с тем, что назначенный исполнитель задания<ФИО> не активен.
