= Смена состояний карточки "Задание"

Согласно стандартному набору состояний, который устанавливается для карточки в момент создания её вида, жизненный цикл карточки начинается с запуска задания и оканчивается переходом *Завершить задание*. Каждый переход между состояниями фиксируется в журнале операций/переходов.

Операция *Изменить*, доступная в состояниях *Отклонено* и *Отозвано*, используется для того, чтобы уже запущенное задание можно было изменить и начать заново. При этом карточка возвращается в состояние *Инициализация*, а в журнал добавляется соответствующая запись.

В состоянии *Завершено* ни одно из действий не может быть применено к карточке.

В таблицах указаны доступные действия для каждого состояния.

[options="header"]
|===
|Состояние/операция |Отправить |Изменить |Отозвать |Отклонить |Отложить |В работу |Делегировать

|Инициализация |X | | | | | |
|Не начато | | |X |X | |X |X
|В работе | | |X |X |X | |X
|Отклонено | |X |X | | |X |
|Отозвано | |X | | | | |
|Отложено | | |X |X | |X |
|Делегировано | | |X |X | |X |X
|Возврат с делегирования | | |X | | | |
|Завершено | | | | | | |
|На приемке | | |X | | | |
|На доработке | | |X | |X |X |X
|===

[options="header"]
|===
|Состояние/операция |Не брать в работу |Завершить |Прекратить исполнение |Отменить делегирование |На доработку |Принять

|Инициализация | | | | | |
|Не начато | |X | | | |
|В работе |X |X |X |X | |
|Отклонено | | | | | |
|Отозвано | | | | | |
|Отложено | | | | | |
|Делегировано | | | |X | |
|Возврат с делегирования | |X | | | |
|Завершено | | | | | |
|На приемке | | |X | |X |X
|На доработке | | |X | | |
|===
