= Взятие задания в работу

Данная операция переводит карточку в состояние _В работе_. Операция может быть выполнена в следующих состояниях (на основе стандартного "автомата состояний"):

* _На начато_ – основной сценарий, исполнитель приступает к работе над заданием;
* _Отклонено_ – исполнитель ранее отклонил задание;
* _Отложено_ – исполнитель возвращает в работу отложенное задание;
* _Делегировано_ – новый исполнитель приступает к работе над делегированным ему заданием;
* _Возврат с делегирования_ – сотрудник, делегировавший задание обрабатывает возврат;
* _На доработке_ – по результатам контроля задание возвращено на доработку.

При выполнении перехода _В работу_ исполнителем задания назначается текущий пользователь.

Когда задание взято в работу, в списке доступных операций появляется пункт "Вернуть в "Не начато". Данная операция противоположна по смыслу взятию задания в работу и предназначена для тех случаев, когда исполнитель желает вернуть задание в состояние, предшествовавшее взятию в работу.

Если задание берет в работу не назначенный исполнитель, то происходит автоматическое делегирование задания ему.
