= Работа с карточкой "Задание"

Карточка _Задание_, входящая в состав библиотеки _Базовые объекты_, предназначена для доставки на рабочие места пользователей информации о необходимости выполнения того или иного действия в рамках налаженного документооборота, а также доставки файлов, карточек и ссылок на внешние по отношению к системе _Docsvision_ объекты. Карточка входит в комплект поставки системы _Docsvision 5_. Название карточки соответствует названию ее типа в _Справочнике видов карточек_.

Карточка _Задание_ является ключевым элементом как приложения _Управления документами_, так и модуля _Управление процессами_. Карточка может быть настроена для поддержки различных сценариев обработки файлов, карточек, других объектов. Средства настройки позволяют создавать задания различных видов, например, задание на исполнение, на согласование, на контроль, на консолидацию документа и пр. Виды могут различаться по набору допустимых действий, состояний и набору данных, которые доставляются пользователю. В том числе, карточка может использоваться в качестве контейнера для других карточек.

В карточке реализованы следующие операции:

* xref:Tcard_perform_log_view.adoc[просмотр хода исполнения];
* xref:Tcard_hand_delegating.adoc[настройка делегирования вручную];
* xref:Tcard_performer_busines_calendar.adoc[подключение бизнес-календаря исполнителя задания];
* xref:Tcard_routing_type.adoc[настройка типа маршрутизации задания];
* xref:Tcard_slavetask_type.adoc[выбор вида подчиненного задания];
* xref:Tcard_reject_comment_requst.adoc[запрос комментария при отклонении задания];
* xref:Tcard_copy_fields_to_slave_task.adoc[копирование полей в подчиненное задание];
* xref:Tcard_finish_settings.adoc[настройка способа завершения задания];
* xref:Tcard_change_deadline.adoc[изменение сроков исполнения задания];
* xref:Tcard_print.adoc[печать карточки];
* xref:Tcard_change_state.adoc[смена состояний карточки].

Дополнительно могут быть выполнены:

* настройка состава полей (динамических);
* расширение базовой машины состояний задания;
* формирование дополнительных событий и определение логики обработки событий;
* настройка ролевой модели (в частности прав на обрабатываемый документ);
* возможность настройки дизайнов для различных состояний, видов и ролей;
* возможность добавления связанных карточек.   