= Просмотр хода исполнения задания

.Чтобы посмотреть состояние исполнения задания, выполните следующие действия:
. Откройте карточку _Задание_.
. Перейдите на вкладку xref:Tcard_perform_log.adoc[*Ход исполнения*].
. В поле *Текущие исполнители* просмотрите перечень сотрудников, назначенных исполнителями текущего задания (для этого задание должно быть уже запущено).
+
Исполнителей может быть несколько, при этом для завершения задания необязательно действия именно от всех участников задания. Список исполнителей может быть заранее настроен в _Справочнике видов карточек_, при этом если задание взято в работу, то в данном поле будет отображаться только сотрудник, взявший задание в работу.
. В поле *Завершил* просмотрите данные о сотруднике, который завершил задание (перевел задание в состояние _Завершено_).
. При необходимости в поле *Процент исполнения* введите значение от 0 до 100, соответствующее текущему этапу жизненного цикла карточки.
+
В состоянии *Завершено* данное поле автоматически заполняется значением *100*.
