[[ariaid-title1]]
== Уровень подготовки пользователя

Для эксплуатации модуля «Базовые объекты» определены две пользовательские роли: администратор Docsvision и конечный пользователь. Настройку [.dfn .term]_решения_ на базе системы Docsvision с использованием Модуля выполняет инженер Docsvision.

Администратор Docsvision устанавливает Модуль (серверную и клиентскую части), выполняет первоначальную настройку, выявляет неполадки в работе бизнес-процессов Модуля в процессе эксплуатации.

Инженер Docsvision настраивает работу с карточками Модуля с помощью предоставляемых [.dfn .term]_конструкторов_ и [.dfn .term]_справочников_ Docsvision, разрабатывает скрипты карточек, настраивает бизнес-процессы.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе Docsvision, их обработкой, согласованием и т.п.

Администратор или конечный пользователь Docsvision заполняют и актуализируют справочники Docsvision.

Все пользователи Модуля должны обладать базовыми навыками работы на персональном компьютере, в программе «Windows-клиент» (модуль «Docsvision 5. Windows-клиент»).

Администратор Docsvision должен обладать навыками настройки модуля «Docsvision 5. Платформа», формирования сертификатов ЭЦП в ОС Windows, использования криптопровайдера «КриптоПро»; а также ознакомиться с документом [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_#.

Инженер Docsvision должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение Docsvision, иметь опыт разработки на языке C# или Visual Basic .NET; должен ознакомиться с данным руководством пользователя, с документами [.ph]#[.dfn .term]_Модуль «Docsvision 5. Базовые объекты». Руководство администратора_# и [.ph]#[.dfn .term]_Docsvision 5.5. Руководство программиста_#.

Конечные пользователи должны ознакомиться с данным руководством пользователя.

*На уровень выше:* xref:../pages/Introduction.adoc[Введение]
