[[ariaid-title1]]
== Выполнение заданий в почтовом клиенте

Пользователь может использовать почтовый клиент для выполнения заданий с типом маршрутизации «Задача Почтового клиента». В этом случае исполнителю задания будут поступать письма, содержащие описание задания и кнопки завершения. Для завершения задания можно использовать как почтовую программу, так и стандартный «клиент» Docsvision.

[NOTE]
====
[.note__title]#Note:# При использовании почтового клиента Gmail в операционной системе iOS, а также Microsoft Outlook в операционной системе Android, при формировании ответного письма часть содержимого темы письма обрезается, что делает невозможным обработку данных писем на сервере Docsvision. Используйте альтернативные почтовые клиенты в данном случае.

Из-за известной ошибки в письмах, открытых в Microsoft Outlook версии 2013, могут не отображаться изображения, содержащиеся в тексте. В Microsoft Outlook версии 2016 и выше данная ошибка отсутствует.
====

Для возможности выполнения заданий в почтовом клиенте требуется специальная настройка, которая выполняется администратором Docsvision.

* *xref:../pages/Receive_Messages.adoc[Письма, формируемые при маршрутизации заданий в почту]* +
* *xref:../pages/Work_with_Task.adoc[Исполнение заданий]* +
* *xref:../pages/Work_with_Documents.adoc[Работа с документами – вложениями в почтовое сообщение]* +
* *xref:../pages/Approval_and_Signing.adoc[Согласование/подписание документа]* +

*Parent topic:* xref:../pages/Operations.adoc[Описание операций]
