= Исправленные ошибки

* DV5-5420 (SUP-3297). При многократном открытии карточек ``Делопроизводство"" в элементе управления HTMLBrowser отображались данные от других карточек.
* DV5-5551 (SUP-3441). Множественный выбор из справочника сотрудников в Windows-клиенте не ограничивал выбор организаций или подразделений. Несмотря на установленные ограничения, всегда можно было выбрать и организации и подразделения.
* DV5-5569 (SUP-3447). Возникала ошибка при копировании видов карточек. Если при копировании вида согласиться с удалением режимов создания карточек, в некоторых случаях режимы оставались неизменными. Ошибка затрагивала режим создания карточек по штрих-коду в РМА и Windows-клиенте.
* DV5-5570 (SUP-3467). В конструкторе разметок при вызове контекстного меню в структуре разметки не отображалось описание одного из пунктов контекстного меню.
* DV5-5695 (SUP-3662). Исправлена ошибка, когда не изменялся руководитель в карточке сотрудника. Если в справочнике сотрудников руководитель подразделения был изменён, то в карточке у сотрудников этого подразделения новый руководитель автоматически не изменялся.
* DV5-5711. В Справочнике видов карточек можно было удалить вид, подвиды которого заблокированы.
* DV5-5725 (SUP-3679). Исправлена ошибка, когда значение расширенных полей в конструкторе справочников отображалось только при первом открытии. При последующих открытиях расширенные поля оказывались пустыми.
* DV5-5736 (SUP-4540, SUP-3691). При работе с подписанным файлом, который был возвращён на подготовку в Windows-клиенте появлялось предупреждение: ``Данный файл подписан цифровой подписью, при изменении файла подпись будет недействительна. Вы уверены, что хотите продолжить?"". Предупреждение появлялось даже, если у пользователя отсутствовали права на изменение файла.
* DV5-5745 (SUP-3727). При печати карточки без преобразования в Windows-клиенте возникала ошибка ``Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции"".
* DV5-5796 (SUP-3795). В подчинённые задания группы заданий на исполнение не копировались отчёты из родительского задания, от которого была создана группа заданий.
* DV5-5805 (SUP-3819). Атрибутивный поиск по полю ``Получатель-организация"" не возвращал карточку с нужным контрагентом, выбранным в таблице получателей.
* DV5-5807 (SUP-4072). Исправлена ошибка, из-за которой отсутствовала иконка принятия решения в задании.
* DV5-5822 (SUP-3861). При добавлении элемента управления ``Ссылки"" в карточки, элемент управления становился неактивным в карточках, созданных до добавления ЭУ.
* DV5-5822 (SUP-4206). При добавлении элемента управления ``Ссылки"" в карточки, элемент управления становился неактивным в карточках, созданных до добавления ЭУ.
* DV5-5822 (SUP-4206, SUP-3861). При добавлении элемента управления ``Ссылки"" в карточки, элемент управления становился неактивным в карточках, созданных до добавления ЭУ.
* DV5-5831 (SUP-3795). Отчеты, приложенные к родительскому заданию на исполнение, не копировались в подчинённую группу заданий.
* DV5-5834 (SUP-3849). При отсылке уведомления о задании с альтернативным исполнением для двух исполнителей возникала ошибка в бизнес-процессе ``Экземпляр процесса Маршрутизация заданий в почту"". Из-за однократной ошибки уведомление приходило только одному исполнителю, повторных попыток отправить уведомление БП не предпринимал.
* DV5-5842 (SUP-3888). В элементе управления таблица карточки документа числовые значения отображались с большим количеством нулей после запятой.
* DV5-5881 (SUP-4034). Одновременная загрузка нескольких файлов через элемент управления ``Файлы"" заканчивалась ошибкой ``Индекс находился вне границ массива"".
* DV5-5892 (SUP-3916). Исправлена ошибка, когда при обновлении модуля платформа до версии 5.5.2 не осуществлялось копирование полей ``State"", ``Kind"" из секций ``System"" в секции ``MainInfo"".
* DV5-5914 (SUP-3958). Возникала ошибка ``Элемент с указанным ключом не найден в коллекции"" при попытке сохранения резолюции после смены ответственного исполнителя.
* DV5-5978 (SUP-4043). Возникала ошибка ``Object reference not set to an instance of an object"" при запуске клиентского скрипта смены состояния карточки.
* DV5-5983 (SUP-4059). Комментарии по заданиям на согласование, выполненным через почтовый клиент не попадали в лист согласования в карточке согласования.
* DV5-5988 (SUP-4016). Исправлена ошибка, когда Windows-клиент становился недоступным при смене состояния задания на согласование.
* DV5-5998 (SUP-4038). Возникала ошибка недостаточных прав доступа при обработке входящих заданий интеграции в модуле межфилиального обмена.
* DV5-6025 (SUP-4119). Исправлена ошибка, когда при попытке открыть карточку задания появлялось сообщение: ``Не удалось установить соединение с сервером, сервер недоступен"" с добавлением следующей записи в журнал: ``Collection was modified; enumeration operation may not execute"".
* DV5-6028 (SUP-4139). Исправлена ошибка, при которой не работал пулинг SQL соединений с сервером Postgres из-за того, что соединения каждый раз создавались заново.
* DV5-6049 (SUP-4163). Возникала ошибка ``Object reference not set to an instance of an object"" при создании и отправке документа УД. Ошибка возникала, если в разметку был добавлен элемент управления ``HtmlBrowser"", в котором имелся добавленный клиентом код.
* DV5-6051 (SUP-4152). Возникала ошибка ``Элемент с тем же ключом уже был добавлен"" при добавлении файла к карточке и одновременном сохранении карточки.
* DV5-6054 (SUP-4039). Некорректно работала настройка периода отсутствия в справочнике сотрудников и профиле сотрудника Windows-клиента. Дату ``ПО"" можно было установить в прошлом.
* DV5-6057 (SUP-4188). Значения в полях строки конструктора справочников, добавленных через через конструктор разметок, не отображались.
* DV5-6079 (SUP-4086). В Windows-клиенте дублировалась группа радио кнопок в карточке документа при наличии в разметке пользовательского скрипта.
* DV5-6086 (SUP-4256). Не заполнялось поле ``Номер документа"", если в настройках элемента управления ``Нумератор"" указать ``обязательно для заполнения"".
* DV5-6090 (SUP-4188). Новые поля, добавленные через конструктор разметок в карточку строки справочника, отображались в представлении только после перезапуска навигатора и пропадали при открытии любой карточки.
* DV5-6100 (SUP-4266). Появлялось сообщение ``Делегаты не выбраны"" при попытке выбрать делегата клавишей Enter в форме делегирования задания.
* DV5-6108 (SUP-4276). В Windows-клиенте в элементе управления ``TaskTree"" отображалось задание из предыдущего документа вместо задания из текущего.
* DV5-6120 (SUP-4221). При наличии нескольких версий файла Windows-клиент использовал для проверки подписи случайную подпись. Это вызывало ошибку при проверке подписи ``файл не подписан"".
* DV5-6127 (SUP-4312). Кнопка раскрытия папок ``+"" отображалась только после принудительного обновления, если опция подсвечивания непрочитанных карточек была отключена.
* DV5-6133 (SUP-4323). Возникала ошибка ``Недостаточно прав для изменения вида. Вид будет открыт в режиме только для чтения."" при открытии справочника в режиме ActiveMode = Select.
* DV5-6146 (SUP-4338). Исправлена ошибка, при которой задания бизнес-процесса модуля Делопроизводство 4.5 не открывались у исполнителя.
* DV5-6148 (SUP-4340). Не заполнялся элемент управления ``Сотрудники"" при нажатии Enter с клавиатуры в карточке подразделения.Появлялось предупреждение ``Поле может быть заполнено только значением из справочника"", после нажатия OK, возникало окно ошибки без текста.
* DV5-6176 (SUP-4266). В окне выбора делегата для задания не работал переход к элементам по кнопке Tab.
* DV5-6267 (SUP-4374). Исправлена ошибка, при которой в вычисляемом поле переставало отображаться значение, если использовалась конкатенация.
* DV5-6287 (SUP-4491). Возникала ошибка в триггере переноса значений системных полей при массовом изменении строк
* DV5-6300 (SUP-4383). Если в справочнике сотрудников аккаунт пользователя указывался в отличающемся регистре, то при синхронизации роли или группы с опцией ``Удалять объекты"" аккаунт удалялся.
* DV5-6313 (SUP-4522). Исправлена ошибка, при которой не происходила отписка от события при смене состояния карточки документа.
* DV5-6404 (SUP-4679). В консоли настройки отсутствовал BackOffice SnapIn для шифрования учётных данных.
* DV5-6408 (SUP-4620). В карточке документа, открытой через задание, прокрутка не прокручивала до конца.
* DV5-6448 (SUP-4738). Исправлена ошибка, когда после обновления модуля Платформа до версии 5.5.3 инициатору согласования становилась недоступна кнопка Завершить этап если он не состоял в группе Администраторы КС.
* DV5-6453 (SUP-4645). Возникала ошибка при попытке создания подразделения в справочнике контрагентов, если для карточки вида подразделения контрагента добавлена секция типа структура и поле RefCardId для хранения ссылок на другие карточки.
* DV5-6455 (SUP-4645). Возникала ошибка ошибка при редактировании организации в справочнике сотрудников, если для карточки вида подразделения была добавлена секция типа ``структура"" и поле RefCardId для хранения ссылок на другие карточки.
* DV5-6478 (SUP-4789). Исправлена ошибка, из-за которой не срабатывало событие CardClosing для карточки строки справочника.
* DV5-6487 (SUP-4817). При отмене создания контрагента возникала ошибка ``Невозможно выполнить данную операцию в связи с ограничением доступа"".
* DV5-6493. Комментарий, добавленный при изменении сроков выполнения задания контролером, отображался в ЭУ только после добавления нового комментария.
* DV5-6502. Исправлена ошибка, когда метод FilesView.RefreshFiles в Docsvision 5.5 не всегда вызывал обновление элемента управления ``Файлы"".
* DV5-6505 (SUP-4869). При удалении карточки файла в Windows-клиенте удалялся только приложенный файл.
* DV5-6514. После копирования основного файла карточка становилась недоступной.
* DV5-6526 (SUP-4999). Исправлена ошибка, при которой пользователь без AccountSID не мог войти в Web-клиент.
* DV5-6538 (SUP-4919). После обновления модуля Платформа до версии 5.5 в Windows-клиенте, в столбцах элемента управления ``Таблица"" с привязкой полей float перестали отображаться разделители тысяч в больших числах.
* DV5-6560 (SUP-4907). Исправлена ошибка, когда функция BackOffice, возвращающая штампы времени карточек, передаваемые ей возвращала null.
* DV5-6572 (SUP-4968). В справочнике контрагентов поля `FirstName` и `MiddleName` у сотрудников при пустых значениях вместо NULL имели пустую строку.
* DV5-6604 (SUP-5028). Возникала ошибка ``Файл не найден"" при попытке открыть файл из карточки документа по ссылке в браузере Internet Explorer.
* DV5-6619 (SUP-5039). В письме заместителю не отображался блок о замещении при настроенной маршрутизации ``Письмо с описанием задания"".
* DV5-6628 (SUP-5041). Исправлена ошибка, когда при первом запуске Windows-клиента быстрый поиск по конструктору справочников работал медленно.
* DV5-6629 (SUP-5042). После обновления модуля Платформа с версии 5.4 на версию 5.5.3 создание карточек занимало более 10 секунд.
* DV5-6642 (SUP-5059). Во вкладке истории карточки выводилось некорректное сообщение для ЭУ ``Список"" с полем данных Enum.
* SUP-2552. Исправлена ошибка, когда при попытке приложить ссылку к карточке в Windows-клиенте возникала нагрузка на БД большим количеством поисковых запросов..
* SUP-2923. В некоторых случаях не работал выбор элементов в раскрывающемся списке при нажатии клавиш ``Вверх"", ``Вниз"" и ``Enter"".
* SUP-3259. Исправлена ошибка, вызывавшая долгое открытие карточки группы заданий.
* SUP-3539. Возникала ошибка ``Не удалось установить соединение с сервером, сервер недоступен"" при открытии карточки в Windows-клиенте после обновления на версию Docsvision 5.5.
* SUP-3650. Возникала проблема превышения времени отклика карточек задания.
* SUP-3784. Исправлена ошибка открытия Windows-клиента при переполнении поля LocalizationXml после изменения разметок в конструкторе разметок и сохранением изменений.
* SUP-3790. Некорректно отображались карточки документа ДП при втором открытии, если системный размер текста был увеличен и в карточке имелось поле нумератора.
* SUP-3913. Если сотрудник открывал карточку документа и приложенный к ней .xlsx на редактирование, не создавалась новая версия файла и не сохранялись внесённые изменения.
* SUP-3923. Одновременная загрузка нескольких файлов через элемент управления ``Файлы"" заканчивалась ошибкой ``Индекс находился вне границ массива"".
* SUP-3958. Возникала ошибка ``Элемент с указанным ключом не найден в коллекции"" при попытке сохранения резолюции после смены ответственного исполнителя.
* SUP-4393. Числовые значения в таблице отображались с большим количеством нулей после запятой.
* SUP-4420. В окне делегирования карточки не получалось переключиться кнопкой Tab на поле ``Комментарий"".
* SUP-4586. При попытке создать ссылку на карточку из задания Windows-клиент оказывался настроен на несуществующие виды карточек.
* SUP-4598. При добавлении файлов в карточку из элемента управления ``Файлы"" второй файл оказывался неактивен.
* SUP-4793. При попытке смены состояния сотрудника из Windows-клиента возникала ошибка ``Произошла ошибка при смене состояния сотрудника"" при установленной версии модуля Платформа 5.5.2.
* SUP-5019. Исправлена ошибка, вызывавшая большую нагрузку на БД при попытке приложить ссылку.
* SUP-5049. Из папки %temp% не удалялись временные файлы при использовании протокола wcf.
* WebC-8613 (SUP-4104). Исправлена ошибка, при которой версия файла, добавленная согласующим через почтовый клиент, не отображалась в карточке задания по консолидации/согласованию.
* WebC-8830 (SUP-4039). Возникала ошибка при настройке периода отсутствия, в окне смены состояния не выполнялась проверка даты с .. по.
* WebC-9423 (SUP-4342). При завершении задания на исполнение администратором (контролёром) за ответственного исполнителя, возникала ошибка ``Переход из состояния `В работе" в состояние `Завершено" по операции `Завершить" недоступен"".
