= Изменения

== Функциональные изменения

[arabic]
. Добавлена возможность фиксировать дату устаревания сертификата подписи. Дата устаревания фиксируется при наложении подписи любым доступным способом из любого клиента.
. Вместе с установкой модуля теперь в справочник сотрудников добавляется группа **_Системные группы**. Системные группы определяют дискреционную безопасность для текущей используемой базы данных. Пользователи, указанные в одной из системных групп Справочника сотрудников для БД, считаются также указанными в одноимённой серверной группе, но не наоборот.
. В справочник "Конструктор ролей" добавлены три новых поисковых слова для ролей:
* В группе без подчиненных из поля карточки.
* В Организации/Подразделении с подчиненными из поля карточки.
* В Организации/Подразделении без подчиненных из поля карточки.
. Слово "В Группе из поля карточки" переименовано на "В группе с подчиненными из поля карточки" Поле карточки может быть выбрано из табличной секции карточки в колонке _Значение_.
