= Список изменений в версии

== Функциональные изменения

Учитывать HTML-форматирование при экспорте::
HTML-текст почтовых уведомлений в новых БД по умолчанию будет отображаться в отформатированном виде. Подробнее см. xref:desdirs:card-kinds/task/email.adoc#xslt["Настройка почтовых уведомлений"] и xref:user:mail-client/message-result.adoc#xslt["Уведомления о результатах выполнения действия и об ошибках"].

Почтовые уведомления о заданиях::
include::user:partial$excerpts.adoc[tags=notify]

Группы заданий на Службе {ws}::
В данной версии модуля для полноценной работы *групп заданий* требуется наличие установленного модуля xref:workerservice::index.adoc[Служба {ws}]. +
Возможность создавать *задания* не требует установки Службы {ws}, но будет отключена в следующих версиях.

[#worker]
Расширение Службы {ws}::
Теперь при установке модуля поставляется расширение Службы {ws} для обработки корневых видов _Заданий_, _Групп заданий_. Обработчик будет также использован для всех подчиненных видов.
+
Компонент доступен для установки только, если xref:workerservice:admin:install.adoc[установлен] модуль "Служба фоновых операций" версии 5.5.2 и выше.

== Оптимизации

* Оптимизирована xref:desdirs:layouts/edit-extended-metadata.adoc#loading[загрузка расширенных метаданных] в базу данных, теперь обновляются только секции с метаданными, изменёнными в текущем сеансе
* Оптимизировано xref:admin:cache-invalidation.adoc[кэширование операндов] ролевой модели из связанных карточек.