= Создание карточки "Документ"

Карточка _Документ_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта. В базовый комплект поставки системы _{dv} 5_ (при отсутствии модуля _{ud}_) входит базовый тип карточки _Документ_. Данный тип может использоваться для создания карточек, однако его настройки не подлежат изменению. Поэтому, при работе с системой рекомендуется пользоваться дочерними видами карточек, созданными на основе базового типа _Документ_.

[IMPORTANT]
====
Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====

.Создание карточки _Документ_ может быть выполнено следующими способами:
* В программе {wincl}:
** с помощью ленты {wincl}а;
** с помощью меню {wincl}а;
** по заранее созданному шаблону;
** из открытой карточки того же вида;
** из открытой карточки по кнопке *Создать карточку*.
* В приложении _Рабочее место администратора_:
** с помощью инструментов модуля;
** по шаблону;
** из открытой карточки того же типа;
** из открытой карточки по кнопке *Создать карточку*.

.Также для карточек _Документ_ существуют дополнительные способы создания:
* xref:document/DCard_create_by_barcode.adoc[создание карточки по штрих-коду];
* xref:document/DCard_create_by_file.adoc[создание карточки при перетаскивании файла в {wincl}е];
* xref:Card_extra_links.adoc[по ссылке из другой карточки];
* xref:Card_extra_perform_tree.adoc[из дерева исполнения связанной карточки].

При создании карточки _Документ_ могут применяться настройки, выполненные для данного вида в _Справочнике видов карточек_. Например, при сохранении карточки может выполняться проверка уникальности атрибутов карточки, синхронизация свойств карточки и вложенного файла и другие действия.
