= Работа с файлами карточки "Документ"

Для хранения совместно с регистрационной карточкой документа больших объемов сопутствующей информации к карточкам документов могут прикрепляться файлы.

.Карточка документа может содержать:
* Набор _основных_ файлов, для хранения и обработки которых была создана карточка.
+
Создание новых версий и автоматическое включение в цифровую подпись, доступны только для основных файлов карточки.
+
* Набор _дополнительных_ файлов, поясняющих или дополняющих содержание основных файлов.
+
Например, если основным файлом является распознанная копия документа, одним из дополнительных файлов может быть отсканированное изображение документа.

Приложить можно неограниченное количество файлов, как основных, так и дополнительных. Чтобы сделать из _основного_ файла _дополнительный_ или наоборот, достаточно перетащить файл из одной области в другую.

При отображении файлов применяется сортировка в алфавитном порядке. _Основные_ и _дополнительные_ файлы сортируются отдельно. Порядок отображения файлов в списке обновляется при каждом добавлении и переименовании файлов карточки.

.С основными файлами могут быть выполнены следующие операции:
* xref:document/open-main-file.adoc[Открытие на редактирование];
* xref:document/file-preview.adoc[Предварительный просмотр].
* Сохранение в указанное место файловой системы.
* Копирование в буфер обмена.
* xref:document/file-lock.adoc[Блокировка, возврат с блокировки и отмена блокировки файла в карточке].
* xref:document/file-delete.adoc[Удаление файла].

.С дополнительными файлами могут быть выполнены следующие операции:
* xref:document/file-preview.adoc[Предварительный просмотр].
* Сохранение в указанное место файловой системы.
* Копирование в буфер обмена.
* Выделение всех дополнительных файлов (если их несколько).
* xref:document/file-delete.adoc[Удаление файла].
