= Предварительный просмотр файла

Предварительный просмотр поддерживается как для _основных_, так и для _дополнительных_ файлов.

В режиме чтения файл открывается в xref:document/card.adoc#preview["Области предварительного просмотра"] карточки _Документ_, или в _Панели просмотра_ {wincl}а. Если формат файла не поддерживается, или не установлено соответствующее приложение, предварительный просмотр будет невозможен.

Предварительный просмотр в теле карточки доступен только для форматов, для которых в системе Windows установлено средство предварительного просмотра.

.В большинстве случаев предварительный просмотр используется для файлов следующих форматов:
* Простые текстовые файлы без форматирования.
* Файлы документов Microsoft Office версий 2016x86 и младше: `.doc`,`.docx`,`.xls`, `.xlsx` и остальные.
* Файлы формата `.pdf`.
* Графические файлы: `.jpg`, `.bmp`, `.png` и остальные.

При работе в ОС Windows 2003 с карточкой документа, в области предварительного просмотра могут отображаться не все форматы файлов. В частности, не будут отображаться картинки и файлы Microsoft Office, содержащие изображения.
