= Ознакомиться с историей карточки

Все действия с карточками и файлами фиксируются в системном журнале {dv}. Для просмотра журнала в интерфейсе карточки _Документ_ имеется вкладка xref:document/card.adoc#history[История].

.В журнале фиксируются следующие операции с карточкой, например:
* Карточка открыта.
* Карточка закрыта.
* Карточка сохранена.

.Для действий с основными файлами в базовых карточках фиксируются операции:
* Основной файл был открыт на чтение.
* Основной файл был открыт на редактирование.
* Создана новая версия основного файла с номером 2 автоматически.
* Основной файл был удалён.
* Основной файл был длительно заблокирован.
* Сохранение изменений основного файла с последующим снятием длительной блокировки.
* Отмена изменений основного файла с последующим снятием длительной блокировки.
* Текущая версия основного файла изменена с 2 на 1.
* Добавлен комментарий к документу.
* Добавлен комментарий к версии документа.

[NOTE]
====
В истории фиксируются некоторые операции с дополнительными элементами управления. Для элемента управления _Таблица_ в историю будет записана информация о том, что в таблицу были внесены изменения, без описания самих изменений.
====

Также в истории отображаются системные сообщения службы Workflow.

Настройки системного журнала доступны в приложении _Рабочее место Администратора_ в меню menu:Сервис[Журнал...].
