= Создание карточки "Бизнес-календарь"

Карточка _Бизнес-календарь_ может быть создана различными способами. Однако, все способы создания предполагают выбор вида создаваемого объекта. В базовый комплект поставки системы _{dv} 5_ (при отсутствии модуля _{ud}_) входит базовый тип карточки _Бизнес-календарь_.

Данный тип изменять нельзя, но его можно использовать для создания карточек. Поэтому, при работе с системой рекомендуется пользоваться дочерними видами карточек, созданными на основе базового типа _Бизнес-календарь_.

[IMPORTANT]
====
Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====

.Карточку "Бизнес-календарь" можно создать следующими способами:
* В программе {wincl}:
** Кнопкой на ленте {wincl}а.
** Из меню {wincl}а.
** По заранее созданному шаблону.
** Из открытой карточки того же типа.
** Из открытой карточки по команде _Создать карточку_.
* В программе _Рабочее место администратора_:
** С помощью инструментов модуля.
** По шаблону.
** Из открытой карточки того же типа.
