// tag::history[]
NOTE: Для просмотра истории изменений карточки пользователю потребуется xref:desdirs:roles/access-matrix.adoc[настройка прав ролевой модели] на операцию _Просмотр истории_.
// end::history[]

//tag::impossible[]
Вариант *Добавить согласующих* невозможен в почтовом клиенте.
//end::impossible[]

//tag::worker[]
Для полноценной работы *групп заданий* требуется наличие установленного модуля xref:6.1@workerservice::index.adoc[Служба {ws}]. +
Возможность создавать *задания* не требует установки Службы {ws}, но будет отключена в следующих версиях.
//end::worker[]

//tag::notify[]
Если задания обрабатываются при помощи приложения {wf} и Служба _{wss-new}_ не запущена, почтовые уведомления о заданиях не будут поступать.
//end::notify[]

//tag::lync[]
Если у пользователя установлено приложение xref:additional/additional-lync-integration.adoc[Microsoft Lync], для выбранного сотрудника может отображаться индикатор текущего состояния.
//end::lync[]

//tag::viewer[]
[NOTE]
====
Чтобы открыть файлы формата `.p7s`, воспользуйтесь сторонним приложением _P7S Viewer_.
====
//end::viewer[]

//tag::user-kinds[]
[WARNING]
====
Для создания карточек рекомендуется использовать пользовательские виды карточек. Данные виды создаются специалистами по внедрению системы в _Справочнике видов карточек_.
====
//end::user-kinds[]

//tag::create[]
* В программе {wincl}:
** Кнопкой на ленте {wincl}а.
** Из меню {wincl}а.
** По заранее созданному шаблону.
** Из открытой карточки того же типа.
** Из открытой карточки по команде _Создать карточку_.
* В программе _Рабочее место администратора_:
** С помощью инструментов модуля.
** По шаблону.
** Из открытой карточки того же типа.
//end::create[]

//tag::available[]
NOTE: Поле доступно, если выбран вариант исполнения *_Посследовательный_* и установлен флаг `*На контроле*`.
//end::available[]