= Задания в почтовом клиенте

Пользователь может использовать почтовый клиент для выполнения заданий с типом маршрутизации *_Задача Почтового клиента_*. В этом случае исполнителю задания будут поступать письма, содержащие описание задания и кнопки завершения. Для завершения задания можно использовать как почтовую программу, так и стандартный "клиент" {dv}.

[NOTE]
====
Если используется почтовый клиент Gmail в операционной системе iOS, а также Microsoft Outlook в операционной системе Android, при формировании ответного письма часть содержимого темы письма обрезается, что делает невозможным обработку данных писем на сервере {dv}. В данном случае рекомендуется использовать альтернативные почтовые клиенты.

Также в письмах, открытых в Microsoft Outlook версии 2013, могут не отображаться изображения, содержащиеся в тексте из-за известной ошибки. В Microsoft Outlook версии 2016 и выше данная ошибка отсутствует.
====

Для возможности выполнения заданий в почтовом клиенте требуется специальная xref:admin:task-routing.adoc[настройка], которая выполняется администратором {dv}.
