= Приложить произвольный файл к ответному письму

[NOTE]
====
При работе с письмами следует учитывать, что при прикреплении к письму изображения (картинки, фотографии или скриншота) прикрепленный файл не будет отображаться в письме, если используется встроенный почтовый клиент MacOS, Gmail и Outlook в операционной системе Windows, а также Outlook в операционной системе iOS.
====

.Чтобы приложить к ответному письму произвольный файл:
. Откройте почтовое сообщение.
. В секции почтового сообщения _Действия с заданием_ нажмите ссылку, соответствующую выбранному варианту завершения задания.
+
.Будет открыто новое письмо с параметрами:
* В поле _Кому_ будет скопировано значение из поля _От_ исходного письма с заданием.
* В поле _Тема_ будет помещён идентификатор, соответствующий выбранному варианту завершения.
+
. Приложите к письму нужный файл и введите в поле содержания письма описание приложенного файла.
. Отправьте письмо.
+
В карточке Задание текст письма будет отображаться как текстовый отчёт, а приложенный файл -- как файл отчёта.
+
После обработки полученного письма БП будет изменено состояние задания, а на вкладке _История_ карточки задания будет сделана соответствующая запись.
