= Завершить задание

. Откройте почтовое сообщение с заданием.
. Нажмите кнопку *Завершить* или другой доступный вариант завершения, чтобы открыть окно создания нового письма со следующими параметрами:
+
* В поле _Кому_ будет скопировано значение из поля _От_ исходного письма с заданием.
* В поле _Тема_ будет помещена строка с параметрами выполнения задания на сервере {dv}.
+
Кнопка *Завершить* может быть недоступна, если для завершения требуется изменить поля карточки Задание (исключение приведено ниже). В таком случае письмо будет содержать сообщение `Для завершения задания необходимо открыть карточку задания {dv}`. Чтобы завершить такое задание, откройте его в {wincl}е или в {wc}е.
+
include::partial$excerpts.adoc[tags=impossible]
+
. При необходимости введите отчёт следующим образом:
+
* Текстовый отчёт вводится в поле _Содержание_ письма и передается в поле _Отчет_ карточки задания {dv}.
* Файл отчёта прикладывается к письму как вложение и передается в карточку задания как ссылка на отчёт об исполнении.
+
Если для завершения задания необходимо заполнить *одно* текстовое поле, то это так же можно сделать, введя нужный текст в поле _Содержание_ ответного письма.
+
. Отправьте письмо.

[start=5]
.После обработки полученного письма сервером {dv}:
. Состояние задания изменится на `Завершено`.
. Исполнителю будет отправлено уведомление о результате выполнения или об ошибке.
+
Например, если к заданию не приложен отчёт, который является обязательным для данного задания, сервер {dv} вернет письмо с сообщением: `При завершении задания Вы забыли приложить отчёт`.
