= Делегирование задания

.Чтобы делегировать задание другому исполнителю:
. Откройте почтовое сообщение с заданием.
. Нажмите кнопку *Делегировать без возврата* или *Делегировать с возвратом* (задание вернется на исполнение после выполнения делегатом).
+
.Будет открыто новое письмо со следующими параметрами:
* В поле _Скрытая копия_ (СК) будет скопировано значение из поля _От_ исходного письма с заданием.
* В поле _Тема_ будет помещена строка с параметрами выполнения задания на сервере {dv}.
* В тело письма будет добавлено сообщение: `Выполняется делегирование задания. Для работы с ним необходимо дождаться сообщения о делегировании от системы`.
+
Кнопки *Делегировать без возврата* или *Делегировать с возвратом* могут быть недоступны, если операция делегирования запрещена правами или настройками задания.
+
. В поле _Кому_ укажите адрес электронной почты сотрудника, которому выполняется делегирование. Данный адрес должен быть указан в карточке данного сотрудника в _Справочнике сотрудников_.
. Если нужно, добавьте собственное сообщение для делегата в тело письма.
. Отправьте письмо.
+
Данное письмо будет отправлено делегату и серверу {dv}.

[start=6]
.После обработки полученного письма сервером {dv}:
. Состояние задания изменится на `Делегировано`.
. Исполнителю будет отправлено уведомление о результате выполнения или об ошибке.
. Задание будет передано на исполнение сотруднику с указанным почтовым адресом.
+
Задание делегата выполняется обычным образом: с помощью клиента {dv} или с помощью почтового клиента, если для задания настроена маршрутизация с типом *_Задача Почтового клиента_*.
+
Если выполнено делегирование с возвратом, то задание вернется после исполнения делегатом.
