= Исполнение заданий

В процессе исполнения задания пользователь имеет возможность из полученного почтового сообщения с заданием выполнить следующие операции:

* xref:mail-client/task-open.adoc[Открыть карточку задания].
* xref:mail-client/task-working.adoc[Взять] задание в работу.
* xref:mail-client/task-reject.adoc[Отклонить] задание.
* xref:mail-client/task-delegate.adoc[Делегировать] задание.
* xref:mail-client/task-complete.adoc[Завершить] задание.
* xref:mail-client/attached-docs-view.adoc[Ознакомиться] с приложенным к заданию файлом документа.
* xref:mail-client/attached-docs-atributes.adoc[Ознакомиться] с атрибутами приложенного документа, если администратором выполнены соответствующие настройки).
* xref:mail-client/attached-docs-approve-sign.adoc[Принять] участие в согласовании/подписании документа.

CAUTION: В ответных письмах, формируемых при выполнении задания, *нельзя* изменять значения полей _Кому_, _Тема_, _Скрытая копия_, если о необходимости их изменения явно не сказано в инструкции.

Важно, чтобы ответные письма с исполнением задания отправлялись с почтового адреса, указанного для пользователя в Справочнике сотрудников. Если письмо с исполнением задания будет отправлено с другого адреса, сервер вернёт письмо с темой `Адрес не зарегистрирован`.
