= Удаление элемента из разметки

Любой элемент разметки карточки может быть удален.

Для элементов, которые не являются стандартными для системы _{dv}_, а подключаются при установке дополнительных модулей и приложений системы (например, _{ud}_), рекомендуется вместо операции удаления скрывать элемент, используя настройку xref:layouts/lay_ControlElements_Appearance.adoc[видимости].

.Чтобы удалить элемент из разметки:
. Выделите в области _Разметки_ или области _Структура разметки_ элемент, который требуется удалить.
. Правой клавишей мыши вызовите контекстное меню, затем выберите команду *Удалить элемент*.
+
Элемент перестанет отображаться в разметке.

После удаления дополнительного элемента управления (установленного с дополнительным модулем), он станет доступен для добавления в разметку только после повторного открытия _Конструктора разметок_.

[NOTE]
====
Название элемента управления на *Панели инструментов* может отличаться от названия экземпляра элемента управления, удаленного из разметки.
====
