= Показать текст метки

Любой элемент управления (базовый, дополнительный или пользовательский), включает текстовое поле xref:layouts/lay_Elements_general.adoc#label[*Текст метки*], предназначенное для отображения названия поля в запущенной карточке. Для базовых элементов управления тексты меток не подлежат изменению. Для дополнительных элементов управления (добавляемых пользователями из области _Панель инструментов_), текст метки определяется в свойствах элемента. В зависимости от назначения элемента управления, текст метки может быть либо отображен, либо скрыт.

[NOTE]
====
Существует также дополнительный элемент управления xref:layouts/lay_Elements_Label.adoc[*Метка*], видимость которого определяется не командой *Показать текст метки*, в свойством элемента *Видимость*.
====

.Чтобы отобразить/скрыть текст метки:
. Выделите в области _Разметки_ или области _Структура разметки_ элемент, для которого следует изменить отображение свойства *Текст метки*.
. Правой клавишей мыши вызовите контекстное меню, затем выберите команду *Скрыть текст метки* или *Отобразить текст метки*.
